### ISSUE TITLE
关于 python3 运行报错的问题！

### ISSUE THREAD

**Issue by jzp820927** [SeaHOH/GotoX#1]
环境编码： locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

在你的提示下，我安装了 py3 的 openssl 现在报错变成下面这样了，你再看看：
python3 proxy.py
Traceback (most recent call last):
  File "proxy.py", line 53, in <module>
    from ProxyHandler import GAEProxyHandler, AutoProxyHandler
  File "/root/GotoX/local/ProxyHandler.py", line 38, in <module>
    from GAEUpdata import testgaeip
  File "/root/GotoX/local/GAEUpdata.py", line 115, in <module>
    from GAEFinder import timeToDelay, getgaeip
  File "/root/GotoX/local/GAEFinder.py", line 168, in <module>
    from HTTPUtil import BaseHTTPUtil
  File "/root/GotoX/local/HTTPUtil.py", line 37, in <module>
    class SSLConnection(object):
  File "/root/GotoX/local/HTTPUtil.py", line 160, in SSLConnection
    from makefile import backport_makefile as makefile
ImportError: No module named 'makefile'

你主页上提到的 必须组件：
gevent 1.1.2
pyOpenSSL 16.0.0 及以上
dnslib 0.9.6 及以上
我都已经安装了。。。
不知道是不是还差什么依赖？

pip3 list
cffi (1.8.3)
chardet (2.3.0)
command-not-found (0.3)
cryptography (1.5.2)
devscripts (2.16.2ubuntu3)
dnslib (0.9.6)
gevent (1.1.2)
greenlet (0.4.10)
idna (2.1)
language-selector (0.1)
Magic-file-extensions (0.2)
pip (8.1.2)
pyasn1 (0.1.9)
pycparser (2.16)
pycurl (7.43.0)
pygobject (3.20.0)
pyOpenSSL (16.2.0)
python-apt (1.1.0b1)
python-debian (0.1.27)
python-systemd (231)
requests (2.9.1)
setuptools (28.6.1)
six (1.10.0)
ssh-import-id (5.5)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
wheel (0.29.0)

**Comment by SeaHOH** [comment]
忘了放 3.4 的 makefile 兼容代码了。3.5 应该自带，不过我还没有写导入。
你明天再下载一次吧，直接 clone，那个发布不会保持最新。

**Comment by jzp820927** [comment]
行吧，确实我都是  git pull 更新的。那就等你的 commit 了。

**Comment by jzp820927** [comment]
刚刚 pull 了以后，现在是这个报错，py2 和 py3 都是一样的这个报错，难道是还没更新完？

python3 local/proxy.py
Traceback (most recent call last):
  File "local/proxy.py", line 22, in <module>
    from common import NetWorkIOError
  File "/root/GotoX/local/common/__init__.py", line 17, in <module>
    import clogging as logging
ImportError: No module named 'clogging'

**Comment by SeaHOH** [comment]
@jzp820927 
proxy.py 第15-19 行被我注释掉了，你去掉试一下。windows没问题...

**Comment by jzp820927** [comment]
我把 15-19 注释去掉了，还是这个报错。

head -n 20 local/proxy.py
#!/usr/bin/env python
# coding:utf-8
# Based on GoAgent   3.1.5 by Phus Lu <phus.lu@gmail.com>
# Based on GAppProxy 2.0.0 by Du XiaoGang <dugang.2008@gmail.com>
# Based on WallProxy 0.4.0 by Hust Moon <www.ehust@gmail.com>
# Contributor:
#      SeaHOH          <seahoh@gmail.com>

__version__ = '3.3.0'

import sys
sys.dont_write_bytecode = True

import os
__file__ = os.path.abspath(__file__)
if os.path.islink(__file__):
    __file__ = getattr(os, 'readlink', lambda x: x)(__file__)
cwdir = os.path.dirname(os.path.abspath(__file__))
os.chdir(cwdir)


python3 local/proxy.py
Traceback (most recent call last):
  File "local/proxy.py", line 22, in <module>
    from common import NetWorkIOError
  File "/root/GotoX/local/common/__init__.py", line 17, in <module>
    import clogging as logging
ImportError: No module named 'clogging'

**Comment by SeaHOH** [comment]
好了，又改了。不知道行不，心里没底。
python 太坑了，版本间有差别还想得通，但是作为脚本语言在不同平台的重要行为居然不一致。

**Comment by jzp820927** [comment]
这个说不通啊，XXNET,XXMINI，这些都是一个版本运行所有平台啊。

**Comment by SeaHOH** [comment]
还好现在就你一人在用，造不成大混乱。
等会儿我一定要开两个分支。

**Comment by jzp820927** [comment]
其实用 linux 的挺多的，xxnet 那边经常遇到，可能你项目知道的人少所以目前就我一个人是 linux。
我也觉得你可以开2个分支，专门拿一个分支维护 linux 版

**Comment by SeaHOH** [comment]
ok，这回全部都改了。
你再试一下。

**Comment by jzp820927** [comment]
看样子，估计你还得好好研究下来。

python start.py
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    from local import proxy
ImportError: No module named local

python3 start.py
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    from local import proxy
  File "/root/GotoX/local/proxy.py", line 23, in <module>
    from .common import NetWorkIOError
  File "/root/GotoX/local/common/__init__.py", line 21, in <module>
    from .. import clogging as logging
ImportError: cannot import name 'clogging'

python local/proxy.py
Traceback (most recent call last):
  File "local/proxy.py", line 23, in <module>
    from .common import NetWorkIOError
ValueError: Attempted relative import in non-package

python3 local/proxy.py
Traceback (most recent call last):
  File "local/proxy.py", line 23, in <module>
    from .common import NetWorkIOError
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by SeaHOH** [comment]
想问一下上面报错中的 /root 目录就是根目录那个？
你是直接拉到根目录还是怎么回事。

**Comment by SeaHOH** [comment]
现在无法链接 ``s3.amazonaws.com``，上传不了

**Comment by SeaHOH** [comment]
ok，**l-path** 分支，麻烦你再试一下。

**Comment by jzp820927** [comment]
恩，我说下我的系统环境吧。我是 ubuntu server 16.04 ，没有 X-windows，所以更没有桌面。所以操作都是终端下操作的。
具体操作如下。

cd /root
git clone https://github.com/SeaHOH/GotoX
cd GotoX
python3 start.py 或 python3 local/proxy.py

喜讯，捷报，l-path 分支，可以正常运行了，py2，py3 都正常，通过 start.py 启动。

**Comment by jzp820927** [comment]
还有个问题反馈一下，我看主配置文件 Config.ini
[filter]
action = 3
sslaction = 2

这个配置是 ，http 默认直连， https 默认转发直连。
但是我随便访问了一个 https 网站就报错了。
报错信息如下：
Exception happened during processing of request from ('192.168.1.2', 49451)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/root/GotoX/local/proxy.py", line 69, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/root/GotoX/local/ProxyHandler.py", line 127, in do_CONNECT
    self.do_count()
  File "/root/GotoX/local/ProxyHandler.py", line 117, in do_count
    do_x()
  File "/root/GotoX/local/ProxyHandler.py", line 434, in do_FORWARD
    hostname = self.set_DNS()
  File "/root/GotoX/local/ProxyHandler.py", line 636, in set_DNS
    dns[self.host] = dns_resolve(self.host)
  File "/root/GotoX/local/common/dns.py", line 26, in dns_resolve
    iplist = list(set(socket.gethostbyname_ex(host)[-1]) - GC.DNS_BLACKLIST)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socketcommon.py", line 248, in gethostbyname_ex
    return get_hub().resolver.gethostbyname_ex(hostname)
  File "/usr/local/lib/python3.5/dist-packages/gevent/resolver_thread.py", line 61, in gethostbyname_ex
    return self.pool.apply(_socket.gethostbyname_ex, args)
  File "/usr/local/lib/python3.5/dist-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 373, in get
    return self.get(block=False)
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 363, in get
    return self._raise_exception()
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 343, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python3.5/dist-packages/gevent/hub.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/gevent/threadpool.py", line 207, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

**Comment by SeaHOH** [comment]
ActionFilter 里面有一些规则，你可以删除掉。
不过导入证书也没啥影响，证书名称不会与其它证书冲突。
最后这个报错我也在苦恼，这是遇到了无法解析的主机名，但是我还没找到方法忽略它。

**Comment by jzp820927** [comment]
我看错误提示，好像也是和 DNS 有关。因为 https 我想通过本机 hosts 直接连接。
我看动作说明：
#动作     | 动作名   | 代码
#拦截     | block    |   1
#转发     | forward  |   2
#直连     | direct   |   3
#GAE 代理 | gae      |   4

试了下，sslaction = 2 的时候，就报上面的错，sslaction = 3，会伪造证书，也就是说没有针对 https 的直连动作？

**Comment by SeaHOH** [comment]
等会儿我会更新配置文件，只带 google 网站规则，其它删掉。
如果你连 google 网站规则都不需要，可以自行删除。
配置中的**转发也就是隧道代理**，而**直连是 GotoX 直连**，需要修改数据。
解析就是提交给系统的，但系统中也是配置了自己的 DNS，我也没搞明白，暂时这样。

**Comment by jzp820927** [comment]
也就是目前还不能针对 https 做真正的直连？

**Comment by SeaHOH** [comment]
你所说的**直连**就是我说的**转发**亦即**隧道**。
你可以在 ``ActionFilter.ini`` 中针对 google 修改直连为转发，把注释符换个位置就好了。
>[7-direct]
#[7-forward]

**Comment by jzp820927** [comment]
还是不行。这样设置根本打不开网页。chrome 显示如下：

www.google.com 网页无法正常运作
www.google.com 未发送任何数据。
ERR_EMPTY_RESPONSE

GotoX 的报错，就是上面那个 DNS 的错误。

**Comment by SeaHOH** [comment]
``[7-forward]``下面的规则还在吧？这关系到使用的 IP，因为你先前说有 dns 服务和 host 我就没在意，这里的规则也是起到类似 host 文件的作用。
配置文件除了appid 外还修改了哪些？你现在的配置 ``[dns]/server``应该还是我自己用的 ``127.0.0.1``，可以尝试修改。
还有，我又做了些修改，把 gws 跟一般网站的 ciphers 分开。
然后终于发现那个 DNS 错误怎么回事了，前几天调试时加了一个抛出，然后这几天死活没看见。

**Comment by jzp820927** [comment]
规则就是这样，没做改动，这就是你默认的规则，有问题吗？

[5-forward]
#转发直连，即隧道代理
.android.com = google_hk
scholar.google.com = google_hk
scholar.google.com. = google_hk
ipv6.
.ipip.net

[6-gae]
accounts.google.com
chrome.google.com
.googlevideo.com

#[7-direct]
#代理直连
[7-forward]
#代理转发／隧道
.appspot.com = google_hk
.ggpht.com = google_hk
goo.gl = google_hk
.google.cn = google_hk
.google.com = google_hk
.google.com. = google_hk
.googleapis.com = google_hk
.googlecode.com = google_hk
.googlegroups.com = google_hk
.googlesource.com = google_hk
.googletagservices.com. = google_hk
.googleusercontent.com = google_hk
.google-analytics.com = google_hk
.gstatic.com = google_hk
.youtube.com = google_hk
.ytimg.com = google_hk
.golang.org = google_hk

[8-gae]
#通过 GAE 服务器代理


[9-proxy]
#转发到代理服务器

**Comment by SeaHOH** [comment]
认证的代码我还没有写，我是在3.1.5版基础上改的，所以这个并没有用，但写了应该也不影响，浏览器并没有让你填写用户密码吧。
其它看不出问题，想不通。用这个配置我也无法重现。

**Comment by jzp820927** [comment]
是啊，认证确实没用，不过这个是小问题。你的意思是，在 win 上这个配置一切正常？

**Comment by SeaHOH** [comment]
win7没问题，就这个配置。
要不你更新一下，然后就现在这个配置，``[dns]/servers`` 不用本地的，改为 ``8.8.8.8``之类，加个三两个。

**Comment by jzp820927** [comment]
那我试试吧

**Comment by hcym** [comment]
终于正常运行了

goagent 3.1.18的老货也可以用

速度不慢就是链接反应迟钝，要是能关闭扫描可能改善迟钝

只有一个问题，ubuntu下面手动导入证书无效

只能用--proxy-server="http=127.0.0.1:8086;https=127.0.0.1:8088"
测试的 http

**Comment by SeaHOH** [comment]
``Config.ini`` 里面设置端口，两个端口都支持 http 和 https 。
“手动导入证书无效”是指什么？我没用过 linux，如果是导入浏览器只需要输入“http://gotox.net/ca”就可以，导入系统的话请先下载。

**Comment by SeaHOH** [comment]
@hcym 
才反应过来，你能正常用了。那么 **jzp820927** 使用的转发方式连 google，麻烦你按照他的配置看看能不能用。

**Comment by jzp820927** [comment]
@SeaHOH 其实我测试 http 也没问题，https 伪造证书应该也没问题，就是隧道转发有问题。

**Comment by SeaHOH** [comment]
讲道理，我觉得转发是最稳定的，实在是没有头绪。
你能否再试一下，把 http 默认规则改为转发，看是否正常。

**Comment by jzp820927** [comment]
可以，实在不行，我在 windows 上再试试。

**Comment by hcym** [comment]
证书还没搞好
哎哟，拷贝到另一个机器又出岔了

等老大完善后再看

**Comment by SeaHOH** [comment]
我自己也是用的昨天才新生成的证书，完全没问题。
你们都用的什么浏览器？证书状态是否正常，是无法导入还是导入后使用出问题？
下面是我的浏览器 palemoon v26.4
![x2scrap2](https://cloud.githubusercontent.com/assets/8470820/19859864/b99c66ae-9fc1-11e6-8190-48c1e092ae3c.png)

**Comment by jzp820927** [comment]
我还没测试证书这块，一直在测试 转发。==试试看

**Comment by SeaHOH** [comment]
不想兼容。我把证书和私钥分开储存，现在 XX-Net 这样用不安全，把私钥一起分享出去了。

**Comment by jzp820927** [comment]
刚刚 pull 到了最新代码，看 DNS ，你已经改成其他的了，我就没改了，任何按照你之前说的 把 http 默认动作改为 forward ，结果出现了一样的错误。用 www.ip138.com 测试的

浏览器显示
www.ip138.com 网页无法正常运作
www.ip138.com 未发送任何数据。
ERR_EMPTY_RESPONSE

Gotox 报错为：
----------------------------------------
15:38:37 I 180.97.33.184 "FWD GET tbmsg.baidu.com:80 HTTP/1.1" - -
----------------------------------------
Exception happened during processing of request from ('192.168.1.2', 64928)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/root/GotoX/local/ProxyServer.py", line 67, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/root/GotoX/local/ProxyHandler.py", line 153, in do_METHOD
    self.do_count()
  File "/root/GotoX/local/ProxyHandler.py", line 113, in do_count
    do_x()
  File "/root/GotoX/local/ProxyHandler.py", line 482, in do_FORWARD
    self.forward_socket(remote)
  File "/root/GotoX/local/ProxyHandler.py", line 610, in forward_socket
    remote.sendall(rebuilt_request)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socket3.py", line 385, in sendall
    data_memory = _get_memory(data)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socket3.py", line 29, in _get_memory
    mv = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
----------------------------------------
15:38:37 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55527
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;twitter.com:443.               IN      A socket: OSError(101, 'Network is unreachable')
15:38:37 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55527
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;twitter.com:443.               IN      A socket: OSError(101, 'Network is unreachable')
15:38:37 E 无法解析主机：'twitter.com:443'，请检查是否输入正确！
15:38:37 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14817
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;twitter.com:443.               IN      A socket: OSError(101, 'Network is unreachable')
15:38:37 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14817
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;twitter.com:443.               IN      A socket: OSError(101, 'Network is unreachable')
15:38:37 E 无法解析主机：'twitter.com:443'，请检查是否输入正确！

**Comment by SeaHOH** [comment]
ok，get 到了，马上改！

**Comment by jzp820927** [comment]
改好了，说声，我再更新测试下。

**Comment by SeaHOH** [comment]
好了，你试一下 py3-path 分支。http 转发应该没问题了。

**Comment by jzp820927** [comment]
行，我马上试试

**Comment by jzp820927** [comment]
16:12:37 I 180.97.33.184 "FWD GET tbmsg.baidu.com:80 HTTP/1.1" - -
16:12:38 W 转发 'http://tbmsg.baidu.com/gmessage/get?mtype=1&_=1477987905858' 失败：ConnectionResetError(104, 'Connection reset by peer')

16:12:37 I 119.84.106.100 "FWD GET inews.gtimg.com:80 HTTP/1.1" - -
16:12:37 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28128
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;inews.gtimg.com:443.           IN      A socket: OSError(101, 'Network is unreachable')
16:12:37 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28128
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;inews.gtimg.com:443.           IN      A socket: OSError(101, 'Network is unreachable')
16:12:37 E 无法解析主机：'inews.gtimg.com:443'，请检查是否输入正确！

还有大量的下面这种报错：
----------------------------------------
16:12:39 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22423
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;img1.gtimg.com:443.            IN      A socket: OSError(101, 'Network is unreachable')
16:12:39 W handle dns query=;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22423
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;img1.gtimg.com:443.            IN      A socket: OSError(101, 'Network is unreachable')
----------------------------------------
Exception happened during processing of request from ('192.168.1.2', 49308)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/root/GotoX/local/ProxyServer.py", line 67, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/root/GotoX/local/ProxyHandler.py", line 128, in do_CONNECT
    self.do_count()
  File "/root/GotoX/local/ProxyHandler.py", line 113, in do_count
    do_x()
  File "/root/GotoX/local/ProxyHandler.py", line 460, in do_FORWARD
    remote = http_util.create_connection((host, port), self.fwd_timeout, cache_key=connection_cache_key)
  File "/root/GotoX/local/HTTPUtil.py", line 268, in create_connection
    addresses = [(x, port) for x in dns_resolve(host)]
TypeError: 'NoneType' object is not iterable

**Comment by SeaHOH** [comment]
好了，这回应该 https 也可以用了。

**Comment by jzp820927** [comment]
还是  py3-patch 分支 ？

**Comment by SeaHOH** [comment]
是 py3-patch

**Comment by hcym** [comment]
py3-patch 分支

不错不错，辛苦了

请问如何添加 ip 段 ?

**Comment by SeaHOH** [comment]
不支持 ip 段，只用 ip，放入 ``data.txt`` 每行一个。

**Comment by jzp820927** [comment]
17:59:19 I 14.18.245.236 "FWD GET weather.gtimg.cn:80 HTTP/1.1" - -
17:59:19 W 14.17.31.44 create_connection 'qos.report.qq.com' 返回 timeout('timed out',)，重试
17:59:19 I 180.97.33.184 "FWD GET tbmsg.baidu.com:80 HTTP/1.1" - -
17:59:19 W 14.17.52.161 create_connection 'qt.gtimg.cn' 返回 timeout('timed out',)，重试
17:59:20 W 14.18.245.212 create_connection 'js.data.auto.qq.com' 返回 timeout('timed out',)，重试
17:59:20 W 14.18.245.236 create_connection 'weather.gtimg.cn' 返回 timeout('timed out',)，重试
17:59:22 I 62.232.251.195 "FWD CONNECT portal.sinodun.com:443 HTTP/1.1" - -
17:59:22 I 180.97.33.184 "FWD GET tbmsg.baidu.com:80 HTTP/1.1" - -
17:59:30 I 14.17.41.183 "FWD GET trace.qq.com:80 HTTP/1.1" - -
17:59:38 I 104.244.42.195 "FWD CONNECT twitter.com:443 HTTP/1.1" - -
17:59:38 W 104.244.42.131 create_connection 'twitter.com' 返回 timeout('timed out',)，重试
17:59:40 I 14.17.57.169 "FWD CONNECT zyjc.sec.qq.com:443 HTTP/1.1" - -

还是有资源加载失败。

**Comment by SeaHOH** [comment]
ok，又调整了一下，已合并。

**Comment by jzp820927** [comment]
对了，啥时候，能把认证给加上？

**Comment by SeaHOH** [comment]
已经定位问题，今天就修。
这是为了让默认规则节约内存埋的坑。

**Comment by jzp820927** [comment]
刚刚 pull 到最新代码后，py3 启动又开始报错了。

python3 start.py
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from local import proxy
  File "/root/GotoX/local/proxy.py", line 75, in <module>
    from .ProxyServer import AutoProxy, GAEProxy
  File "/root/GotoX/local/ProxyServer.py", line 53, in <module>
    from .ProxyHandler import AutoProxyHandler, GAEProxyHandler
  File "/root/GotoX/local/ProxyHandler.py", line 16, in <module>
    from urllib import unquote
ImportError: cannot import name 'unquote'

**Comment by SeaHOH** [comment]
转到 GAE 代理可以正常用了，上面这条也修复完成。请更新。

**Comment by jzp820927** [comment]
行，那我试试，试完来汇报情况。

**Comment by samljh** [comment]
大神们辛苦了！
加油

**Comment by hcym** [comment]
jzp820927

Linux下正常吗

我的完全不能用，最早的一个版本还可以

xp只是看看股票不上网，就没试

最近几个都不行，老版也覆盖没了，晕啊

**Comment by SeaHOH** [comment]
可以贴错误啊，行行好，给点吧。
真要用老版，发布里面 3.3.0 版应该就行。

**Comment by jzp820927** [comment]
没问题，我最后一此回复 issues 已经说了。py2，py3，都测试过，都没问题。

**Comment by hcym** [comment]
噢

那就是我的问题喽

回头再试试看

错误信息无非是环境错误

不行再贴，老大不是Ubuntu，偷懒就没贴错误信息

**Comment by jzp820927** [comment]
我这儿也报错，上面回帖内容更新了。

**Comment by hcym** [comment]
唉

您这不是调戏俺嘛

差不多也是这消息

py2和3都不行

按说环境没有问题，两台机器一直保留一个老的3.0.4用py3运行，1604和1710都正常

估计还是平台兼容

不急，慢慢来吧

**Comment by SeaHOH** [comment]
嗯，这个把 ``data/ip_bad.txt`` 删除应该就好了。

**Comment by jzp820927** [comment]
我再检查下，配置文件

**Comment by jzp820927** [comment]
OK，搞定，正常运行，没有问题，py2，py3，都正常。
@hcym 你可以再试试。

**Comment by hcym** [comment]
报错


Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "/home/oem/wallproxy/GotoX-master/local/proxy.py", line 257, in main
    CertUtil.check_ca()
  File "/home/oem/wallproxy/GotoX-master/local/CertUtil.py", line 261, in check_ca
    sub_key = crypto.load_publickey(crypto.FILETYPE_PEM, content)
AttributeError: 'module' object has no attribute 'load_publickey'

**Comment by SeaHOH** [comment]
@hcym 
看不出问题，错的好没道理。
你是说前面的版本有正常运行，麻烦试一下 3.3.0 正常是否。

**Comment by jzp820927** [comment]
CertUtil.check_ca()，CertUtil.py，好像和证书有关？

**Comment by hcym** [comment]
系统ubuntu 16.04

GoAgent Version    : 3.2.3 (python/2.7.1 gevent/1.1.0 pyopenssl/0.15.1)
Listen Address     : 127.0.0.1:8087
GAE Mode           : https (SSLv23)


 3.3.0也不行了

python start.py
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from local import proxy
  File "/home/oem/wallproxy/GotoX-master/local/proxy.py", line 38, in <module>
    import dnslib
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named dnslib

**Comment by hcym** [comment]
删证书也不行

**Comment by jzp820927** [comment]
和你一样的系统，不过我是 ubuntu server 16.04
哦，你的 py 版本是 2.7.12 吧？上面漏了个 2？

**Comment by hcym** [comment]
pyopenssl 等等系统环境都没动，应该最新

放了

怕路径问题，所有目录都放

还是不行，以前就已1个版本可以，系统是1610

现在升到1704也不行了

**Comment by jzp820927** [comment]
应该和系统没啥关系，还是运行环境。
把你 pip list 命令结果贴出来看看。

**Comment by SeaHOH** [comment]
@hcym 
项目页有写啊，pyopenssl 至少 16.0，dnslib 也需要安装。
估计虽然系统升级了，但是 py 第三方库却降级或者是恢复默认版本了。

**Comment by SeaHOH** [comment]
@hcym 
项目页有写啊，pyopenssl 至少 16.0，dnslib 也需要安装。
估计虽然系统升级了，但是 py 第三方库却降级或者是恢复默认版本了。

**Comment by SeaHOH** [comment]
@hcym 
项目页有写啊，pyopenssl 至少 16.0，dnslib 也需要安装。
估计虽然系统升级了，但是 py 第三方库却降级或者是恢复默认版本了。

**Comment by jzp820927** [comment]
我也觉得是他运行环境的问题，特别是 openssl 和证书有关。

**Comment by hcym** [comment]
可能

没用python-pip安装运行环境

就是源里版本，那个正常运行的是1610，版本新

晚上再换个试试

**Comment by jzp820927** [comment]
那你的运行环境哪儿来的？gotox 是不带运行环境的，得自己装才行。

**Comment by hcym** [comment]
换了1704的机器 pyopenssl/16.2.0

还是不行


python start.py
==================================================================================
* GotoX  版 本 : 3.3.1 (python/2.7.12+ gevent/1.1.1 pyopenssl/16.2.0)
* GAE    APPID : 
* GAE 远程验证 : 已启用
*  监 听 地 址 : 自动代理 - 127.0.0.1:8087
*                GAE 代理 - 127.0.0.1:8086
*  链 接 模 式 : 远程 - TLSv1.2/openssl
*                本地 - SSLv23/gevent
*  链接 配置集 : ipv4
*  安 装 证 书 : http://gotox.net/ca
*  下 载 证 书 : http://gotox.net/ca 加任意字符
==================================================================================
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "/home/oem/wallproxy/GotoX-master/local/proxy.py", line 257, in main
    CertUtil.check_ca()
  File "/home/oem/wallproxy/GotoX-master/local/CertUtil.py", line 261, in check_ca
    sub_key = crypto.load_publickey(crypto.FILETYPE_PEM, content)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2547, in load_publickey
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

**Comment by SeaHOH** [comment]
看不咋懂，**cert** 文件夹是否存在这三个文件：
CA.crt
CAkey.pem
subkey.pem

**Comment by hcym** [comment]
有这三个文件

也是担心兼容，又删尽再用原版重新生成

**Comment by SeaHOH** [comment]
subkey.pem 里面是否有内容呢？

**Comment by SeaHOH** [comment]
subkey.pem 里面是否有内容呢？

**Comment by jzp820927** [comment]
确实有点诡异，同样的环境，我这边都可以正常运行。

**Comment by theratlesnake** [comment]
@SeaHOH  大哥，你这项目可以使用了吗？

**Comment by jzp820927** [comment]
一直可以用

**Comment by theratlesnake** [comment]
@jzp820927 是不是自动扫描ip的？

**Comment by jzp820927** [comment]
是

**Comment by SeaHOH** [comment]
还是需要自己提供 IP，不支持 IP 段。看项目介绍。

**Comment by theratlesnake** [comment]
@SeaHOH 老大，写个教程？

**Comment by jzp820927** [comment]
这么简单的东西，还需要教程。

**Comment by jzp820927** [comment]
这么简单的东西，还需要教程。

**Comment by SeaHOH** [comment]
大致信息项目首页都可以看到。
详细设置说明都在配置文件中，我觉得勉强写明白了。

@jzp820927 
这是连击？

**Comment by jzp820927** [comment]
不明觉厉，应该是，从来没遇到过，第一次遇到连击，兴奋ing

**Comment by SeaHOH** [comment]
GoProxy？我也xx了，大雾~~

**Comment by jzp820927** [comment]
github 直连没走代理。

**Comment by SeaHOH** [comment]
这样我就放心了。

**Comment by SeaHOH** [comment]
这样我就放心了。

**Comment by theratlesnake** [comment]
@SeaHOH  例如你写的【需事先提供由其它扫描工具取得一个较大的（上万也可）可用 GAE IP 列表以供筛选，放入“data/ip.txt”或“data/ipex.txt”（优先）中，格式为每行一个完整 IP】，就这一步我都不知道怎么搞了

**Comment by SeaHOH** [comment]
data 是文件夹，ip.txt 和 ipex.txt 是可用 GAE IP 列表，自己找 IP 放进去，每行一个。
建议你使用 XX-Net，我这个主要方便自定义代理规则。

**Comment by theratlesnake** [comment]
@SeaHOH 上万个ip手动加进去啊，吓人

**Comment by SeaHOH** [comment]
几百个也行，不是有那么多找 IP 的软件么。
