### ISSUE TITLE
GotoX-3.5.0-cp35-win_amd64的gotox后cmd界面闪下即消失

### ISSUE THREAD

**Issue by shpherd** [SeaHOH/GotoX#101]
系统W7 64，之前所使用XX-NET，运行GotoX-3.5.0-cp35-win_amd64的gotox后cmd界面闪下即消失，查看任务管理器没有gotox。GotoX-3.5.0-cp35-win32和GotoX-3.5.0-none-any同样，GotoX-gae-r6得uploader.bat同样现象。

**Comment by SeaHOH** [comment]
双击 vbs 文件运行。

另外，这个使用要求比 XX 高，需要懂点网络基础，不然用不顺手。
还有，不要指望 GAE 代理好用。上传问题见 #99 。

**Comment by SeaHOH** [comment]
突然想起，可能是在安装了不同于便携版版本的系统上运行便携版。
下个发布的便携版会尝试修复。
