### ISSUE TITLE
捣鼓直连时发现件荒唐事，CFIEC 的 DNS64 居然能翻墙

### ISSUE THREAD

**Issue by SeaHOH** [SeaHOH/GotoX#102]
http://www.cfiec.net/dns/s/?978.html

只对没有 IPv6 的域名有效，这个 NAT64 网关也比较特别，IP 没有一一对应。
简单试了下，速度还好。

搜了下相关内容，发现这个情况起码已经持续一年以上。
没搞明白他们的逻辑，难道会随机进行中间人攻击？

**Comment by gxggsrmyy** [comment]
@SeaHOH 能说说自定义 SNI 扩展的工作原理吗，最终是走gae吗？

**Comment by SeaHOH** [comment]
https://zh.wikipedia.org/wiki/服务器名称指示
https://zh.wikipedia.org/wiki/防火長城#针对SNI的连接
原理参考以上链接，大部分站点修改或禁用 SNI 就能直连。

**Comment by gxggsrmyy** [comment]
@SeaHOH 一知半解，能具体说说GotoX 是怎样利用SNI 扩展吗

**Comment by gxggsrmyy** [comment]
@SeaHOH 
#固定 GAE 服务使用的 iplist，当值不是空白时（不能直接填 IP），将不会进行 IP 检查筛选
#可填写存在的任意列表名称
iplist = google_sni

之前的版本gae 可以走 sni server ,现在的版本不行了。

**Comment by SeaHOH** [comment]
伪造 SNI 设置看 #103

使用 SNIProxy 参考配置注释
https://github.com/SeaHOH/GotoX/blob/bf6c4af0e2dcf541239380172c12af4c6f72fef3/config/Config.ini#L72-L79

**Comment by gxggsrmyy** [comment]
servername =   以前有默认值可以不填，现在一定要填写吗，ip.use 文件在哪？
#可以使用不包含点的任意字符串，或者是 *.appspot.com（* 不能是 www） 这句什么意思？

**Comment by SeaHOH** [comment]
> servername = 以前有默认值可以不填，现在一定要填写吗

是

> ip.use 文件在哪？

config 文件夹

> #可以使用不包含点的任意字符串，或者是 *.appspot.com（ * 不能是 www） 这句什么意思？

> #只有全部都是 *.appspot.com 域名才能保证 SNI IP 反代正确工作

就讲到这里了，不鼓励使用 SNIProxy。
GAE 还有几个 IP 可以用，自行搜索。
如果不看 U2B 的话，根本用不着 GAE，基本都能用伪造 SNI 直连。
像 twitter 这种完全封锁的还能通过 CFIEC 的 DNS64 翻。。。前提是它没有 IPv6。

**Comment by gxggsrmyy** [comment]
config 文件夹 里没有ip.use文件啊

**Comment by gxggsrmyy** [comment]
@SeaHOH  config 文件夹 里没有ip.use文件啊

**Comment by gxggsrmyy** [comment]
之前的版本，日志输出有显示  sni server 筛选的过程，现在的版本没有日志显示了

**Comment by gxggsrmyy** [comment]
@SeaHOH  之前的版本，日志输出有显示 sni server 筛选的过程，现在的版本没有日志显示了
