### ISSUE TITLE
自动规则 SNI 设置求助专帖

### ISSUE THREAD

**Issue by SeaHOH** [SeaHOH/GotoX#103]
https://github.com/SeaHOH/GotoX/wiki/如何使用伪造-SNI-的功能
这里的 SNI 并非 SNI代理，先看 wiki 说明，实在搞不来再跟帖求助。

GAE 代理无法使用 SNI 规则，请设置代理端口为自动代理端口，默认 8087。

规则如下：
1. 贴出你想要访问的网站域名

1. 解决结果（无论是否成功）会放在 2L
1. 有了结果后，**请删除你的跟帖**
1. 会定期选择部分的加入默认规则

**Comment by SeaHOH** [comment]
占

**Comment by gxggsrmyy** [comment]
www.instagram.com  规则中写有，但也打不开啊

**Comment by gxggsrmyy** [comment]
@SeaHOH  www.pixiv.net 规则中写有，但也访问不了啊

**Comment by gxggsrmyy** [comment]
@SeaHOH 实在看不明白，能否就以[www.pixiv.net] 为例说明一下

**Comment by gxggsrmyy** [comment]
@SeaHOH 伪造 SNI 直连 ipv4 环境能用吗？

**Comment by SeaHOH** [comment]
注意看 wiki 说明，使用 https 连接，确保无 DNS 污染。

**Comment by gxggsrmyy** [comment]
DNS-over-HTTPS早就设为优先了，工作原理基本懂了，但还是不行 @SeaHOH

**Comment by SeaHOH** [comment]
> DNS-over-HTTPS早就设为优先了，工作原理基本懂了，但还是不行

你确定？注意访问时的日志，前面的 IP 是否是下列之一：
210.140.131.222
210.140.131.224
210.140.131.218

**Comment by wz7465** [comment]
不管国内国外，现在是通通被拦截状态
![default](https://user-images.githubusercontent.com/7801728/52909112-6a970280-32bd-11e9-84d2-94df40459db2.png)

**Comment by wz7465** [comment]
action = 1 不知何时改成1了，失策

**Comment by SeaHOH** [comment]
>     3\. 有了结果后，**请删除你的跟帖**

@wz7465

**Comment by wz7465** [comment]
无关的删了，其实还是没有结果，www.google.com改了sni域名还是无法访问
![default](https://user-images.githubusercontent.com/7801728/52910610-e3ee1f80-32d4-11e9-9cfd-01913fb58c54.png)

**Comment by fredericky123** [comment]
感谢海大的热心开发，不过使用起来还是有些无从下手，从3.5.0面世以来的情形可能表明小白上手并不是那么简单，不知有无默认好的sni设置可以访问谷歌系，这样就满足了基本的搜索需求，小白们可以照葫芦画瓢

**Comment by SeaHOH** [comment]
默认规则支持一些网站，包括谷歌大部分服务。

**Comment by fredericky123** [comment]
啊是么 我下载下来解压后直接默认运行并不能访问谷歌 是哪里的设置还需要改么

**Comment by SeaHOH** [comment]
> 啊是么 我下载下来解压后直接默认运行并不能访问谷歌 是哪里的设置还需要改么

两种情况：
1. 首次运行需等待筛选到可用 IP 。
1. 你没有 IPv6 网络，此时应添加一些 IPv4 IP 到 ip.txt 文件中。

**Comment by fredericky123** [comment]
那就是原因2了 请问通过什么方式可以扫描到支持sni的有效ipv4 ip呢？用哪个软件

**Comment by SeaHOH** [comment]
> 请问通过什么方式可以扫描到支持sni的有效ipv4 ip呢？

这里的 SNI 不是 SNI 代理，而是 TLS 连接协议的一个选项。

> 用gscan可以扫，主要找不到ip库

如果你需要 IPv4 IP，可以查看 ip.txt 的旧版本，也可以扫描 XX-Net 的 IP 库文件。

>     3. 有了结果后，请删除你的跟帖

**Comment by fredericky123** [comment]
如何说来只是需要将gscan改为sni模式，拼命扫ip即可，已经在扫了。不过无论3.5.0还是3.5.1均会出现错误，也是无奈
3.5.0错误如下：
20:45:13 W 导入证书时发生错误：OSError('exception: access violation reading 0x0000000047FDAD90',)
20:45:13 W 导入证书时发生错误：OSError('exception: access violation reading 0x0000000047FDAE60',)
20:45:13 W install root certificate failed, Please run as administrator/root/sudo
20:45:17 W [picker gae] 当前 gae IP 数量为 0
20:45:18 E [picker gae] pick_ip_worker 发生错误：'NoneType' object has no attribute 'close'
Traceback (most recent call last):
  File "D:\Software\Download\GotoX-3.5.0-cp35-win_amd64\local\GIPManager.py", line 804, in pick_ip_worker
    domain, ssl_time, type = self.get_ip_info(ip)
  File "D:\Software\Download\GotoX-3.5.0-cp35-win_amd64\local\GIPManager.py", line 783, in get_ip_info
    sock.close()
AttributeError: 'NoneType' object has no attribute 'close'

3.5.1错误如下：
Traceback (most recent call last):
  File "D:\Software\Download\GotoX-3.5.1-cp35-win_amd64\start.py", line 13, in <module>
    from local import proxy
  File "D:\Software\Download\GotoX-3.5.1-cp35-win_amd64\local\proxy.py", line 53, in <module>
    from .GlobalConfig import GC
  File "D:\Software\Download\GotoX-3.5.1-cp35-win_amd64\local\GlobalConfig.py", line 37, in <module>
    class GC:
  File "D:\Software\Download\GotoX-3.5.1-cp35-win_amd64\local\GlobalConfig.py", line 76, in GC
    GAE_FETCHMAX = CONFIG.getint('gae', 'fetchmax', fallback=2)
  File "configparser.py", line 816, in getint
  File "configparser.py", line 806, in _get_conv
  File "configparser.py", line 800, in _get
ValueError: invalid literal for int() with base 10: '

**Comment by SeaHOH** [comment]
已重新发布 3.5.1

**Comment by SeaHOH** [comment]
> 这样说来只是需要将gscan改为sni模式

并不是。

> 这里的 SNI 不是 SNI 代理，而是 TLS 连接协议的一个选项。

**Comment by fredericky123** [comment]
好吧 这样的话我还是不确定sni功能如何用了 等以后大家都用起来再用吧 新的3.5.1还是有证书错误

21:55:04 W 导入证书时发生错误：OSError('exception: access violation reading 0x00000000438921B0',)
21:55:04 W 导入证书时发生错误：OSError('exception: access violation reading 0x0000000043892830',)
21:55:04 W install root certificate failed, Please run as administrator/root/sudo
21:55:05 W [picker gae] 当前 gae IP 数量为 0
21:55:07 W [picker gws] 当前 gws IP 数量为 0

**Comment by SeaHOH** [comment]
> 新的3.5.1还是有证书错误

忽略然后手动操作

**Comment by fredericky123** [comment]
这样貌似可以了，只是找不到可用ip
22:04:23 W L4:1665-> do_DIRECT "GET https://scholar.google.com/" 没有正确响应，重试。
22:04:23 W L4:1665-> do_DIRECT "GET https://scholar.google.com/" 失败，返回 404
22:04:25 W L4:1666-> do_DIRECT "GET https://www.google.com/" 没有正确响应，重试。
22:04:25 W L4:1666-> do_DIRECT "GET https://www.google.com/" 失败，返回 404

**Comment by wz7465** [comment]
22:09:33 I 'https://www.google.com/ncr' 返回包含重定向 'https://www.google.com/'
22:09:33 I L4:14455->[2800:370:10:17::e] "DIRECT GET https://www.google.com/ncr HTTP/1.1" 302 220
22:09:35 I L4:14455->[2800:370:10:17::e] "DIRECT GET https://www.google.com/ HTTP/1.1" 200 65819
有ip也不行，其实不是sni的关系，而是这边的网络环境已经能识别阻断了sni欺骗了

**Comment by SeaHOH** [comment]
> 22:09:35 I L4:14455->[2800:370:10:17::e] "DIRECT GET https://www.google.com/ HTTP/1.1" 200 65819

成功访问了，难道你浏览器没有收到数据？

**Comment by wz7465** [comment]
没有，响应头空，另外默认的几个，像zh.wikipedia.org www.pixiv.net都访问不了，只有ipv4老版本正常，应该是墙对最后发布版本针对性干扰了

**Comment by SeaHOH** [comment]
还是上面那个 bug，不是针对的干扰。

**Comment by wz7465** [comment]
用chrome试了下，报错
![111](https://user-images.githubusercontent.com/7801728/52960183-30b82000-33d3-11e9-9c17-15c105a62af2.png)

**Comment by wz7465** [comment]
谷歌浏览器，老版Gotox，把可用的Ipv6导入，直连访问谷歌，第一加载页面成功，刷新404，拦截效率很高，改用sniip，则健壮的多

**Comment by fredericky123** [comment]
@wz7465 求问sni如何使用的，能否个配置好的config和ip

**Comment by wz7465** [comment]
电脑关了，论坛可以搜sni，不行明天可以简单讲下，Ip就不提供了，属稀缺资源，1，2个也不好使，十个左右才行，真有心论坛也能搜到

**Comment by fredericky123** [comment]
@wz7465 OK,有空告诉如何配置和如何扫描也可以，多谢！

**Comment by SeaHOH** [comment]
>     3. 有了结果后，请删除你的跟帖

**Comment by wz7465** [comment]
@fredericky123 
配置[gae]下
iplist = sni_all
servername = XXX.appspot.com XXX指随意字符
然后[iplist]下 添加一条
sni_all = ip|ip|ip ip是你找到的
工具用gscan，项目讨论区搜关键词sni 以前有公布过ip

**Comment by wz7465** [comment]
有些想法，不知新版本中能否增加这些功能
priority = system|overhttps|remote中能不能引入 priority = host|system这样，优先读取主机host文件，方便dns解析使用固定ip，便于测试
[filter]规则中，action = 3 能不能增加一个action = 5 http 链接默认动作［直连］会在无法连接时尝试 外部代理（比如ss1080接口）

**Comment by wz7465** [comment]
举个实例分析一下
首先无污染解析到ip地址
199.59.148.140 zh.wikipedia.org
198.35.26.96 en.wikipedia.org
host大法 浏览器无代理情况访问，结果很明显，en顺利访问，zh不能访问
zh.wikipedia.org域名被墙，无需多说，现在证明199.59.148.140被墙，
199.59.148.140 en.wikipedia.org 还是不能访问，证明ip被墙
我这边的环境属于ip 域名双封锁，猜测你那边的环境是域名单封锁
所以用199.59.148.140+伪造sni名en.wikipedia.org（实质是zh.wikipedia.org）可以访问
你可以用host法 199.59.148.140 en.wikipedia.org 验证一下，如果能访问，那应该是单封锁

**Comment by gxggsrmyy** [comment]
@SeaHOH 内置的谷歌 DNS-over-HTTPS 服务默认不能使用呢，要加什么配置才能用？

**Comment by lshilshi** [comment]
wiki里面的SNI相关和配置文件 的说明还是 看不明白
楼主能拿个18禁whv做实例来教学一下吗？

**Comment by SeaHOH** [comment]
>     1. 贴出你想要访问的网站域名

**Comment by lshilshi** [comment]
就拿有名的1024来说吧
www.t66y.com

**Comment by SeaHOH** [comment]
> 就拿有名的1024来说吧
> [www.t66y.com](http://www.t66y.com)

这种根本就没封 SNI，你完全没看过 wiki 说明吧。

**Comment by lshilshi** [comment]
我知道，但是最近GAE基本报废
你又提到SNI才是可行的FQ方法
所以我想是不是可以用SNI方式来访问这些网站？

**Comment by SeaHOH** [comment]
嗯，建议你仔细看一遍 wiki 说明。
当然，如果嫌麻烦可以使用其它工具，fg 之类。

2 楼已经给出结果，只需要去 DNS 污染就行。

>     3\. 有了结果后，**请删除你的跟帖**

**Comment by fredericky123** [comment]
可不可教学一下，从down下3.5.1步骤开始，如何实现google.com和scholar.google.com的访问，至今没搞懂。
将此例写在wiki中，大家不言自明。

**Comment by SeaHOH** [comment]
> 可不可教学一下，从down下3.5.1步骤开始，如何实现google.com和scholar.google.com的访问，至今没搞懂。
> 将此例写在wiki中，大家不言自明。

真心不想写，因为最多三步：
下载 -> 增加旧 IPv4 到 ip.txt -> 运行并使用代理

**Comment by fredericky123** [comment]
唉 可能我就是找不到可用ip

**Comment by SeaHOH** [comment]
都讲了是旧 IP，翻以前的 ip.txt 口牙！

>     3\. 有了结果后，**请删除你的跟帖**

**Comment by fredericky123** [comment]
唉~

**Comment by wz7465** [comment]
@fredericky123 
阅后即焚
Config.ini和ActionFilter.ini中修改
重点，一定要优先解决好dns污染，那些114和谷歌的8.8.8.8的没用
还有版本的问题，新版本在我这里有些莫名问题，是用老版做演示
[dns]
servers = 127.0.0.1   #指向本地加密dns，这是我自建的，gotox不带的，如果你没有，就把remote替换成overhttps，但不太好使
priority = remote

[0-fakecert] #建议伪造证书排第一不要改动，配合需要匹配路径的加密链接（下面添加）
t66y.com = 66.t66y.cn      # 66.t66y.cn可以尝试改其他，但要保留t66y字符
[30-redirect] #重定向
http://t66y.com = @^http >> https

**Comment by wz7465** [comment]
@fredericky123 1024示范邮箱里收到么？我删的较快，没收到可以重新发一次

**Comment by gxggsrmyy** [comment]
GAE 绑定自定义域名应怎么设置，出错提示 
Traceback (most recent call last):
  File "E:\Dropbox\GotoX\GotoX-master\GotoX-master\local\ProxyHandler.py", line 689, in do_GAE
    response = gae_urlfetch(self.command, self.url, request_headers, payload, appid)
  File "E:\Dropbox\GotoX\GotoX-master\GotoX-master\local\GAEFetch.py", line 208, in gae_urlfetch
    _response = _gae_urlfetch(request_params, payload, request_headers, getfast, method, realurl)
  File "E:\Dropbox\GotoX\GotoX-master\GotoX-master\local\GAEFetch.py", line 215, in _gae_urlfetch
    _, (iporname, _) = get_connect_action(request_params.ssl, request_params.host)
TypeError: 'NoneType' object is not iterable

**Comment by gxggsrmyy** [comment]
@SeaHOH GAE 绑定自定义域名应怎么设置

**Comment by SeaHOH** [comment]
@gxggsrmyy 请删除你的跟帖，新开 issue 提问。

**Comment by kxmp** [comment]
ping.eu打不开
我直连发现都能开. 奇怪了 应该不是sni封锁吧!!!!

**Comment by SeaHOH** [comment]
不要使用全局 GAE 代理，需要通过 8087 端口来使用 SNI 规则。

**Comment by kxmp** [comment]
那我有时候想用全局代理访问网站然后遇到这个情况怎么办哇!!!

**Comment by SeaHOH** [comment]
> 那我有时候想用全局代理访问网站然后遇到这个情况怎么办哇!!!

请使用代理切换工具或者手动设置。
浏览器推荐使用代理设置扩展，PAC 脚本可以用于操作系统。

> 那这个问题不属于sni是不是!!? 因为我用的全局代理

ping.eu 不是，imgur 是。

问题解决后请删除跟帖。

**Comment by kxmp** [comment]
但是imgur我也走的全局代理啊 所以这个应该是全局代理的问题吧!!!

**Comment by Demon-crazy** [comment]
@SeaHOH 你好，我按照教程查询www.quora.com和cn.nytimes.com的cname，设置如下：
www.quora.com = same@quora.map.fastly.net
cn.nytimes.com = same@d1emgxxou2di91.cloudfront.net
但访问依然提示无法验证证书。请问应当如何解决？
（令，使用Accesser则可以访问quora。）

**Comment by SeaHOH** [comment]
这个功能需要最新的主分支。

**Comment by Demon-crazy** [comment]
> 
> 
> 这个功能需要最新的主分支。

噢，了解了。谢谢。

**Comment by lshilshi** [comment]
继续求助
wiki看过好几遍了，还是看不明白，请原谅我这小白
一直私心以为应该以访问某自动规则下不能访问的某站（加入某成人站，举例啊举例：））
来告诉大家如何去处理以突破（写个专门的转发规则就好，还是需要SNI，以及其它……）
这样更具体，更有教学性啊

> 11:38:10 W 31.13.84.8 _create_connection 'archive.is' 返回 timeout('timed out',)
，重试
11:38:12 T [picker gws] 0 测试连接（超时：1000 ms）172.217.194.144，231 ms
11:38:18 W L4:55457->31.13.84.8 转发到 'archive.is' 失败：timeout('timed out',)
11:38:26 W 31.13.84.8 _create_connection 'archive.is' 返回 timeout('timed out',)
，重试
11:38:32 W [picker gae] 当前 gae IP 数量为 0
11:38:34 W L4:55457->31.13.84.8 转发到 'archive.is' 失败：timeout('timed out',)
11:38:34 W L4:55457-> do_FORWARD 连接远程主机 ('archive.is', 443) 失败，尝试使用
 "FAKECERT & GAE" 规则。

能访问google了（应该算F墙成功了？），但这个archive.is就是访问不了
看上面的各种规则还是救不了这个被Q的archive.is

请以此站演示，如何找出archive.is是dns被污染，还是ip直接被封还是其它原因
如何处理（写何种规则以帮助突破）
如果涉及SNI，请示例如何构造合适的SNI

**Comment by SeaHOH** [comment]
主配置的 DNS 设置里面有多种解析方式，其中可以调整为 DoH 优先，这个必定是无污染的。
你选择的 archive.is 不是一个合适的演示目标，因为排除污染后直接就能连接，它并未被 SNI 过滤。

另，wiki 中讲的是一般方法，按照顺序重复几次，一般都能确定合适的 SNI。我等会儿再修改一下，增加使用前提条件，也就是先排除 DNS 污染和 IP 封锁。

**Comment by SeaHOH** [comment]
@lshilshi 如问题已解决，请删除跟帖。

**Comment by Sak94664** [comment]
https://nyaa.si
thx :)

**Comment by SeaHOH** [comment]
> https://nyaa.si

证书有问题，是自签的，暂时没有忽略特定错误的相关功能。

**Comment by Sak94664** [comment]
这个我设置了之后报522证书错误并且无法访问那个网站，但在约11小时之前我成功过。(通过设置SNI)

**Comment by SeaHOH** [comment]
>issuer: /C=EU/ST=*/O=ddos-guard

又仔细看了一下，好像哪里不对，这是不是 ddos 保护？还是说封大陆 IP？

**Comment by SeaHOH** [comment]
steemit 和 medium 都正常，不发送就行。

**Comment by Sak94664** [comment]
我在ActionFilter.ini内的fakecert一栏添加了
`steemit.com = @none`
看日志它报了timeout?
本地设置了dnscrypt-proxy

**Comment by SeaHOH** [comment]
如果是 `_request **** timed out`，你试试增大 link/timeout  数值。
如果是 `create_ssl_connection **** timed out`，只能改代码了，默认是三秒，应该足够大。

**Comment by Sak94664** [comment]
`104.24.118.129 _create_ssl_connection 'steemit.com' 返回 Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])`
  
然后报了404

**Comment by SeaHOH** [comment]
> `104.24.118.129 _create_ssl_connection 'steemit.com' 返回 Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])`
> 
> 然后报了404

你是对的，我搞错了，之前 steemit 设置了代理。

**Comment by Sak94664** [comment]
还有，就是有些网站有时连接不稳定，可否强制设定通过SNI?
有时它会自己去走goagent，但是我是把它当作去除sni 工具来用的。

**Comment by SeaHOH** [comment]
> 会自动变成走goagent，

GAE 临时规则有个白名单 link/tempwhitelist

**Comment by Sak94664** [comment]
谢谢帮助 :)
现在可以删除评论吗？

**Comment by SeaHOH** [comment]
> 之前的nyaa.si在cn去除了sni也上不了，但挂了proxy之后可以上

看证书信息似乎是被人攻击了，然后自动保护？

> 现在可以删除评论吗？

可以
