### ISSUE TITLE
GotoX-gae-r6上传输入验证码后没有反映

### ISSUE THREAD

**Issue by miketwes** [SeaHOH/GotoX#104]
log输出如图:

![2019-02-19_492x536](https://user-images.githubusercontent.com/6849681/53014400-569cfd80-3483-11e9-87c9-5744b95a8753.png)

**Comment by miketwes** [comment]
另外用XX-Net正常登录的一个网站用GotoX无法正常登录,都是重定向到首页,一个显示登录,一个是未登录的状态

**Comment by SeaHOH** [comment]
什么验证码？在弹出窗口点击授权就好了，如果没有弹出就自行复制链接到浏览器。

> 另外用XX-Net正常登录的一个网站用GotoX无法正常登录,都是重定向到首页,一个显示登录,一个是未登录的状态

网址。

**Comment by miketwes** [comment]
如图:
![2019-02-19_340x161](https://user-images.githubusercontent.com/6849681/53022381-067b6680-3496-11e9-80c3-6d471fca22ea.png)

到这里长时间没有响应,按Ctrl + c后,提示上传失败

网址有点敏感,就不提供了,请不要介意

**Comment by SeaHOH** [comment]
你开了二步验证？我没用过，你可以试试上传时关掉它。

**Comment by miketwes** [comment]
> 你开了二步验证？我没用过，你可以试试上传时关掉它。

没有开二步验证

**Comment by SeaHOH** [comment]
没有遇到过这种验证码，都是这样的：
```
===============================================================
 GoProxy GAE 服务端部署程序，开始上传 gae 应用文件夹。
===============================================================

输入多个 AppID 时需要使用字符“|”隔开。
特别提醒：AppID 请勿包含 ID/Email 等个人信息!
请输入 AppID：xyz

如果您不想设定使用密码，请直接按回车键。
请输入 App 使用密码：

开始上传……
12:54 PM Application: xyz
12:54 PM Host: appengine.google.com
12:54 PM Rolling back the update.
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2
F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=htt
p%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=550516889912.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver
```

**Comment by miketwes** [comment]
用Google Cloud部署完成:

![2019-02-20_575x129](https://user-images.githubusercontent.com/6849681/53083133-4c3d3b00-3539-11e9-97bc-d5484bccb7b6.png)

![2019-02-20_180x219](https://user-images.githubusercontent.com/6849681/53083197-5fe8a180-3539-11e9-938f-b5d98177b37c.png)

**Comment by SeaHOH** [comment]
直接通过调试部署？不是 Google Cloud Shell 吗？

**Comment by miketwes** [comment]
> Google Cloud Shell

通过下载的google-cloud-sdk部署

**Comment by miketwes** [comment]
> 另外用XX-Net正常登录的一个网站用GotoX无法正常登录,都是重定向到首页,一个显示登录,一个是未登录的状态

在清理系统后这个网站可正常登录
另有
https://stackoverflow.com/
https://unix.stackexchange.com/
等系列的网址无法打开

**Comment by SeaHOH** [comment]
> 另有
> https://stackoverflow.com/
> https://unix.stackexchange.com/
> 等系列的网址无法打开

直连或转发就行，不用走代理。
如果没有安装反 DNS 污染工具，可以提高内置 DoH 的优先级。

**Comment by miketwes** [comment]
> > 另有
> > https://stackoverflow.com/
> > https://unix.stackexchange.com/
> > 等系列的网址无法打开
> 
> 直连或转发就行，不用走代理。
> 如果没有安装反 DNS 污染工具，可以提高内置 DoH 的优先级。

重新git了一下(原先的是zip版), 重新安装了ca, all's ok
