### ISSUE TITLE
导入证书时发生错误

### ISSUE THREAD

**Issue by 722tzz** [SeaHOH/GotoX#109]
版本：GotoX-3.5.1-cp35-win_amd64
系统：win10
在有管理员权限的windows账户下，右键“以管理员身份运行”GotoX“报如下错误：

```
18:32:02 W 导入证书时发生错误：OSError('exception: access violation reading 0xFFFFFFFFCFB57F10',)
18:32:02 W 导入证书时发生错误：OSError('exception: access violation reading 0xFFFFFFFFCFB57140',)
18:32:02 W install root certificate failed, Please run as administrator/root/sudo
```
#84 中提到的 [http://gotox.go](url) 无法访问

**Comment by SeaHOH** [comment]
> #84 中提到的 [http://gotox.go](url) 无法访问

需要通过本代理才能访问。
请忽略自动检测导入证书错误并停止这个设置，没有修复的计划，手动操作就行。

**Comment by 722tzz** [comment]
导入证书后还是报错。。。
`22:48:29 W L4:61640-> host=clients1.google.com，客户端 https 验证失败！可能未安装 GotoX CA 证书。`

**Comment by 722tzz** [comment]
导入为“受信任的根证书颁发机构”后解决

**Comment by AeneasZhu** [comment]
> 导入为“受信任的根证书颁发机构”后解决

怎么弄呀？

**Comment by SeaHOH** [comment]
使用前请先阅读 README
