### ISSUE TITLE
运行报错：UnicodeDecodeError

### ISSUE THREAD

**Issue by cixi666** [SeaHOH/GotoX#11]
GotoX  版 本 : 3.3.4 (python/3.5.2 gevent/1.2.1 pyOpenSSL/16.2.0)
 GAE 远程验证 : 已启用

  监 听 地 址 : 自动代理 - 127.0.0.1:8087
                GAE 代理 - 127.0.0.1:8086

  代 理 认 证 : 无需认证

  调 试 信 息 : INFO

  链 接 模 式 : 远程 - TLSv1.2 / gevent + OpenSSL
                本地 - SSLv23 / gevent

  网 络 配 置 : ipv4

  安 装 证 书 : 设置代理后访问 http://gotox.go/
===============================================================================
==
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 274, in main
    pre_start()
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 223, in pre_start
    tasklist = dict((x.name.lower(), x) for x in get_process_list())
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 118, in get_proces
_list
    path = modname.value.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 3: invalid
continuation byte

**Comment by SeaHOH** [comment]
我还没搞清楚怎么复现。
你先把 `checkprocess` 选项设为 **0**，跳过检查。

**Comment by SeaHOH** [comment]
可能是系统不一样引起的，我的是 Win7，你的是什么系统？

你能不能把下面这句加在出错的 118 行前面，看看有什么结果？`checkprocess` 要启用。

```python
print('结果=', repr(modname.value))
path = modname.value.decode()
```

**Comment by cixi666** [comment]
win8.1 x64
好了，把 checkprocess 选项设为 0 就可以运行了。

**Comment by cixi666** [comment]
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from local import proxy
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 118
    print('结果=', repr(modname.value))
                                     ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by SeaHOH** [comment]
你好像把制表符复制进去了。

这个 print 语句是与后一句 path 相同缩进位置的，你把 print 前的空白全部删除，再用空格加回去，应该就能正常运行这一句。

麻烦你重试一下，谢谢。

**Comment by cixi666** [comment]
不懂，你直接改好这个文件proxy.py，我下载复制到目录里试方式。

**Comment by cixi666** [comment]
================================================================================
==
 GotoX  版 本 : 3.3.3 (python/3.5.2 gevent/1.2.1 pyOpenSSL/16.2.0)

 GAE    APPID : freevpn263|freevpn2632|freevpn2633|freevpn2634|freevpn2635|freev
pn2636|freevpn2637|freevpn2638|freevpn2639|freevpn26310|freevpn26311|freevpn2631
2|freevpn26313|freevpn26314|freevpn26315|freevpn26316|freevpn26317|freevpn26318|
freevpn26319|freevpn26320|freevpn26321|freevpn26322|freevpn26323|freevpn26324|fr
eevpn26325|ffmpegvpn01|ffmpegvpn02|ffmpegvpn03|ffmpegvpn04|ffmpegvpn05|ffmpegvpn
06|ffmpegvpn07|ffmpegvpn08|ffmpegvpn09|ffmpegvpn10|ffmpegvpn11|ffmpegvpn12|ffmpe
gvpn13|ffmpegvpn14|ffmpegvpn15|ffmpegvpn16|ffmpegvpn17|ffmpegvpn18|ffmpegvpn19|f
fmpegvpn20|ffmpegvpn21|ffmpegvpn22|ffmpegvpn23|ffmpegvpn24|ffmpegvpn25

 GAE 远程验证 : 已启用

  监 听 地 址 : 自动代理 - 127.0.0.1:8087
                GAE 代理 - 127.0.0.1:8086

  代 理 认 证 : 无需认证

  调 试 信 息 : INFO

  链 接 模 式 : 远程 - TLSv1.2 / gevent + OpenSSL
                本地 - SSLv23 / gevent

  网 络 配 置 : ipv4

  安 装 证 书 : 设置代理后访问 http://gotox.go/
================================================================================
==
结果= b'C:\\Windows\\System32\\taskhostex.exe'
结果= b'C:\\Windows\\System32\\InputMethod\\CHS\\ChsIME.exe'
结果= b'C:\\Windows\\explorer.exe'
结果= b'C:\\Program Files (x86)\\NVIDIA Corporation\\Update Core\\NvBackend.exe'

结果= b'C:\\Windows\\System32\\SkyDrive.exe'
结果= b'C:\\Windows\\System32\\SettingSyncHost.exe'
结果= b'J:\\Program Files\\palemoon\\Bin\\Palemoon\\palemoon.exe'
结果= b'J:\\Program Files\\palemoon\\Bin\\Palemoon\\plugin-container.exe'
结果= b'C:\\Program Files\\WindowsApps\\41095344.PPStream_3.2.2.4_x64__z6zadccf1
nq96\\iQiyiVideo.Windows.exe'
结果= b'C:\\Windows\\System32\\RuntimeBroker.exe'
结果= b'J:\\Program Files\\palemoon\\Bin\\Palemoon\\plugin-container.exe'
结果= b'K:\\\xd7\xc0\xc3\xe6\\\xb7\xad\xc7\xbd\\notepad.6.9.2\\notepad++.exe'
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 276, in main
    pre_start()
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 225, in pre_start
    tasklist = dict((x.name.lower(), x) for x in get_process_list())
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 119, in get_process
_list
    path = modname.value.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 3: invalid
continuation byte

**Comment by cixi666** [comment]
==
结果= b'C:\\Windows\\System32\\taskhostex.exe'
结果= b'C:\\Windows\\System32\\InputMethod\\CHS\\ChsIME.exe'
结果= b'C:\\Windows\\explorer.exe'
结果= b'C:\\Program Files (x86)\\NVIDIA Corporation\\Update Core\\NvBackend.exe'

结果= b'C:\\Windows\\System32\\SkyDrive.exe'
结果= b'C:\\Windows\\System32\\SettingSyncHost.exe'
结果= b'J:\\Program Files\\palemoon\\Bin\\Palemoon\\palemoon.exe'
结果= b'J:\\Program Files\\palemoon\\Bin\\Palemoon\\plugin-container.exe'
结果= b'C:\\Program Files\\WindowsApps\\41095344.PPStream_3.2.2.4_x64__z6zadccf1
nq96\\iQiyiVideo.Windows.exe'
结果= b'C:\\Windows\\System32\\RuntimeBroker.exe'
结果= b'J:\\Program Files\\palemoon\\Bin\\Palemoon\\plugin-container.exe'
结果= b'K:\\\xd7\xc0\xc3\xe6\\\xb7\xad\xc7\xbd\\notepad.6.9.2\\notepad++.exe'
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 276, in main
    pre_start()
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 225, in pre_start
    tasklist = dict((x.name.lower(), x) for x in get_process_list())
  File "C:\Users\ku888_000\Desktop\GAE\local\proxy.py", line 119, in get_process
_list
    path = modname.value.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 3: invalid
continuation byte

**Comment by SeaHOH** [comment]
看到了，等我搞定就修复，谢谢。

**Comment by SeaHOH** [comment]
@cixi666 
已经修复。 [`74e5d5a`](https://github.com/SeaHOH/GotoX/commit/74e5d5a1f7a3f65507d1ea6f9590cbd8d785f337)
今晚网络质量太差了，放弃 GitHub 客户端同步，改用上传。

**Comment by jzp820927** [comment]
改用上传？意思是直接在 github web 网页上上传更新代码？

**Comment by SeaHOH** [comment]
对，就是网页上传。

顺便吐个槽：我太小看 git 了，知道它复杂，但没想到会这么复杂！

昨天传完修改后，还是想不过，又去找设置 git 代理的方法，以前找过觉得麻烦，反正能用就行。
好多都是讲 Linux 的，也不知道 Win 能用不，就在 Shell 打了`git help config`，结果跳出一本地网页。
一看吓一跳，无它，就是太长了，怪不得要用网页。
还没完，这应该只是设置部分，还有用法，进入文件夹一看，我 X，11M！整整 11M 的网页文件！算纯文本也有 7、8M 吧，我之前用过有 Linux 基因的 MPV 播放器说明文档才 500+k，已经觉得很复杂了。不就一版本控制工具么，要不要这么凶残，太可怕鸟！果然还是我大 Windows 够傻瓜。

然后还是老老实实去刚弹出来的网页找怎么设置代理，结果发现网上也是不靠谱的多，只需一句就行：
`git config --global http.proxy http://127.0.0.1:8087`
下面这句没必要，根本就没这设置，即使有地址格式也应该仍然是 `http://127.0.0.1:8087`：
`git config --global https.proxy https://127.0.0.1:8087`

**Comment by jzp820927** [comment]
恩，git 走代理没问题，我以前测试过。
