### ISSUE TITLE
GotoX-gae-r6-c1 上传失败

### ISSUE THREAD

**Issue by 722tzz** [SeaHOH/GotoX#110]
能够访问 https://accounts.google.com/signin/oauth/consent?authuser 页面，并完成认证：

```
The authentication flow has completed.
```
可是最终仍旧上传失败
```
上传 (****) 失败 1 次，重试……
```

**Comment by SeaHOH** [comment]
默认规则是：
```ini
appengine.google.com = google_gws
```
你可以改成这样试试：
```ini
appengine.google.com = google_gae
```
两个我都能正常部署。

**Comment by SeaHOH** [comment]
另外看下目录中是否有正常创建 `.appcfg_oauth2_tokens` 授权文件。

**Comment by 722tzz** [comment]
改了也不行，
.appcfg_oauth2_tokens 授权文件是在什么地方？软件的根目录？文件名就是.appcfg_oauth2_tokens？

另外这个是用IPV6直连效果好还是用Teredo隧道效果好？

**Comment by SeaHOH** [comment]
> .appcfg_oauth2_tokens 授权文件是在什么地方？软件的根目录？文件名就是.appcfg_oauth2_tokens？

部署脚本 (uploader.py) 所在目录，如果没有，说明没获取到授权。

> 另外这个是用IPV6直连效果好还是用Teredo隧道效果好？

不试一下怎么知道呢，也许根本就不能用。

**Comment by 722tzz** [comment]
没有这个文件，看来是没有得到授权了。
发现了一个现象默认的代理是127.0.0.1:8086
由于我之前用的是XXnet，使用的代理是127.0.0.1:8087
用8087的话是能够弹出授权页面并走到`The authentication flow has completed`.这步，但是上传失败，无法得到授权；
如果用8086则浏览器弹出页面会报`AppID 配置为空，无法使用 GAE 代理`

**Comment by 722tzz** [comment]
没有这个文件，看来是没有得到授权了。
发现了一个现象默认的代理是127.0.0.1:8086
由于我之前用的是XXnet，使用的代理是127.0.0.1:8087
用8087的话是能够弹出授权页面并走到`The authentication flow has completed`.这步，但是上传失败，无法得到授权；
如果用8086则浏览器弹出页面会报`AppID 配置为空，无法使用 GAE 代理`

**Comment by SeaHOH** [comment]
> 发现了一个现象默认的代理是127.0.0.1:8086

不清楚你讲的是哪个默认，关于本代理的端口，请查看 readme 介绍。

另外就是，很多 https 站点可以通过修改 sni 规则直连，不需要使用 GAE 代理。
如果你不看 U2B 就没必要上传，现在用起来不稳定，某些时候连通率很低。

**Comment by 722tzz** [comment]
如果不上传的话会出`AppID 配置为空，无法使用 GAE 代理`，不知该如何处理？

**Comment by SeaHOH** [comment]
>很多 https 站点可以通过修改 sni 规则直连，不需要使用 GAE 代理。
上面讲了，大部分封锁站点（包括大部分谷歌系）都能通过本工具直连。

如果你有刚需，请使用其它稳定的代理，可以通过浏览器插件或本工具调配。
免费的有自由门、无界、SS 免费帐号等。
