### ISSUE TITLE
3.5.4不能访问google或油管等

### ISSUE THREAD

**Issue by shpherd** [SeaHOH/GotoX#116]
================================================================================

 GotoX  版 本 : 3.5.4 (python/3.6.8 gevent(libuv-cffi-1.24.0)/1.4.0 pyOpenSSL/19
.0.0)

 GAE    AppID : nonpariel

 GAE 远程验证 : 已启用

  监 听 地 址 : 自动代理 - 127.0.0.1:8087
                GAE 代理 - 127.0.0.1:8086

  代 理 认 证 : 无需认证

  调 试 信 息 : INFO
否

  连 接 模 式 : 远程 - TLSv1.2
                本地 - TLS

  网 络 配 置 : ipv46

  IP 数 据 库 : CN IP from 17mon-20190809, range count: 3901

  直 连 域 名 : 2019-08-09, domains count: 65240, IPs count: 0

  安 装 证 书 : 设置代理后访问 http://gotox.go/
================================================================================

20:12:04 I IP 列表 'google_2p' 解析结果：iplist=['2607:f8b0:4005:804::2004', '17
2.217.5.100']

未连接到互联网 代理服务器出现问题，或者地址有误。
请试试以下办法：

联系系统管理员
检查代理服务器地址
运行 Windows 网络诊断
ERR_PROXY_CONNECTION_FAILED

**Comment by SeaHOH** [comment]
> 未连接到互联网 代理服务器出现问题，或者地址有误。

浏览器提示非常明确，请确认代理设置是否正确。
