### ISSUE TITLE
走代理 Gmail用不了

### ISSUE THREAD

**Issue by kxmp** [SeaHOH/GotoX#121]
我发现日志里面是乱七八糟的redirect
然后gmail说我账号暂时不可用.
我用代理登陆cloudflare也是登陆不上去. 虽然能打开页面但是登陆完了又跳回来...

![image](https://user-images.githubusercontent.com/6483602/64696190-625c1a00-d4d0-11e9-95b5-44a65de03dba.png)

**Comment by SeaHOH** [comment]
不要什么网站都使用 GAE 代理访问，免费应用的限制有很多。
如果你想要的是一种全局代理，请使用其它工具。
