### ISSUE TITLE
油管可以打开，视频加载不出来，求解！

### ISSUE THREAD

**Issue by diyici18sui** [SeaHOH/GotoX#122]
小白一个，大神勿怪。
XX-net这两天挂了，转来GotoX
昨天看了教程，配置了下，已经可以上谷歌 Gmail之类
遇到两个问题
一是油管视频加载不出来 错误反馈如下：
 L4:52516-> do_GAE 失败，url='https://r5---sn-8xgp1vo-p5ql.googlevideo.com/videoplayback?expire=1568268466&ei=UYx5XYW2PP2L3LUPh4uboAY&ip=124.65.241.18&id=o-ANJY7YgSPY29_jMbLr6ak0Ukq6m3XQJ7YRo_mF2Cl62n&itag=160&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-8xgp1vo-p5ql%2Csn-5uaeznd7&ms=au%2Crdu&mv=u&mvi=4&pl=20&mime=video%2Fmp4&gir=yes&clen=2155535&dur=532.465&lmt=1568216146261374&mt=1568246156&fvip=5&keepalive=yes&c=web&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgGQzM4zmMUM_fJm2xTjzow8dlAzhQVzVysHBs14B6rZMCIGqOGTjtBRpnprtKDgc3tuHaH3X915SybduiNwWvMhre&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHylml4wRQIhALFxmPYiKHV7_TLJuIs5Hw1YPjhABZ2hTd2GBJ9ujBa7AiBm_2aQ3a5ugVxnamra_XrhVBDaW67ZlVbdKhy4lRpQtQ%3D%3D&alr=yes&cpn=h_YkAKnTZIPf7rb8&cver=html5&range=0-2065&rn=34&rbuf=0'，重试
如此的错误会出现很多条。
二是看P站，会显示如下错误：
 L4:52631->66.254.114.41 "FWD CONNECT www.pornhub.com:443 HTTP/1.1" - -
求解！

**Comment by SeaHOH** [comment]
是否有部署服务端，如果没有，请到发布页面下载部署。
白色的是普通日志，不是错误信息。

Readme 写得不是很详细，很多内容我都在配置文件中有注释，建议也读一遍配置文件注释。

**Comment by nxtreaming** [comment]
既然是小白了，就不要折腾这种代理方案，直接用VPN方案，这样会避免折腾。

**Comment by diyici18sui** [comment]
> 是否有部署服务端，如果没有，请到发布页面下载部署。
> 白色的是普通日志，不是错误信息。
> 
> Readme 写得不是很详细，很多内容我都在配置文件中有注释，建议也读一遍配置文件注释。

感谢回复，一直用XX-net 以为部署过就没有重新部署，我去试下！谢谢！

**Comment by diyici18sui** [comment]
> 既然是小白了，就不要折腾这种代理方案，直接用VPN方案，这样会避免折腾。

谢谢··想做个爱折腾的小白··
