### ISSUE TITLE
问下比较初级的问题-IP数量为0

### ISSUE THREAD

**Issue by lshilshi** [SeaHOH/GotoX#125]
GotoX：3.5.4
上海电信宽度，IPv4环境，已提供一份9.14抓取的GWS IP表（放入data\ip_ex.txt）

软件设置
 GAE    AppID : **************************（已保密）
 GAE 远程验证 : 已启用
  监 听 地 址 : 自动代理 - 127.0.0.1:8087
                GAE 代理 - 127.0.0.1:8086
  代 理 认 证 : 无需认证
  调 试 信 息 : INFO否
  连 接 模 式 : 远程 - TLSv1.2
                本地 - TLS
  网 络 配 置 : ipv46
  IP 数 据 库 : CN IP from apnic-20190925/20190924, range count: 3874
  直 连 域 名 : 2019-08-09, domains count: 65240, IPs count: 0
  安 装 证 书 : 已安装

开启gotox后，ip_ex瞬间缩水
之后一直就是“W [picker gae] 当前 gae IP 数量为 0”

开了一下午没有任何变化，还是0
访问google，会跳转到hk，如果强制返回NCR，一样不能访问

是我哪里设置错了还是怎么的？

**Comment by miketwes** [comment]
files  in data/ :

directdomains.txt  
ip_del.txt      
ip_gws         
ip_stat_19267  
ip.txt.bak
directip.db        
ip_del.txt.bak  
ip_gws.bak     
ip_stat_19268  
ip.use
ip_bad             
ip_gae          
ip_stat_19265  
ip_stat_bak
ip_bad.bak         
ip_gae.bak      
ip_stat_19266  ip.txt

**Comment by SeaHOH** [comment]
> 开启gotox后，ip_ex瞬间缩水

这个是 bug，提前删除了 ip_ex.txt。
麻烦你看一下 ip_ex.txt 中的 IP 是否有正确导入 ip.txt。

>之后一直就是“W [picker gae] 当前 gae IP 数量为 0”
> 开了一下午没有任何变化，还是0

假如 IP 已导入 ip.txt，那么一上午肯定能筛选出来。你抓取 IP 的证书中是否有包含 `*.appspot-preview.com` 名称？这种 IP 才能用于 GAE 代理。
还有，你是否删除了本来的 ip.txt？

**Comment by lshilshi** [comment]
>这个是 bug，提前删除了 ip_ex.txt。
麻烦你看一下 ip_ex.txt 中的 IP 是否有正确导入 ip.txt。

原数据没保存，我下载2楼兄弟的数据试试看

> 假如 IP 已导入 ip.txt，那么一上午肯定能筛选出来。你抓取 IP 的证书中是否有包含 *.appspot-preview.com 名称？这种 IP 才能用于 GAE 代理。
还有，你是否删除了本来的 ip.txt？

是乱跑的，我是直接筛选所有可以访问google服务的IP整理的，看来的确有很多错误和冗余的
没有删除原本的ip.txt

重新跑下我在看看

**Comment by SeaHOH** [comment]
> 访问google，会跳转到hk，如果强制返回NCR，一样不能访问

先访问一次 https://www.google.com/ncr#hl=zh_CN
