### ISSUE TITLE
启动错误IndentationError: unexpected indent。。。咋办？

### ISSUE THREAD

**Issue by loveinlastnight** [SeaHOH/GotoX#127]
启动错误。。。咋办？
```
Traceback (most recent call last):
  File "D:\GotoX-3.5.4-cp36-win_amd64\start.py", line 9, in <module>
    from local import proxy
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\proxy.py", line 54, in <module>
    from .GlobalConfig import GC
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\GlobalConfig.py", line 12, in <module>
    from .common.util import wait_exit
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\common\util.py", line 308
    if cls.maxsize <= 0:
    ^
IndentationError: unexpected indent
```
已经按照：https://github.com/SeaHOH/GotoX/commit/f3c4e0bab6933d3e7179abde2c78230ef05d8b15

修改过了。啥原因呢？

**Comment by SeaHOH** [comment]
试试直接下载主分支来覆盖

**Comment by loveinlastnight** [comment]
。。。覆盖，真的好了。

15:15:15 W 读取系统当前 DNS 设置失败
================================================================================
 GotoX  版 本 : 3.5.4 (python/3.6.8 gevent(libuv-cffi-1.24.0)/1.4.0 pyOpenSSL/19.0.0)

 GAE    AppID : 请填入 AppID

 GAE 远程验证 : 已启用

  监 听 地 址 : 自动代理 - 127.0.0.1:8087
                GAE 代理 - 127.0.0.1:8086

  代 理 认 证 : 无需认证

  调 试 信 息 : INFO
否

  连 接 模 式 : 远程 - TLSv1.2
                本地 - TLS

  网 络 配 置 : ipv46

  IP 数 据 库 : CN IP from APNIC-20190608/20190607 and 17mon-20190608 and GaoYiFan-20190608, range count: 4806

  直 连 域 名 : 2019-06-08, domains count: 61834, IPs count: 0

  安 装 证 书 : 设置代理后访问 http://gotox.go/
