### ISSUE TITLE
所有网站无法登录

### ISSUE THREAD

**Issue by daxinnan** [SeaHOH/GotoX#128]
我也不知道哪一步造成的😭
只是在尝试上传GAE 服务端，Config.ini里面只改了appid其他都是默认的
现在不运行gotoX的情况下一个网站都没办法打开，运行GotoX启用8087端口之后能上谷歌和youtube，其他的像baidu github都还是打不开，但是电脑版微信这种都能正常使用，只有浏览器无法访问，包括chrome和firefox都不行，微信内置浏览器也不能。
/etc/ufw看了下应该没问题，/etc/hosts只有
```
127.0.0.1 localhost
127.0.1.1 usrname-PC
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
还新装了个`dnscrypt-proxy` v2的版本配置了下它的toml文件，别的好像也没动哪里了
然后我的miredo好像无法启动了，执行`ifconfig -a`结果里teredo部分没有scopeid global啥的相关信息。
因为是手机敲的没法上传截图请见谅
我该咋办，还能从哪些方面着手解决
我是ubuntu 18.04 chrome 77正式版 clone的最新gotox data和config.ini使用的是[xx-net-linux](https://github.com/miketwes/XX-Net-Linux)

**Comment by SeaHOH** [comment]
如果你不记得自己用什么方式设置过代理，请检测你的系统网络代理设置、环境变量设置。

**Comment by daxinnan** [comment]
昨天和今天上午gotoX都是正常使用的，今天下午就重启了下世界就变了。
我系统的默认代理是关闭的
环境变量在此前后没有动过

**Comment by SeaHOH** [comment]
还记得重启前运行过的程序或脚本吗？检查一下。
