### ISSUE TITLE
错误：BrokenPipeError（<-- #13）

### ISSUE THREAD

**Issue by SeaHOH** [SeaHOH/GotoX#14]
移动自 #13 
出现 Broken pipe 的话应该调整什么参数合适？

>13:57:06 I 17.252.201.246 "FWD CONNECT api-aka.smoot.apple.com:443 HTTP/1.1" - -
13:57:18 W 转发 None 失败：BrokenPipeError(32, 'Broken pipe')
21:20:51 W 113.171.253.26 do_GAE "POST https://gsp64-ssl.ls.apple.com/a/v2/use" 返回：BrokenPipeError(32, 'Broken pipe')，重试
21:20:52 E 113.171.240.110 do_GAE "POST https://gsp64-ssl.ls.apple.com/a/v2/use" 失败：BrokenPipeError(32, 'Broken pipe')`
21:25:14 I 192.30.253.116 "FWD CONNECT api.github.com:443 HTTP/1.1" - -
21:25:20 W 转发 None 失败：BrokenPipeError(32, 'Broken pipe')
21:25:20 W 转发 None 失败：BrokenPipeError(32, 'Broken pipe')
21:25:29 I 17.248.156.108 "FWD CONNECT p44-keyvalueservice.icloud.com:443 HTTP/1.1" - -
21:25:31 I 17.248.156.108 "FWD CONNECT p44-keyvalueservice.icloud.com:443 HTTP/1.1" - -
21:25:33 W 转发 None 失败：BrokenPipeError(32, 'Broken pipe')
21:25:33 I 192.30.253.113 "FWD CONNECT github.com:443 HTTP/1.1" - -
21:26:16 W 转发 None 失败：BrokenPipeError(32, 'Broken pipe')

**Comment by SeaHOH** [comment]
@giveup 
我把报错转到这里了。
这个错误我重来没见过，你能不能把你的使用环境描述一下。

**Comment by giveup** [comment]
macOS 10.12.3
GotoX https://github.com/SeaHOH/GotoX/commit/f8da2b9065ac61f1ada55c51e7cd0161d8056d49

**Comment by SeaHOH** [comment]
3.6 我还没测试过，意思是今天的更新 https://github.com/SeaHOH/GotoX/commit/f8da2b9065ac61f1ada55c51e7cd0161d8056d49 出问题了？

**Comment by SeaHOH** [comment]
@giveup 
除了会报错，能不能正常使用呢？

**Comment by giveup** [comment]
@SeaHOH 都会,我还以为还是需要调整参数.用的话倒是能用.严谨一点说,不确定能否正常用...
因为,我这地区访问GitHub本来就慢,那么慢到底是GotoX代理造成呢?
还是因为自身网络直接访问GitHub慢造成.我也不确定...

**Comment by SeaHOH** [comment]
那么就是 macOS 下之前也有这个报错，我会把这个错误从代码里面忽略，因为不影响使用。

问一下，你用其它 GAE 类代理是否也是这么慢呢？你把 GAE IP 换成这个项目（https://github.com/out0fmemory/GoAgent-Always-Available ）的 IP  看看速度如何，注意换一下格式。

**Comment by SeaHOH** [comment]
你是默认配置没改过对吧，那就是你自身网络的问题，把 `github.com` 和其它相关主机名加入 GAE 规则就好了。

有代理就要用啊，你不使用代理时上不了的网址都可以加进去，这个需要自己动手。
虽说我也设定了自动尝试，但那个算是临时处置，而且也不一定起作用，手动加入最保险。
或者你还是习惯 pac，那就找一份跟随 gwflist 的 pac，把端口改成 8086 就行。

**Comment by SeaHOH** [comment]
@giveup 
怎么样，还报错不？加入代理规则后速度是否不再慢了？

**Comment by giveup** [comment]
@SeaHOH 报错没那么多了.不过还是有一些的.
`17:38:11 E 伪造加密链接失败：host='syndication.twitter.com'，OSError(22, 'Invalid argument')`
`127.0.0.1:62344 - - [28/Mar/2017 17:40:38] code 501, message Unsupported method ('PROPFIND')
`
这个似乎是GAE的限制,使用了不支持的方法.

**Comment by SeaHOH** [comment]
GAE 连标准方法都不完全支持，何况 WebDAV。
实际上不走 GAE 是不会报错的，但是翻不了。

解决方案：
```ini
#这个是利用反代 IP 转发
[顺序-forward]
https://syndication.twitter.com = 反代 IP

#这个是利用其它后端代理
[顺序-proxy]
https://syndication.twitter.com = 其它后端代理
```
