### ISSUE TITLE
cfw反馈

### ISSUE THREAD

**Issue by k79e** [SeaHOH/GotoX#143]
我发现下载资源文件的时候 比如图片. (png的 大小600-800k 单独标签开一张图)
有时候直接变成白色屏幕 不知道为什么. (chrome就算看个像素点 也应该是黑背景) 这个时候那个黑背景 变全白了. 我应该没记错 就是整个网页就白了.

然后我发现下载大的资源. 测试用的是个7m差不多的图片 发现经常会卡住不动.
5m的测试正常. (后面发现也卡了 是走一个特定的代理才是那样. )

//不太确定大资源卡住是不是cfw的问题 可能是我这里面一个代理卡了.
但是更诡异的是 资源全载入完 突破也是卡住. 显示的就是 从一个地方 断开 下面都是黑色的.

我发现png图片 打开的时候变成**渐进**的了!!! 这是服务端做的操作么? 不知道他会不会消耗算力然后某些情况卡住?

**Comment by SeaHOH** [comment]
初期测试会有一大堆问题，请统一反馈到 #142 ，谢谢。
