### ISSUE TITLE
3.6.0a do_GAE失败

### ISSUE THREAD

**Issue by loveinlastnight** [SeaHOH/GotoX#144]
日志如下：
01:49:50 W [picker gws] 3 测试失败（超时：1000 ms）66.96.224.172，7970 ms
01:50:03 W L4:58065-> do_GAE 失败，url='https://www.google.com/'，重试
01:50:04 W L4:58065-> do_GAE 失败，url='https://www.google.com/favicon.ico'，重试
01:50:14 W [picker gws] 2 测试失败（超时：1000 ms）172.217.161.155，2147 ms，Bad IP 已删除
01:50:24 W L4:58092-> do_GAE 失败，url='https://youtube.com/'，重试
01:50:27 W L4:58092-> do_GAE 失败，url='https://youtube.com/favicon.ico'，重试
01:50:51 W [picker gws] 3 测试失败（超时：1000 ms）172.217.166.86，7842 ms
01:51:16 W [picker gws] 2 测试失败（超时：1000 ms）172.217.166.184，2480 ms，Bad IP 已删除
01:51:36 W L4:58197-> do_GAE 失败，url='https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=E/4SsmXJqSxcYjCxQXLf2A%3D%3D'，重试
01:51:37 W L4:58197-> do_GAE 由于有上传数据 "POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=E/4SsmXJqSxcYjCxQXLf2A%3D%3D" 终止重试

3.5.6版，设置和3.6.0a一样，却正常访问。。
日志如下：
01:58:48 I L4:58672->172.253.118.153 "GAE POST https://www.youtube.com/notifications_ajax?action_get_registration_token=1 HTTP/1.1" 400 30
01:58:48 I L4:58692->172.217.166.148 "GAE GET https://i.ytimg.com/vi/D6uQVGJviXA/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCXKitgcgVbW0XlAWDf4jIVH9ZQsg HTTP/1.1" 200 98162
01:58:48 I L4:58675->172.217.168.244 "GAE GET https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fChc4EsA.woff2 HTTP/1.1" 200 11804

问题出在哪里呢？

**Comment by SeaHOH** [comment]
data 文件夹复制没有？不过没复制也没关系，多运行点时间就好了。

你这日志精简的太厉害，但我已经有点懂你的套路了。 :smiling_imp:

**Comment by loveinlastnight** [comment]
3.6.0a是新下载的，运行了很久了。GAE的IP也有了十几个。还是GAE错误，打开网站，错误如下：

GAE-'https://youtube.com/' 请求超时，请稍后重试。

**Comment by loveinlastnight** [comment]
17:17:32 W L4:53342-> do_GAE 失败，url='https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZSEYTHpsF8mcjLdbAqOckIy39p0bUJBQ='，重试
17:17:35 W L4:53342-> do_GAE 失败，url='https://clients1.google.com/tbproxy/af/upload'，重试
17:17:35 W L4:53342-> do_GAE 由于有上传数据 "POST https://clients1.google.com/tbproxy/af/upload" 终止重试
17:17:35 W L4:53348-> do_GAE 失败，url='https://clients1.google.com/tbproxy/af/upload'，重试
17:17:36 W L4:53348-> do_GAE 由于有上传数据 "POST https://clients1.google.com/tbproxy/af/upload" 终止重试
17:17:40 W L4:53350-> do_GAE 失败，url='https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=E/4SsmXJqSxcYjCxQXLf2A%3D%3D'，重试
17:17:40 W L4:53350-> do_GAE 由于有上传数据 "POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=E/4SsmXJqSxcYjCxQXLf2A%3D%3D" 终止重试
17:17:46 W L4:53351-> do_GAE 失败，url='https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZzQa7RVHNymgjLdKj4pQkIy2UK-IdJBQTGWMdJ2ISs6N4Iy2_CP-zJCMtlCviHSQUExnauyHTZnL25yMtkWGVTiQjLde-K0skIy39p0bUJBQ='，重试
17:17:47 W L4:53353-> do_GAE 失败，url='https://www.googleapis.com/gmail/v1/users/me/history?labelId=UNREAD&startHistoryId=494766&maxResults=100&fields=history%28labelsAdded%2ClabelsRemoved%2CmessagesAdded%2CmessagesDeleted%29%2ChistoryId%2CnextPageToken'，重试
17:17:47 W L4:53352-> do_GAE 失败，url='https://www.googleapis.com/gmail/v1/users/me/history?labelId=UNREAD&startHistoryId=496999&maxResults=100&fields=history%28labelsAdded%2ClabelsRemoved%2CmessagesAdded%2CmessagesDeleted%29%2ChistoryId%2CnextPageToken'，重试

**Comment by SeaHOH** [comment]
不要贴错误精选，你这点日志根本没用。。。

话说，谷歌系网站为什么还要代理，直连它不香么。默认配置就好了大部分，你居然不用。

**Comment by loveinlastnight** [comment]
呃，一直设的用GAE代理，看啥时候连的上，。。。

**Comment by SeaHOH** [comment]
看看这个 https://github.com/SeaHOH/GotoX/issues/145#issuecomment-593190181 ，你确定不是设置或者 IP 数量的问题？

**Comment by loveinlastnight** [comment]
又运行了1小时，还是失败，检查ip_gae，IP数量30多个，ip.use，IP数量8个。
复制3.5.6的这两个文件覆盖，gae成功运行。
以前3.5.6，运行一会就可以连gae，怎么3.6半天没足够IP呢。。

**Comment by SeaHOH** [comment]
虽然你说了设置相同，但是确定有开启扫描吗？你贴的日志里面只有 `[picker gws]`，没看见 `[picker gae]`。

**Comment by loveinlastnight** [comment]
我去检查下，谢谢你提醒！

**Comment by loveinlastnight** [comment]
[picker/gae]
#当发现筛选模式当前得到的 IP 质量较好时，可关闭筛选功能固定使用这些 IP
enable = 0
这项下载全新的3.6.0a没注意，改为1后，有[picker gae]了。
