### ISSUE TITLE
用最新GotoX-master覆后闪退

### ISSUE THREAD

**Issue by loveinlastnight** [SeaHOH/GotoX#147]
用最新GotoX-master覆后闪退，重新下载2月19日完整包，就正常运行。
海兄检查下，是不是有什么BUG.

**Comment by SeaHOH** [comment]
https://github.com/SeaHOH/GotoX/issues/142#issuecomment-601645521

**Comment by loveinlastnight** [comment]
删除还是闪退，用最新master覆盖后，解决问题。

**Comment by SeaHOH** [comment]
应该是覆盖后删除，可能有步骤没对。

**Comment by loveinlastnight** [comment]
对了。先覆盖，再删除，就不闪退了。
