### ISSUE TITLE
是否支持PHP空间搭建？

### ISSUE THREAD

**Issue by pynne** [SeaHOH/GotoX#148]
是否支持PHP空间搭建？ 因为这样很便宜。现在php一般支持php7以上

**Comment by SeaHOH** [comment]
GotoX 不以收费服务为目标，如果你发现有其它稳定的免费服务，欢迎提供相应信息，我十分乐意添加支持。

**Comment by Quantum2Bits** [comment]
Heroku 的PHP是免费的。原来有些支持Heroku的软件已经不更新了。

**Comment by SeaHOH** [comment]
免费 Heroku 应用启动太慢。
