### ISSUE TITLE
IP库更新失败

### ISSUE THREAD

**Issue by lshilshi** [SeaHOH/GotoX#165]
```
16:59:11 I APNIC 列表下载完毕
16:59:11 I 开始下载 17mon 列表
16:59:12 I L4:51117->151.101.228.133 "FWD CONNECT raw.githubusercontent.com:443
HTTP/1.1" - -
16:59:23 I L4:51140->151.101.228.133 "FWD CONNECT raw.githubusercontent.com:443
HTTP/1.1" - -
16:59:34 I L4:51165->151.101.228.133 "FWD CONNECT raw.githubusercontent.com:443
HTTP/1.1" - -
16:59:34 W 请求网址 'https://raw.githubusercontent.com/17mon/china_ip_list/maste
r/china_ip_list.txt' 时，重试 2 次后仍然失败。
16:59:34 W 请忽略下面这个错误跟踪，并检查是否需要更改自动代理规则（ActionFilter.
ini）。
```
正常运行下，系统代理设置无，Chrome通过SwitchyOmega调度代理
访问google，Gayhub正常
但是更新IP库就始终卡在17mon这里

先还以为是Gotox自身更新要通过系统代理，于是设置系统代理为CFW代理（CFW正常）
更新仍然是卡在17mon这

两种情况下，手动访问gayhub的[raw](https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)
可以访问，显示正常

**Comment by SeaHOH** [comment]
raw.githubusercontent.com 经常被干扰，我测试使用 CFW 能正常更新 IP。

> 16:59:34 W 请忽略下面这个错误跟踪，并检查是否需要更改自动代理规则（ActionFilter.
> ini）。


请到 ActionFilter.ini 中添加相应的 CFW 规则。

**Comment by lshilshi** [comment]
> raw.githubusercontent.com 经常被干扰，我测试使用 CFW 能正常更新 IP。
> 
> > 16:59:34 W 请忽略下面这个错误跟踪，并检查是否需要更改自动代理规则（ActionFilter.
> > ini）。
> 
> 请到 ActionFilter.ini 中添加相应的 CFW 规则。

怎么添加？说实话，ActionFilter.ini 的说明我看过好几次，还是让我云山雾里……
另外，我直接在浏览器中访问地址，是可以显示内容的，也就是访问raw.githubusercontent.com 的规正常（cfw还是forword？但至少是可用的）
只是更新时失败，这个还有必要更新action规则么？

**Comment by SeaHOH** [comment]
把 `raw.githubusercontent.com` 添加到任意一个 CFW 节段中即可，中间有一个，最后一个也是。

> 只是更新时失败，这个还有必要更新action规则么？

需要。

**Comment by lshilshi** [comment]
> 把 `raw.githubusercontent.com` 添加到任意一个 CFW 节段中即可，中间有一个，最后一个也是。
> 
> > 只是更新时失败，这个还有必要更新action规则么？
> 
> 需要。

加入CFW段后成功。

不过在默认action配置下，用8087端口，就是自动模式打开google搜索失败
```
09:57:48 W 2607:f8b0:4005:800::100d _create_ssl_connection 'www.google.com' 返回
 timeout('timed out')，重试
09:57:49 W 2607:f8b0:4005:800::100d create_ssl_connection 'https://www.google.co
m/search?q=ert&oq=ert&ie=UTF-8' 失败：timeout('timed out')
```
而用8086端口，cfw代理模式就没问题

看了下action配置，
.google. = google_gws
google.com = google_gws
.google.com = google_gws
这3项默认在[70-direct] #代理直连（兼容性较好）下
又是需要将google相关的规则加到cfw段以下？

**Comment by SeaHOH** [comment]
现在不定时段谷歌直连比较困难，但是多刷一两次还是能用。谷歌连接比较多，很多网站也在用，一般不建议使用 CFW 来代理，会快速消耗请求数。不过你可以试着用几天，看看会不会超免费套餐限额。

注意，规则前面的数值是匹配顺序，第一个匹配到的就是最终使用的规则。
