### ISSUE TITLE
是否可通过某种方法只使用 SNI 伪造功能？

### ISSUE THREAD

**Issue by 185264646** [SeaHOH/GotoX#167]
这个项目也好久没更新了，我也不打算用这里面的GAE和CFW啥的。只想用这玩意绕过SNI阻断，不挂梯子连接avatars3.githubusercontent.com。有办法进行配置吗？

**Comment by SeaHOH** [comment]
> 只想用这玩意绕过SNI阻断，不挂梯子连接avatars3.githubusercontent.com。有办法进行配置吗？

单只用 SNI 伪造可以这样配置：
1. 关闭默认开启的 GWS IP 筛选
1. 配置 [filter] 默认动作为 2 (forward)
1. 清空你不需要的默认自动规则，注意 DoH 相关不要删除
1. 配置你的 SNI 伪造规则
1. 可能的话建议通过浏览器扩展智能规则调用，这样其它无需伪造的连接可减少一次转发

这里有个问题，`.githubusercontent.com` 似乎并未被阻断，我这里是能够直连的。
