### ISSUE TITLE
不能同时使用 CFW 和 GAE

### ISSUE THREAD

**Issue by loveinlastnight** [SeaHOH/GotoX#168]
ACT默认是CFW.此时即使指定了某个域名使用GAE，也是走CFW代理。
如果ACT设定GAE,指定走CFW的域名也走GAE了。
怎么设置能同时使用CFW和GAE呢？

**Comment by SeaHOH** [comment]
**活动**代理端口和临时规则都始终使用 act 设置。你是如何指定并使用的呢？

正确做法是在**自动**规则配置文件中指定，然后通过**自动**代理端口使用。

**Comment by loveinlastnight** [comment]
搞好了。原来没有去掉;号。
