### ISSUE TITLE
系统代理导致Win10应用商店无法访问

### ISSUE THREAD

**Issue by ivysrono** [SeaHOH/GotoX#17]
尚不清楚系统更新无法进行是否也是这个原因。
Win10 x64

**Comment by jzp820927** [comment]
可能是因为不能访问 环回地址的原因吧

**Comment by SeaHOH** [comment]
你可以禁用代理看是否正常。
CA 证书安装到系统中没有？

**Comment by SeaHOH** [comment]
@jzp820927 
你这么一说，我想起好像有个软件可以破解 Win10 的代理设置。

**Comment by ivysrono** [comment]
@SeaHOH 禁用代理正常，使用MEOW正常。就是确认了这点才来报bug的，困惑了好几天了。
确实有软件可以破解UWP的代理设置，不过暂时用不到~

**Comment by SeaHOH** [comment]
你用的是 Firefox，这个肯定是导入了 CA 证书的，但是证书安装到系统了吗？
设置代理后用 Edge 访问 http://gotox.go 即可点击安装。

如果还是不对，你的设置能否贴一份？
还有你可能需要下载最新的主分支代码更新一下。

**Comment by SeaHOH** [comment]
又搜索了一下，商店要不破解，要不就不要设置环回地址的代理。
建议破解，或者你单独写一个 pac 排除微软地址。

**Comment by jzp820927** [comment]
@SeaHOH 按他说的 XXNET 正常，可能就不是环回地址的原因了，XXNET 也是用的 环回地址。

**Comment by SeaHOH** [comment]
估计他用的不是全局，而是 pac，这就绕过代理了。

**Comment by jzp820927** [comment]
我觉得应用商店没必要走代理，使用没必要用全局。

**Comment by SeaHOH** [comment]
@jzp820927 
因为没有搞 pac，我本意就是取代 pac，刷新麻烦。没想到 Win10 是个怪胎，还好有破解。

**Comment by ivysrono** [comment]
> 或者监听地址改为 0.0.0.0，然后手动设置系统代理为你的局域网 IP。

更新到了f9d9d4d，这个方法没用。

我有时候还是要用Edge和Chrome的，所以肯定是成功导入证书了。

**Comment by jzp820927** [comment]
应该就只有 win10 有这个问题吧

**Comment by ivysrono** [comment]
应用商店还有win8有，就没法测试了

**Comment by jzp820927** [comment]
win8 没听谁说过有不能访问环回地址的问题，win10 到时有过案例。

**Comment by SeaHOH** [comment]
@ivysrono 
既然这样，要是不想破解，就只有用 pac 了。但我不打算放进 GotoX 里面。
你可以把下面这个存为 pac 文件，手动设置到系统代理，pac 优先级最高。
```pac
var Direct = 'DIRECT';
var GotoX = 'PROXY 127.0.0.1:8087';

function FindProxyForURL(url, host) {
    //1、本机地址
    if (
        host == '127.0.0.1'  || // 本机
        isPlainHostName(host)   // 不包含点
        )
        return Direct;
    //2、文件协议及本地地址
    var Protocol = url.split(':', 1)[0];
    var hostsp = host.split('.'); // 前面已经检测过点了，所以长度肯定大于 1
    if (
        Protocol == 'ftp'    || // ftp
        Protocol == 'file'   || // file
        Protocol == 'gopher' || // gopher
        hostsp[0] == '192'   && // 局域网地址自行修改
        hostsp[1] == '168'   &&
        hostsp[2] == '1'
        )
        return Direct;
    if (host.indexOf('microsoft') == 0)
        return GotoX;
    else:
        return Direct;
```

**Comment by ivysrono** [comment]
谢谢，用这个PAC确实能解决问题。
当然，还是建议内置，至少要写入 Wiki 中。
原因很简单，同样的问题影响不止应用商店，我已经确认，Win10 系统更新同样受到破坏。
主楼说 MEOW 没问题，的确是因为调用 PAC，如果是全局，一样的问题。

**Comment by SeaHOH** [comment]
我再考量一下，暂时不会放入 GotoX。
还有那个网址如果不止 `microsoft` 还有其它的话，请先自己添加修改。

**Comment by ivysrono** [comment]
更新到 Win10 1073 最新版后，PAC文件失效，全部直连了……

**Comment by SeaHOH** [comment]
不至于吧，关闭 pac 再重新设置一次试试看。

**Comment by ivysrono** [comment]
都重装过系统了……

**Comment by ivysrono** [comment]
我就是来报个bug，系统重装百废待兴ε=ε=ε=┏(゜ロ゜;)┛
现在系统代理用MEOW的PAC，Firefox代理设定成 GotoX

**Comment by SeaHOH** [comment]
pac 失效的锅不背，我给你的那个 pac 应该是没啥问题的，除非微软改接口了。

**Comment by jzp820927** [comment]
没听其他人反应过 win10 不能用 pac，XX 那边用 PAC 的，系统是 win10 的还是蛮多的。

**Comment by SeaHOH** [comment]
又看了下，上面那段 pac 结尾的确少了个大括号，至于能不能用，我没有 Win10。

**Comment by SeaHOH** [comment]
@ivysrono 
找到一份 Win10 升级使用的域名，可以帮助你修改 pac。
http://www.crazyws.fr/WindowsSpyBlocker/hosts/win10/update.txt

**Comment by jzp820927** [comment]
太牛了，这个都能找到。

**Comment by SeaHOH** [comment]
机缘巧合，都是猿汾。

**Comment by jzp820927** [comment]
我想要一份 onedrive 同步用到的域名，还有 win10子系统 ubuntu 下载时候用的域名。不知道你有没有

**Comment by SeaHOH** [comment]
@jzp820927 
真是无意间看到的，我手头只有一台 Win7 设备，没法试。
我觉得你可以通过抓包软件或者网络监控软件得到这些域名。

**Comment by ivysrono** [comment]
加上大括号还是全部直连。

[pac.txt](https://github.com/SeaHOH/GotoX/files/916419/pac.txt)

**Comment by jzp820927** [comment]
我还没用过抓包软件，都是通过 chrome F12 分析。

**Comment by SeaHOH** [comment]
@ivysrono 
不是我要甩锅，我只有 Win7，没法测。
这个 pac 还是比较简单的，你可以尝试自己修改一下。

还有，你是保存的 `pac.txt` 作为文件名吗？尝试修改成 `.pac` 扩展名，有可能是这个原因。

**Comment by ivysrono** [comment]
我是用的 GotoX.pac 改成 txt 是因为 gayhub 对附件后缀名有限制。

**Comment by SeaHOH** [comment]
哦，没必要上传文件。直接描述修改就行了，或者直接贴出来。
