### ISSUE TITLE
CFW 超时问题

### ISSUE THREAD

**Issue by ZK6100HGA** [SeaHOH/GotoX#178]
使用CFW代理时运行一段时间之后就会疯狂超时，网页加载很慢甚至无法加载。重启后恢复正常，但运行一段时间后又这样。
 `_create_ssl_connection ' ' 返回 timeout('The read operation timed out')，重试`

>

**Comment by SeaHOH** [comment]
你以前使用过是正常的吗？我这里一直在使用，没有发现这样的现象，也许是你的网络环境有变化。

你是否调整过超时参数、每 IP 最大连接数、自选 IP 节点？可以使用默认参数试试。

**Comment by ZK6100HGA** [comment]
> 
> 
> 你以前使用过是正常的吗？我这里一直在使用，没有发现这样的现象，也许是你的网络环境有变化。
> 
> 你是否调整过超时参数、每 IP 最大连接数、自选 IP 节点？可以使用默认参数试试。

以前是正常的。随着使用次数的增多，出现此现象所需时间越来越短。全部参数都是默认。

**Comment by SeaHOH** [comment]
你是不是所有流量都用 CFW 代理？这样是不行的，单个 CFWorker 请求队列是 6 还是 8 忘了，后续请求会挂起，然后本地就会出现超时。解决方法，一是增加超时时间参数，不推荐；二是切换到自动端口，仅部分自定义站点使用 CFW 代理。
