### ISSUE TITLE
本地播放器或下载工具出现断流问题请在这里详述

### ISSUE THREAD

**Issue by SeaHOH** [SeaHOH/GotoX#18]
主要收集出问题的软件名称和版本。
具体表现为：
本地播放器播放网络媒体时拖动进度条后断流；
多线程下载工具下载部分文件后断流，此时停止下载任务后仍然可以继续下载才算，停止后无法继续则与本软件无关。

**Comment by jzp820927** [comment]
这是要 强化 autorange 么？

**Comment by SeaHOH** [comment]
@jzp820927 
不是，这几天开启了代理的长链接模式，出现不少问题，收集一下做个排除列表。
还有些是播放软件本身对长链接支持不好。我自己用的 mpv 就这样，至少在代理下如此，也懒得测试不用代理了，所以没去报错。
当然，如果其它没问题就算了。

**Comment by jzp820927** [comment]
哦，原来是这个意思。看来做兼容还是个体力活。
