### ISSUE TITLE
cp39版本的3.7和3.8.1访问gotox.go提示"代理服务器拒绝连接"

### ISSUE THREAD

**Issue by CJN1986** [SeaHOH/GotoX#183]
下载的GotoX-3.8.1-cp39-win_amd64.7z和GotoX-3.7.0-cp39-win_amd64.7z，解压后不作任何修改，直接运行GotoX.vbs，去火狐浏览器里设置代理为127.0.0.1:8086，访问gotox.go时提示"代理服务器拒绝连接"

系统是win8.1，浏览器是火狐68

下面的log是GotoX-3.8.1-cp39-win_amd64生成的，配置文件仅修改了debug改为3和保存log
[log.txt](https://github.com/SeaHOH/GotoX/files/6178266/log.txt)

**如果下载GotoX-3.7.0-cp38-win_amd64.7z是可以正常访问gotox.go并安装证书的。**

**Comment by SeaHOH** [comment]
Python 3.9 是原生支持 Win 8 的，我的改造行为仅针对 Win 7，3.7.0 的两个包中 GotoX 的代码和配置并没有任何不同。我怀疑是触发了 #182 提到的 bug，你现在正常使用的版本也可能会触发。修改事件循环为 libev-cext 后再重新启动，看是否能正常运行。

**Comment by CJN1986** [comment]
GotoX-3.8.1-cp39 修改事件循环为 libev-cext 后正常运行
