### ISSUE TITLE
一个重要的问题（安卓支持）

### ISSUE THREAD

**Issue by nextgental** [SeaHOH/GotoX#19]
xx-net 安卓版在我手机上运行时停在 loading 界面,无法使用
因此想询问海大,你的代码能否用于安卓系统
goproxy那个我看过,需要root权限 而我的手机解锁不保修,不能root

**Comment by nextgental** [comment]
据说可以用 gnuroot debian 而我试过xx-net代码,出了很奇怪的问题,在xx-net 板块我贴出来了
怀疑是xx-net 的代码没对安卓系统优化所致

**Comment by nextgental** [comment]
自从fqrouter失效后就希望能有人把GAE代理在安卓系统上实现,至今没成功,不知海大有无这个意愿

**Comment by SeaHOH** [comment]
不是很懂啊，我就是个野狐禅。
如果 gnuroot debian 无需 root，你可以自己尝试一下，从 `start.py` 启动就是；
代码方面因为没有自动导入证书啥的，估计还是能用的。

其实保修啥的，不用太较真，这属于霸王条款，只要一年内就必须保，如果是过了保期就更无所谓了。

**Comment by jzp820927** [comment]
termux 用过，是不需要 root 的，gnuroot 没用过，不太清楚。

**Comment by SeaHOH** [comment]
@nextgental 
想起个问题，GotoX 不兼容 Python2，可能找不到 相应版本的 pyOpenSSL。

**Comment by nextgental** [comment]
有 python3-openssl 的包,可以解决

**Comment by nextgental** [comment]
据说114 dns 泄露隐私 因此我换了level3 和 norton 的dns,自测速度较快,请查收

**Comment by SeaHOH** [comment]
你这错别字不忍直视。
好吧，如果能用我就把标签删掉，等你反馈。

**Comment by nextgental** [comment]
用不了,可以关了
