### ISSUE TITLE
GAE服务端无法部署

### ISSUE THREAD

**Issue by 3061732350** [SeaHOH/GotoX#190]
**Hi，我这里有一些网站无法通过CFW代理，因此我只能使用GAE
当我尝试部署的时候，弹出以下错误。**

开始上传……
10:54 AM Application: chengzi114
10:54 AM Host: appengine.google.com
10:54 AM Rolling back the update.
上传 (chengzi114) 失败 1 次，重试……
10:55 AM Application: chengzi114
10:55 AM Host: appengine.google.com
10:55 AM Rolling back the update.
上传 (chengzi114) 失败 2 次：error(10060, '')
Traceback (most recent call last):
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\uploader.py", line 191, in retry_
upload
    upload(dirname, appid)
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\uploader.py", line 182, in upload

    appcfg(['appcfg', 'rollback', dirname])
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 5514, in main
    result = AppCfgApp(argv).Run()
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 2977, in Run
    self.action(self)
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 5170, in __call__
    return method()
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 4523, in Rollback
    self._Rollback()
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 4568, in _Rollback
    appversion.Rollback(force_rollback)
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 2387, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\google_appengine\google\appengine
\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line
 246, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "google_appengine\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
error: [Errno 10060]

以下 AppID 上传失败：
chengzi114

按回车键开始重新上传……

**我之前在XX-Net部署过几个Appid，了解到现在部署方式有所更新。
当我采用XX-Net相同的方式，使用gcloud app deploy上传app.yaml，提示以下错误。**

C:\Users\Jimmy\AppData\Local\Google\Cloud SDK>gcloud app deploy C:\Users\Jimmy\Desktop\GotoX-gae-r6-
c2\gae\app.yaml
ERROR: (gcloud.app.deploy) The [application] field is specified in file [C:\Users\Jimmy\Desktop\Goto
X-gae-r6-c2\gae\app.yaml]. This field is not used by gcloud and must be removed. Project name should
 instead be specified either by `gcloud config set project MY_PROJECT` or by setting the `--project`
 flag on individual command executions.

**以下是乱捣鼓**
**我删除了application这一行，再次运行，提示以下错误。**

C:\Users\Jimmy\AppData\Local\Google\Cloud SDK>gcloud app deploy C:\Users\Jimmy\Desktop\GotoX-gae-r6-
c2\gae\app.yaml
ERROR: (gcloud.app.deploy) The [version] field is specified in file [C:\Users\Jimmy\Desktop\GotoX-ga
e-r6-c2\gae\app.yaml]. This field is not used by gcloud and must be removed. Versions are generated
automatically by default but can also be manually specified by setting the `--version` flag on indiv
idual command executions.

**我又删除了version这一行，再次运行，提示以下错误。**

C:\Users\Jimmy\AppData\Local\Google\Cloud SDK>gcloud app deploy C:\Users\Jimmy\Desktop\GotoX-gae-r6-
c2\gae\app.yaml
ERROR: (gcloud.app.deploy) Staging command [C:\Users\Jimmy\AppData\Local\Google\Cloud SDK\google-clo
ud-sdk\platform\google_appengine\go-app-stager.exe C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\gae\app.ya
ml C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\gae C:\Users\Jimmy\AppData\Local\Temp\tmp_ecc9rm8\tmpvybhz
2rv] failed with return code [1].

------------------------------------ STDOUT ------------------------------------
------------------------------------ STDERR ------------------------------------
2021/07/07 11:08:33 invalid runtime value go
--------------------------------------------------------------------------------

**我有尝试过把runtime改成go111之类的，但是仍然会报错。**

C:\Users\Jimmy\AppData\Local\Google\Cloud SDK>gcloud app deploy C:\Users\Jimmy\Desktop\GotoX-gae-r6-
c2\main\app.yaml
ERROR: (gcloud.app.deploy) Staging command [C:\Users\Jimmy\AppData\Local\Google\Cloud SDK\google-clo
ud-sdk\platform\google_appengine\go-app-stager.exe C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\main\app.y
aml C:\Users\Jimmy\Desktop\GotoX-gae-r6-c2\main C:\Users\Jimmy\AppData\Local\Temp\tmpkpma0u1z\tmplo8
gc9ka] failed with return code [1].

------------------------------------ STDOUT ------------------------------------
------------------------------------ STDERR ------------------------------------
2021/07/07 11:24:11 staging for go1.11
2021/07/07 11:24:11 GO111MODULE=auto, but no go.mod found, so building with dependencies from GOPATH

2021/07/07 11:24:11 Staging second-gen Standard app (GOPATH mode): failed analyzing C:\Users\Jimmy\D
esktop\GotoX-gae-r6-c2\main: the root of your app needs to be package "main" (currently "gae")
GOPATH: C:\Users\Jimmy\go
--------------------------------------------------------------------------------

**本人是代码小白，不知道如何处理。
如能解决，不胜感激。**

**Comment by SeaHOH** [comment]
代码方面可以参考 https://github.com/Quantum2Bits/GotoX/pull/1 ，但并不保证是可用的。
上传请使用 gcloud SDK，官方文档有详细介绍。

**Comment by SeaHOH** [comment]
你可以把需要访问的站点贴出来，我可以帮忙看看是否能伪造 SNI 来直连。

**Comment by 3061732350** [comment]
嗨~我成功通过伪造SNI的方式来直连该网站。
谢谢大佬的指教。
