### ISSUE TITLE
每次启动都会报错误

### ISSUE THREAD

**Issue by leafsnow** [SeaHOH/GotoX#192]
![error](https://user-images.githubusercontent.com/6291246/125886943-c7d1c778-f131-4131-b203-f4414adb957c.png)

**Comment by SeaHOH** [comment]
无法复现，如果方便请提供完整的配置和日志。

另外，如果你设置了系统 DNS 估计就不会出现这个问题。

**Comment by leafsnow** [comment]
请问大佬，是还需要把DNS设置成127.0.0.1吗？

**Comment by leafsnow** [comment]
[log.txt](https://github.com/SeaHOH/GotoX/files/6829324/log.txt)
大佬，这里是日志。

**Comment by SeaHOH** [comment]
> 是还需要把DNS设置成127.0.0.1吗？

你本地有服务器吗？有就可以设置。

另外，看日志好像已经能正常使用了？

**Comment by leafsnow** [comment]
谢谢大佬回复。还是访问不了syosetu 、p站。

**Comment by leafsnow** [comment]
谢谢大佬回复。OK了，原来是我的switchOmega导致的，之前用岛风go配置了一个，切换成系统代理就OK了。
