### ISSUE TITLE
google.cn访问时报错：谷歌域名没有获取到正确的证书链：CA 公钥不匹配

### ISSUE THREAD

**Issue by chen2021-web** [SeaHOH/GotoX#197]
请问要怎么解决

**Comment by chen2021-web** [comment]
错误日志：203.208.41.98 _create_ssl_connection 'www.google.cn' 返回 CertificateError(-1, '谷歌域名没有获取到正确的证书链：CA 公钥不匹配。')，重试
21:47:57 W 203.208.41.34 create_ssl_connection 'https://www.google.cn/chrome/' 失败：CertificateError(-1, '谷歌域名没有获取到正确的证书链：CA 公钥不匹配。')
21:47:57 W 203.208.40.98 _create_ssl_connection 'www.google.cn' 返回 CertificateError(-1, '谷歌域名没有获取到正确的证书链：CA 公钥不匹配。')，重试

**Comment by chen2021-web** [comment]
只要访问google域名就会出现这个问题

**Comment by SeaHOH** [comment]
已经修复了，但是出了点问题还没发布新版，你可以直接下载源码更新。

**Comment by SeaHOH** [comment]
终于找到原因搞定了。

**Comment by gxggsrmyy** [comment]
Exception ignored in thread started by: <bound method HTTPUtil._create_ssl_connection of <local.HTTPUtil.HTTPUtil object at 0x03ECE6E8>>
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\GotoX-master (2)\GotoX-master\local\HTTPUtil.py", line 745, in _create_ssl_connection
    self.google_verify(ssl_sock)
  File "C:\Users\Administrator\Downloads\GotoX-master (2)\GotoX-master\local\HTTPUtil.py", line 480, in google_verify
    raise CertificateError(-1, '%s 证书的组织名称（%s）不属于 %s 之一。' % (sock.getpeername[0], subject.O, GoogleONames))
TypeError: 'builtin_function_or_method' object is not subscriptable

**Comment by gxggsrmyy** [comment]
@SeaHOH 证书问题还没解决

**Comment by SeaHOH** [comment]
谢谢提醒，这下好了。不过建议平时不要使用这个只检测名称的设置。

**Comment by gxggsrmyy** [comment]
19:06:41 I L4:57200->120.253.255.34 "FWD CONNECT google.cn:443 HTTP/1.1" - -
19:06:41 W 120.253.255.34 _create_ssl_connection 'www.google.cn' 返回 CertificateError(-1, "('120.253.255.34', 443) 证书的组织名称（None）不属于 {'Google LLC', 'Google Trust Services LLC'} 之一。")，重试
19:06:42 W 120.253.253.34 create_ssl_connection 'https://www.google.cn/' 失败：CertificateError(-1, "('120.253.253.34', 443) 证书的组织名称（None）不属于 {'Google LLC', 'Google Trust Services LLC'} 之一。")

**Comment by gxggsrmyy** [comment]
@SeaHOH 只是访问google.cn

**Comment by gxggsrmyy** [comment]
19:06:21 W 检查和导入证书时发生错误：OSError('exception: access violation reading 0x0000000071211380')
如果没有导入过证书，请手动操作，否则请忽视这条警告。
19:06:21 W 检查和导入证书时发生错误：OSError('exception: access violation reading 0x0000000071211EE0')
如果没有导入过证书，请手动操作，否则请忽视这条警告。
19:06:21 W install root certificate failed, Please run as administrator/root/sudo

**Comment by gxggsrmyy** [comment]
还有这个错误

**Comment by SeaHOH** [comment]
> 19:06:42 W 120.253.253.34 create_ssl_connection 'https://www.google.cn/' 失败：CertificateError(-1, "('120.253.253.34', 443) 证书的组织名称（None）不属于 {'Google LLC', 'Google Trust Services LLC'} 之一。")

你是不是修改过`[picker/servername]`设置？删除可恢复默认值。

> 如果没有导入过证书，请手动操作，否则请忽视这条警告。

就是这样，我没有能力全适配，权做提醒，以防有用户忘记导入证书。

**Comment by gxggsrmyy** [comment]
也是通过你们 的这些项目才第一次接触到python ,之前完全不懂, 现在也是懂一些皮毛, 没有系统学习, 不会调试 @SeaHOH
