### ISSUE TITLE
CFW 无法连接 WinError 10051

### ISSUE THREAD

**Issue by loveinlastnight** [SeaHOH/GotoX#201]
xxxxxxxxxx.workers.dev' 返回 OSError(10051, '[WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。')，重试

最近一个月出现的，这该怎么办呢？

**Comment by SeaHOH** [comment]
麻烦把这行日志前面到 IP 贴出，怀疑是域名解析的问题。

**Comment by loveinlastnight** [comment]
可能是吧，刚才直接删除了DATA文件夹。重启GOTOX，好了。。。

**Comment by loveinlastnight** [comment]
明白，IP.txt复制过来了。其他的2个文件直接更新的。
