### ISSUE TITLE
请问大佬可以反代实现steam论坛访问吗？

### ISSUE THREAD

**Issue by leafsnow** [SeaHOH/GotoX#205]
https://steamcommunity.com/

**Comment by SeaHOH** [comment]
为什么要反代呢，客户端不能设置代理吗？
这个工具可以设置成反代 (监听 443)，但没有专门优化反代体验。Adnroid App 肯定不行，Windows 客户端估计可以使用导入系统的证书。

**Comment by 2378** [comment]
这不是反不反代的问题。
steam的策略就这样，单一IP账号一多直接封，什么加速器、VPN被封的多了
原因无外乎，打击黑产灰产，保证游戏公平，维护区域销售，等等
用自己的VPS上没有任何问题

**Comment by SeaHOH** [comment]
主要看个人需求。
对延迟要求高当然不能用我这个工具搞，如楼上所言建议自己搞一个适合的 VPS 开 VPN，个位数的账号@单 IP 估计问题不大。
如果不在乎加速是可以本地直连的，UDP 不论延迟但基本是畅通的，HTTP 也无需通过远程代理。
问题是，为了 HTTP 直连个别域名 (比如 community 主域名) 中间人要修改 SNI，并使用自签证书中继连接。

**Comment by 2378** [comment]
@SeaHOH 海大，隔壁可炸锅了，GAE没绑卡的ID全军覆没，这次狼是真来了 :worried:

**Comment by SeaHOH** [comment]
搞不懂非要用 GAE 的道理，那么多公共 ID，怎么可能全部都绑上，要用只好绑自己的，何苦呢。

**Comment by 2378** [comment]
反正两年前就停用GAE了，但看着有人屁颠屁颠的 把自己的卡号电话奉上，心中一阵感慨，不知是福是祸啊 :cold_sweat:

**Comment by gxggsrmyy** [comment]
@SeaHOH 
Traceback (most recent call last):
  File "D:\GotoX-master (4)\GotoX-master\local\ProxyHandler.py", line 822, in do_GAE
    response = gae_urlfetch(self.command, self.url, request_headers, payload)
  File "D:\GotoX-master (4)\GotoX-master\local\GAEFetch.py", line 237, in gae_urlfetch
    _response = _gae_urlfetch(response.appid, payload, getfast, method, realurl)
  File "D:\GotoX-master (4)\GotoX-master\local\GAEFetch.py", line 252, in _gae_urlfetch
    'Content-Length': str(length)
NameError: name 'length' is not defined

**Comment by SeaHOH** [comment]
@gxggsrmyy 实际上我没检查过，请等一会。

**Comment by gxggsrmyy** [comment]
不是说gae不再更新维护了吗，GAEFetch.py 的改动是什么原因

**Comment by gxggsrmyy** [comment]
@SeaHOH  连接数达到限制会有［LimiterFull］警告，可以参考出现频率来调整值，能不能做动态调高连接？

**Comment by SeaHOH** [comment]
> 不是说gae不再更新维护了吗，GAEFetch.py 的改动是什么原因

顺手，统一作相同处理。这不是功能性维护，只是兼容新代码。

> 连接数达到限制会有［LimiterFull］警告，可以参考出现频率来调整值，能不能做动态调高连接？

动态就失去了限制的意义，你可以手动调整设置参数。

**Comment by SeaHOH** [comment]
> @gxggsrmyy 实际上我没检查过，请等一会。

已经修复完成。你还在使用 GAE 吗，速度是不是比 CFW 快很多？

**Comment by gxggsrmyy** [comment]
@SeaHOH 速度还是cfw 快，但我觉得gae 比vps 要好，vps 很容易被封ip, gae 个人用费用也是很低的，我自己没有编程能力，只能大概看懂 if else 什么意思，受益你的付出，gotox 是个很好的项目，只是别人不懂欣赏，被低估了，不过小众一点也好，免得树大招风。

**Comment by SeaHOH** [comment]
@gxggsrmyy 哈哈，谢谢夸奖。我以前不宣传是因为水平有限，现在有了些进步，但是心态比以前放得更平了。毕竟各种好用的工具也挺多，GotoX 应用范围有局限，大家用适合自己的就好。

**Comment by gxggsrmyy** [comment]
@SeaHOH gotox 无人值守部署在路由器上，经常LimiterFull 就卡住了，所以设想如果能自动调节连接数就好了，

**Comment by SeaHOH** [comment]
> gotox 无人值守部署在路由器上，经常LimiterFull 就卡住了，所以设想如果能自动调节连接数就好了，

是 GAE 卡住，还是普通连接卡住？

前者你直接修改以下代码 `_response =` 为`return`，这个修改不会添加到项目中。
https://github.com/SeaHOH/GotoX/blob/79b44e398578c1846629eab0e9538af782fac999/local/GAEFetch.py#L237

后者的话，如果你愿意帮忙测试，我可以把你调试得到的最大值添加到项目中。这个数值在下面 32 的位置。
https://github.com/SeaHOH/GotoX/blob/79b44e398578c1846629eab0e9538af782fac999/local/GlobalConfig.py#L91

**Comment by gxggsrmyy** [comment]
@SeaHOH 是 GAE 卡住，还是普通连接卡住？两种情况都有.
前者你直接修改以下代码 _response = 为return , 是什么意思, 是下面这样吗, 好象不对.
    realurl = 'GAE-' + url
    response = LimitGAE()
   # _response = _gae_urlfetch(response.appid, payload, getfast, method, realurl, length)
    return
    return response(_response)

我可以把你调试得到的最大值添加到项目中。我要怎么调试? 更改32的值, 怎样才算是得到最大值.

**Comment by gxggsrmyy** [comment]
@SeaHOH 是 GAE 卡住，还是普通连接卡住？两种情况都有.
前者你直接修改以下代码 _response = 为return , 是什么意思, 是下面这样吗, 好象不对.
realurl = 'GAE-' + url
response = LimitGAE()

return
return response(_response)
我可以把你调试得到的最大值添加到项目中。我要怎么调试? 更改32的值, 怎样才算是得到最大值.

**Comment by SeaHOH** [comment]
> 前者你直接修改以下代码 _response = 为return , 是什么意思

就是把`_gae_urlfetch`前面的`_response =`换成`return`。
你不想修改源码的话，也可以先试试配置文件 [gae/maxperip] 参数到最大值 8，如果还不符合你的使用环境再改源码。

> 我要怎么调试? 更改32的值, 怎样才算是得到最大值.

把 32 改成一个更大的数值 (如 100)，然后修改配置文件 [link/maxperip] 参数 (默认是 6)，你可以按一定数值增加它 (如 +10)，增加一次就重启运行一段时间，如果达到不再卡住只是偶尔出现 LimiterFull 提示，那么这个参数数值就比较合适。
我认为这个数值是不太可能超出 32 的。

**Comment by gxggsrmyy** [comment]
@SeaHOH 就是把_gae_urlfetch前面的_response =换成return。response = LimitGAE()可以前面加个#注释掉。好象没有那么简单, 改了之后又引入了新的故障, 提示 response 未定义, 不管怎样, 现状已经很好了, 很感谢你的热心帮助, 为了不必要的麻烦, 我把发过的帖删除, 望见谅.

**Comment by gxggsrmyy** [comment]
@SeaHOH  google . cloudflare 这些大佬有海量的ip  ,才是最强的,  才是最难封的, 是其他vps 无法比的优势, 原来用的goproxy 版的gae 服务端因为版本太低已经不能部署, 现在用的是xx-net 的python 2 的服务端,  xx-net 的服务端能不能升级到python 3 ,python 2不知google 还支持多久, 不能用了就可惜了, 我个人认为你低估了google gae 的价值,

**Comment by gxggsrmyy** [comment]
@SeaHOH google . cloudflare 这些大佬有海量的ip ,才是最强的, 才是最难封的, 是其他vps 单个ip 容易被封, 无法比的优势, 原来用的goproxy 版的gae 服务端因为版本太低已经不能部署, 现在用的是xx-net 的python 2 的服务端, xx-net 的服务端能不能升级到python 3 ,python 2不知google 还支持多久, 不能用了就可惜了, 我个人认为你低估了google gae 的价值,

**Comment by SeaHOH** [comment]
> `response = LimitGAE()`可以前面加个`#`注释掉。

忘了后面还有引用，实际上不需要注释掉。

我不再使用 GAE 主因是隐私，毕竟其它网站可以使用代理，但是代理本身还是要直连的，我一般不搞多重跳板。

**Comment by gxggsrmyy** [comment]
@SeaHOH 是这样吗，好象不行
    realurl = 'GAE-' + url
    response = LimitGAE()
    return _gae_urlfetch(response.appid, payload, getfast, method, realurl, length)
    return response(_response)

**Comment by SeaHOH** [comment]
> @SeaHOH 是这样吗，好象不行
> realurl = 'GAE-' + url
> response = LimitGAE()
> return _gae_urlfetch(response.appid, payload, getfast, method, realurl, length)
> return response(_response)

加一行`response.close()`到`response = LimitGAE()`后面。

直接设置 [gae/maxperip] 参数到 8 也会卡吗？
