### ISSUE TITLE
cloudflare转发失效

### ISSUE THREAD

**Issue by ksi1110** [SeaHOH/GotoX#207]
31日起，代理转发开始失效，更新到了最新3.8.5，部署后依旧失效，重新删除证书安装证书，重新部署回3.8.3，仍然不能正常工作。
问题现象：打开代理后，无法连接网页，提示证书失效，主机名称不能匹配
截取一小段日志如下：
10:29:44 W 2606:4700::6810:859a create_ssl_connection 'CFW-https://go.microsoft.com/fwlink/?LinkId=832372&clcid=0x804'  失败：Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])
10:29:44 W 104.16.133.202 _create_ssl_connection 'https://broken-shape-9295.ksi1110.workers.dev/' 返回 Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])，重试
10:29:46 W 104.16.133.2 create_ssl_connection 'CFW-https://go.microsoft.com/fwlink/?LinkId=832372&clcid=0x804' 失败：CertificateError(-1, "hostname 'https://broken-shape-9295.ksi1110.workers.dev/' doesn't match either of 'dev.si.v1.pull-ups.com', 'dev.origin.si.v1.pull-ups.com', 'dev1.si.v1.pull-ups.com', 'server1.dev1.si.v1.pull-ups.com', 'server1.tcceast.dev1.si.v1.pull-ups.com', 'server1.tccwest.dev1.si.v1.pull-ups.com', 'server2.dev1.si.v1.pull-ups.com', 'server2.tcceast.dev1.si.v1.pull-ups.com', 'server2.tccwest.dev1.si.v1.pull-ups.com', 'tcceast.dev1.si.v1.pull-ups.com', 'tccwest.dev1.si.v1.pull-ups.com'")
10:29:46 W 104.16.132.235 _create_ssl_connection 'https://broken-shape-9295.ksi1110.workers.dev/' 返回 CertificateError(-1, "hostname 'https://broken-shape-9295.ksi1110.workers.dev/' doesn't match '*.pedroshoes.com'")，重试
10:29:47 W 2606:4700::6810:8461 create_ssl_connection 'CFW-https://go.microsoft.com/fwlink/?LinkId=832372&clcid=0x804'  失败：CertificateError(-1, "hostname 'https://broken-shape-9295.ksi1110.workers.dev/' doesn't match either of 'sni.cloudflaressl.com', 'images.kw.com'")

其他诸如谷歌网页可以打开，但检索某些页面时不能载入，就会报错，youtube可以打开，但视频不能载入。

**Comment by SeaHOH** [comment]
你是否修改过配置？建议重新下载解压到另外的位置，不会影响你原本的配置，用默认配置重试 (只配置一个 worker 域名)，重试时要把原先的退出。

**Comment by ksi1110** [comment]
> 你是否修改过配置？建议重新下载解压到另外的位置，不会影响你原本的配置，用默认配置重试 (只配置一个 worker 域名)，重试时要把原先的退出。

了解，我重新部署一下

**Comment by ksi1110** [comment]
> > 配置文件是默认的，只加了一个worker
> 
> 你填写的什么，不会是 `https://*.*.workers.dev/` 吧？这里应该填域名 `*.*.workers.dev`，不是链接。

晕晕晕 乌龙了  可能和旁路由里面代理冲突了  去掉后就正常了 十分感谢解答^_^
