### ISSUE TITLE
有個關於 ipex.txt 的問題想請教

### ISSUE THREAD

**Issue by caofengzi** [SeaHOH/GotoX#21]
老大說的data/ipex.txt是自己新建一個嗎？

**Comment by SeaHOH** [comment]
这个 `ipex.txt` 文件需要自己建立，建立时间两小时后会被删除。
如果它包含了稳定性较佳的 IP，这些 IP 会保存在统计记录中，当 IP 无法稳定使用后会被丢弃。
如果你想长期使用这些 IP，那么需要**同时**将这些 IP 加入 `ip.txt` 文件。

**Comment by caofengzi** [comment]
謝謝，俺沒有新建ipex而是把ip放入ip.txt裡面了。

**Comment by SeaHOH** [comment]
你用的什么系统，Windows？剩下几个 python.exe 进程？
窗口还在不，有没有显示什么信息？
你是从托盘工具退出的还是直接关闭窗口？请都尝试一下。

**Comment by caofengzi** [comment]
俺用的是win7，剩下一個pyton.exe進程，俺每次都是在系統托盤關閉程序的。
![2017-04-19_151318](https://cloud.githubusercontent.com/assets/13650252/25167349/b807259c-2511-11e7-8987-f1fa698fa36d.png)

**Comment by SeaHOH** [comment]
无法复现，直接关闭窗口呢？

**Comment by caofengzi** [comment]
直接關閉窗口沒有pyton進程了。

**Comment by SeaHOH** [comment]
这个情况不好说，我暂时无法解决，因为用的 `sys.exit(0)` 退出，照道理是直接关闭了。
不知道你用的 Python 是否是我发布的便携版？
如果你要使用 GotoX，暂时忍耐下，关闭时就直接关窗口吧。

**Comment by caofengzi** [comment]
使用的是你發佈的便攜版。

**Comment by SeaHOH** [comment]
好久没看过 issues，忘了说了。现在点击托盘菜单应该可以完美退出了。
