### ISSUE TITLE
WIN10升级后，套接字方式有改变

### ISSUE THREAD

**Issue by 2378** [SeaHOH/GotoX#215]
涉及所有版本，370~386 ，微软作妖啊 :fearful:

![2](https://user-images.githubusercontent.com/24506320/147540993-030eccd7-7c9d-4395-af97-5a037fdc8d4d.PNG)

**Comment by SeaHOH** [comment]
你这个是端口被占用了，重启一次估计就好了。或者也可能是低位端口被设为保留状态，把端口配置成更大的数字就可以避开。

**Comment by 2378** [comment]
问题已解决，同时无法复现，判断是端口占用问题

机器上 一个virtualbox 两个hyperv  ，应该是重启时未能及时清空，系统重启无效，重启hyperv恢复。

目测win10升级后对16384以内的端口调用更严格，未深入研究。
