### ISSUE TITLE
Youtube / Google 直链404

### ISSUE THREAD

**Issue by robinlighting** [SeaHOH/GotoX#218]
昨天还好好的，今天就不行了，出现一片一片都404。
![QQ截图20220213004400](https://user-images.githubusercontent.com/39740368/153720227-e6160741-3439-4ece-88ce-e1fbcc87c9c5.jpg)

**Comment by SeaHOH** [comment]
请检查确保有使用以下配置，否则可能是你的接入网络有变化，重启 GotoX 看看是否有网络不可用提示。
```ini
[link]
profile = ipv46

[picker/gws]
enable = 1
```

**Comment by robinlighting** [comment]
[link]
profile = ipv46

[picker/gws]
enable = 1

刚刚查看了config，是这些设置。

**Comment by SeaHOH** [comment]
否则。。。？

**Comment by SeaHOH** [comment]
@performcanhe 同样的问题，你的 IPv6 似乎挂了。

**Comment by SeaHOH** [comment]
检查你的网络，IPv4 从 11 号下午就封了，现在需要使用 IPv6 来连接。

**Comment by robinlighting** [comment]
> 检查你的网络，IPv4 从 11 号下午就封了 (也不清楚是谁封的，懒得验证)，现在需要使用 IPv6 来连接。

不知道怎么私信你，所以在这里回复。

今天直链恢复了。
