### ISSUE TITLE
hostname 'xxx' doesn't match either of 'yyy', 'yyy'

### ISSUE THREAD

**Issue by jdjdlxq** [SeaHOH/GotoX#236]
目前在访问dlsite的时候出现这个问题
hostname 'www.dlsite.com' doesn't match either of 'quantil.com', 'www.quantil.com'
我在本地host里添加了https://cssxsh-github-io.pages.dev 中的所有内容

**Comment by SeaHOH** [comment]
> 我在本地host里添加了https://cssxsh-github-io.pages.dev 中的所有内容

我这里测试，GotoX 默认配置可以直接访问 dlsite，只有 DNS 污染。
因此判断是内容过时了，建议移除或从其它渠道更新。

**Comment by jdjdlxq** [comment]
> 
host我已经清理掉dlsite相关的ip了
dns污染 可以用gotox解决吗？需要进行怎样的配置呢？

**Comment by SeaHOH** [comment]
> dns污染 可以用gotox解决吗？需要进行怎样的配置呢？


> GotoX 默认配置可以直接访问 dlsite
