### ISSUE TITLE
cloudflare tunnel 映射gotox端口

### ISSUE THREAD

**Issue by hg123** [SeaHOH/GotoX#245]
cloudflare tunnel能做端口映射 不知道能不能将内网的gotox 映射出去供外网使用？
烦请大神解答一下小白的疑惑，谢谢了。

**Comment by SeaHOH** [comment]
类似于 frp，绝大多数服务都可以正常运行。网上有许多教程，照着做就行。
不过 GotoX 本身也只是个本地代理，没必要挂到外网多绕一圈。

**Comment by hg123** [comment]
同一个局域网内手机可以通过PC上的gotox翻墙，但当我在外部网络时也想通过这台PC上的gotox翻墙，我知道在路由器上做好端口映射是可以，但有的路由器没有权限无法做到映射，所以想问一下能否通过tunnel做映射。

**Comment by hg123** [comment]
我用tunnel 成功映射了本地端口 但无法使用本地的gotox的服务

**Comment by SeaHOH** [comment]
检查下你的步骤是否正确，可以映射个其它的服务来测试。
使用 HTTPS 连接代理，最新的浏览器都支持，毕竟是代理，你明文的话可能会有问题。
还有，GotoX 端口监听设置可以留空，以免不匹配。

最后，还是建议不要这么用，太折腾了，你手机直接运行也是可以的，虽然用处不大。

**Comment by hg123** [comment]
明白了，谢谢解答
