### ISSUE TITLE
overhttpsserver及untrusted CA

### ISSUE THREAD

**Issue by jdjdlxq** [SeaHOH/GotoX#252]
一、Config.ini 里 overhttpsservers 保持默认时提示
```
16:33:15 W 162.159.36.1 _create_ssl_connection 'cloudflare-dns.com' 返回 TimeoutError('timed out')，重试
16:33:15 W 1.0.0.1 _create_ssl_connection 'cloudflare-dns.com' 返回 TimeoutError('timed out')，重试
```
`overhttpsservers = 1.1.1.1`  这样配置也是提示
```
16:34:03 W 162.159.132.53 _create_ssl_connection '1.1.1.1' 返回 TimeoutError('timed out')，重试
16:34:03 W 162.159.36.1 _create_ssl_connection '1.1.1.1' 返回 TimeoutError('timed out')，重试
```
有办法让这个能用吗？
或者有其它能用的服务器吗？

二、（附带的问题） 这个是需要处理的错误吗？如果是，该怎么做？
`16:34:10 W [picker gws] 3 测试失败（超时：2000 ms）159.12.192.14，(-1, ('untrusted CA, issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA', 1))`

**Comment by SeaHOH** [comment]
自从 DoH 开始大规模被干扰，我也很久没用过了。
现在是用的 UDP 查询，偶尔会得到污染结果，遇到这种情况，通常重置 DNS 缓存即可。

至于谷歌，我这里已经完全没法直连，无法调试。不过，你观察到的这个错误日志不用特别处理。
