### ISSUE TITLE
部分网站兼容有问题

### ISSUE THREAD

**Issue by waiting4new** [SeaHOH/GotoX#262]
如访问pixiv，显示以下错误信息：
Ray ID: 7c3fadd80079048d
Timestamp: 2023-05-08 06:34:48 UTC
Your IP address: 2a06:98c0:3600::103
Requested URL: www.pixiv.net/
Error reference number: 1020
Server ID: FL_582F76
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
另外在speedtest网站中也总是以ipv6连接，在这里问一下需要更改哪些设置使得总是优先v4连接

**Comment by SeaHOH** [comment]
是的 CFW 无法代理 pixiv，我使用如下规则：
```ini
# xx 为规则匹配序数
[xx-fakecert]
pixiv.net$ = pixiv.me
.pximg.net = pximg.net

[xx-direct]
.pixiv.net = pixiv.net
.pximg.net = pximg.net
```

**Comment by SeaHOH** [comment]
当前不支持优先使用 IPv4 或 IPv6，只能选择其中一种。
设置方法有两种：
```ini
# 主配置，作用于全局，不建议使用
[link]
profile = ipv46
```
```ini
# 自动规则，灵活配置，实时应用修改
[xx-direct]
hostname.xxx = @v4
```

**Comment by waiting4new** [comment]
好的谢谢解答
