### ISSUE TITLE
SSL_session_reused函数已不存在

### ISSUE THREAD

**Issue by debugger-zhang** [SeaHOH/GotoX#271]
参见 https://github.com/pyca/cryptography/commit/5d475502b31845c9b735495120313b511e86b4f7

但是 https://github.com/SeaHOH/GotoX/blob/master/local/compat/openssl.py#L81 还在使用这个函数，所以把pyopenssl更新到最新版本就会报错module 'lib' has no attribute 'SSL_session_reused'。

（PS：如果不更新pyopenssl有可能会出现这个问题： https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check ，[README.md](https://github.com/SeaHOH/GotoX/blob/master/README.md)里面应该说要求22.0.0以上版本）

**Comment by SeaHOH** [comment]
这个 API 只是保留在那里，但是并没有调用它。如果你遇到了 attribute 错误，请更新。
