### ISSUE TITLE
反馈：某dll文件丢失

### ISSUE THREAD

**Issue by Alvin9999** [SeaHOH/GotoX#28]
使用GotoX-3.3.6的32位和64位，都出现此问题，造成软件无法使用
![default](https://cloud.githubusercontent.com/assets/12132898/25470240/e8c4c7f0-2b53-11e7-94c7-09b994ed11b6.PNG)

**Comment by caofengzi** [comment]
搜索一下system32文件夾裡面是否有這個dll文件，俺這裡有。

**Comment by Alvin9999** [comment]
有的
![default](https://cloud.githubusercontent.com/assets/12132898/25472409/bb8c7616-2b5d-11e7-88c9-191a31c890d5.PNG)

**Comment by zdzliqian** [comment]
我也是 用的是windows便捷版 怎么办

**Comment by jzp820927** [comment]
VC 运行库，估计你们装的系统是精简版吧？或者 ghost 版？

**Comment by Alvin9999** [comment]
@jzp820927  重新装了个VC库，可以用了。

**Comment by Alvin9999** [comment]
反馈一下：我用GoAgent和GotoX分别做了测试，同样的appid，ip，以及视频。GotoX中的ip我是放在date文件夹里面的ip.txt里面。测试结果：GotoX速度明显不如GoAgent，这里的速度指的是播放YouTube时的速度。

如下图：
GoAgent：
![1](https://cloud.githubusercontent.com/assets/12132898/25480668/482b4b38-2b7c-11e7-8f48-e5799214fe71.PNG)

GotoX：
![2](https://cloud.githubusercontent.com/assets/12132898/25480674/52b97b38-2b7c-11e7-9588-5a84f8b9a0ca.PNG)

**Comment by jzp820927** [comment]
好像是差一大截，不明觉厉。是不是同时播放的？

**Comment by Alvin9999** [comment]
没法同时播放，因为都是GAE类软件。但我是测试了几次，都是这样，GotoX上不到2000kbps

**Comment by jzp820927** [comment]
好吧，等 repo 主确认。

**Comment by SeaHOH** [comment]
涉及到视频下载，请调节 autorange 参数，配置文件注释有详述。

**Comment by SeaHOH** [comment]
@Alvin9999 
对了，由于 GotoX 定位折腾，没有特别采取措施保证任意参数设置下正常运行；一旦设置不合适，普通用户很可能无法自行调试解决；所以不适合傻瓜化整合包，你的项目完全不用考虑使用 GotoX。

**Comment by SeaHOH** [comment]
关于速度的问题，可以继续在这里https://github.com/SeaHOH/GotoX/issues/29#issuecomment-297918800 讨论。
