### ISSUE TITLE
大文件下载出错

### ISSUE THREAD

**Issue by SeaHOH** [SeaHOH/GotoX#33]
问题见：https://github.com/SeaHOH/GotoX/issues/31#issuecomment-306444151

**Comment by SeaHOH** [comment]
怀疑只是 GAE fetch 的 32MB 大小限制导致，尝试用 autorange 功能进行兼容修复，顺带加入根据响应内容大小启用 autorange 的特性。

@caofengzi 
麻烦尝试下这个分支，看看你遇到的问题是否也是这个原因。
https://github.com/SeaHOH/GotoX/tree/dev-autorange

**Comment by caofengzi** [comment]
明天俺在github找一個40多m的文件測試一下。謝謝，辛苦了。

**Comment by caofengzi** [comment]
@SeaHOH 發佈正式版吧，下載github大文件問題以解決了。

**Comment by SeaHOH** [comment]
好的，谢谢。再修改些小细节就发。

**Comment by SeaHOH** [comment]
@caofengzi 
正式版已发布，针对这个问题有较多修改。
刚才 NoScript 把我耍惨了，Github 老是改代码，好半天才发现上传出错的原因。

**Comment by caofengzi** [comment]
@SeaHOH 謝謝，goa有傳承了。哈哈

**Comment by Melody713** [comment]
海大太棒了!终于可以愉快的下载了!赞美你!

**Comment by SeaHOH** [comment]
@Melody713 
谢谢捧场 :smile_cat:
