### ISSUE TITLE
ConnectionRefusedError(10061, '[WinError 10061] 

### ISSUE THREAD

**Issue by ivysrono** [SeaHOH/GotoX#36]
3.3.7
访问：
https://p1.music.126.net/5QxEuxegyf6w6A8xaH4fwA==/18732379604094419.jpg
连续报错。
```
L4:52295->223.252.216.52 转发到 'p1.music.126.net' 失败：ConnectionRefusedError(10061, '[WinError 10061] 由于目标计算机积极拒绝，无法连接。')
```
如果直连，可以正常访问，飞快。

如下设置无用：
```
[link]
tempwhitelist = p1.music.126.net | www.lkong.net
```

**Comment by SeaHOH** [comment]
这个错误说明就是直接转发的，并没有使用到其它后端代理。
我这里用 Pale Moon 是正常访问的，不知道你使用的浏览器是什么？
`17:19:56 I L4:51979->182.140.130.23 "FWD CONNECT p1.music.126.net:443 HTTP/1.1" - -`

或者尝试是否 IP 原因，我这里这个 IP 正常连接。
```ini
#ActionFilter.ini
[序数-forward]
p1.music.126.net = 182.140.130.23
```

**Comment by SeaHOH** [comment]
可能真是 IP 问题，我用 `223.252.216.52` 来链接也出现了你这个错误。
是不是你的 DNS 不合适？

**Comment by ivysrono** [comment]
还真是DNS的问题，我设置了 priority = overhttps|system|remote

**Comment by SeaHOH** [comment]
`overhttps` 一般备用好些，毕竟响应可能会很慢，而且不会绝对准确。
我这里 `overhttps` 的结果就不是最优，虽说和最优 IP 比也慢不了几十毫秒。

**Comment by ivysrono** [comment]
本来我以为这点速度差距可以忽略，只要能准确安全可以接受这点代价。
被教育了……
话说如果 overhttps 只用于被墙站点，也会有这种问题么？

**Comment by SeaHOH** [comment]
嗯，谈不上教育。
我的日常方案是：
* 系统 DNS 用 Pcap_DNSProxy 之类的防污染。
* GotoX 的 `[dns/priority] = system|overhttps|remote`，这个只在特殊情况下才调整。

>话说如果 overhttps 只用于被墙站点，也会有这种问题么？

我就是不想用 gfwlist 才改的这个 GotoX 啊，所有不会有这种功能。

**Comment by ivysrono** [comment]
有道理，还是各司其职比较好。
谢谢。

**Comment by SeaHOH** [comment]
不客气，有人用我就很高兴了。

**Comment by ivysrono** [comment]
回头看，#32 可能也是我乱改DNS造成的……

**Comment by SeaHOH** [comment]
没问题，这个功能可以有，避免有些 IP 不在国内的网站误走 GAE，尤其是现在前几天新法生效的情况下。
