### ISSUE TITLE
请教个问题，鼠标手势 + MPV + youtube-dl 怎么通用gotox 使用

### ISSUE THREAD

**Issue by gxggsrmyy** [SeaHOH/GotoX#37]
因为看到大海兄推荐过几回 鼠标手势 + MPV + youtube-dl ,试用了一下，现在的问题是gotox 是要伪造证书的，如果是浏览器可以倒入证书来使用，但MPV + youtube-dl怎么样倒入证书呢，shadowsocks 不用倒入证书，MPV + youtube-dl 可以通过shadowsocks 访问网络，现在的问题是MPV + youtube-dl 怎么样通过gotox 访问网络呢，证书怎么处理。

**Comment by gxggsrmyy** [comment]
@SeaHOH

**Comment by SeaHOH** [comment]
youtube-dl 默认会使用系统证书，导入系统就好。下面是代理设置。
```ini
#mpv.conf
#MPV 设置我一般停用 youtube-dl，鼠标调用时添加“--ytdl”参数
ytdl=no
ytdl-raw-options='"sub-lang"="zh-Hans,zh-Hant,ja,en","proxy"="HTTP://127.0.0.1:8087"'
```

**Comment by SeaHOH** [comment]
对了，MPV 还需要设置环境变量。你也可以把这个变量想办法在调用 MPV 时加入，或者用 bat 脚本。
http_proxy: http://127.0.0.1:8087

**Comment by gxggsrmyy** [comment]
@SeaHOH  可以播放了，另一个问题，鼠标手势 具体是什么，怎么使用，能说具体点吗

**Comment by gxggsrmyy** [comment]
鼠标手势 是chrome 的一个插件，还是一个程序

**Comment by SeaHOH** [comment]
都可以，不过插件可以直接获取链接地址，单独的手势程序还需要一个链接的传递过程，比如先复制链接。
我用是火狐 FireGestures，搜了一下 Chrome 还是有不少的类似插件的，你选一款支持调用其它程序的手势插件就好。

**Comment by jzp820927** [comment]
@SeaHOH 刚刚又给你回了邮件，你去看看

**Comment by puowasb** [comment]
@SeaHOH 

你这傻逼,居然给五毛点赞,简直是渣滓.
![1](https://user-images.githubusercontent.com/29521696/27262035-66d8a5b6-5481-11e7-9ffe-9fbde04140f3.png)

**Comment by SeaHOH** [comment]
@puowasb 
如果你继续侮辱行为，我会屏蔽你。
