### ISSUE TITLE
IP在gop正常使用在gotox使用变成404 及乱码

### ISSUE THREAD

**Issue by wpyok500** [SeaHOH/GotoX#41]
![image](https://user-images.githubusercontent.com/14154547/29213240-00f0aacc-7ed5-11e7-85ca-a26dc29461c2.png)
![image](https://user-images.githubusercontent.com/14154547/29214685-dc7627a2-7eda-11e7-9bf8-1749db447d29.png)

**Comment by SeaHOH** [comment]
请问，除了 `ip.txt` 你还修改了哪些配置？

**Comment by SeaHOH** [comment]
能否把启动时的日志贴上来？`debuginfo` 设置为 2。

**Comment by wpyok500** [comment]
config.ini无做任何修改，只在Config.user.ini配置了appid

**Comment by SeaHOH** [comment]
你的 GoProxy 开了 quic ？

还有，首次使用时，你不能启动后马上就用，这时可能还没有筛选出质量较好的 IP，建议等 2 至 5 分钟。
如果这样还不行，请调大 `finder/maxtimeout` 重新启动。

**Comment by wpyok500** [comment]
家里的网络电信不行，出现如下，白天在公司电信网可以正常是使用。
下图是家里的网络运行日志
![1](https://user-images.githubusercontent.com/14154547/29240310-226f5e1c-7f95-11e7-8a91-2e8e6b28bfc4.png)

**Comment by SeaHOH** [comment]
调大 `gae/timeout` `finder/maxtimeout`
调小 `gae/keeptime` `finder/minipcnt`

其实干扰严重的话，你还是需要重新扫描点 IP 加进去，注意设定一个合适的超时。
或者使用 GoProxy 开 quic 也不错啊。

**Comment by wpyok500** [comment]
主要是想用来下载，gp的下载停停下下，太慢了。
