### ISSUE TITLE
ubuntu 16.04 使用了pip安装了所有依赖。但是import有问题

### ISSUE THREAD

**Issue by china-shang** [SeaHOH/GotoX#43]
![screenshot from 2017-08-31 12-08-34](https://user-images.githubusercontent.com/17249688/29906103-59ce4b70-8e45-11e7-94ef-620e68a07d49.png)

**Comment by SeaHOH** [comment]
还有 brotlipy 没装

**Comment by china-shang** [comment]
建议把依赖一起写进requirement.txt 中，这样可以自己pip insatll -r requirement.txt

**Comment by china-shang** [comment]
建议把依赖一起写进requirement.txt 中，这样可以直接pip insatll -r requirement.txt

**Comment by SeaHOH** [comment]
谢谢建议，其实我不太懂啦，帮我写一个行吗。

>-    gevent 1.1.2 及以上
>-    pyOpenSSL 16.0.0 及以上
>-    dnslib 0.8.3 及以上
>-    PySocks 1.5.4 及以上
>-    brotlipy 0.5.0 及以上

**Comment by china-shang** [comment]
gevent >= 1.1.2 
        pyOpenSSL >=16.0.0 
        dnslib >= 0.8.3 
        PySocks >= 1.5.4
        brotlipy >= 0.5.0 
把上面的保存为requirement.txt就行了，要安装依赖就可以pip3 install -r requirement.txt

**Comment by SeaHOH** [comment]
安装方面不懂，我连 Python 都不是安装的，自己精简了个便携版，没有设置环境变量和关联。

请问，除了 requirement.txt 还有其它需要做的吗？
