### ISSUE TITLE
启动时 UnicodeDecodeError 错误

### ISSUE THREAD

**Issue by pgz123** [SeaHOH/GotoX#46]
```
                本地 - SSLv23 / gevent

  网 络 配 置 : ipv4

  安 装 证 书 : 设置代理后访问 http://gotox.go/
================================================================================
==
Traceback (most recent call last):
  File "start.py", line 14, in <module>
    proxy.main()
  File "C:\Users\Administrator\Desktop\新建文件夹\gox\local\proxy.py", line 274,
 in main
    pre_start()
  File "C:\Users\Administrator\Desktop\新建文件夹\gox\local\proxy.py", line 223,
 in pre_start
    tasklist = dict((x.name.lower(), x) for x in get_process_list())
  File "C:\Users\Administrator\Desktop\新建文件夹\gox\local\proxy.py", line 118,
 in get_process_list
    path = modname.value.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 31: invalid
 continuation byte
```

**Comment by SeaHOH** [comment]
你的系统是什么？文件系统编码有点奇怪，先暂时强制用 `mbcs` 解码。

你也可以在配置文件中关闭进程检测功能。

**Comment by pgz123** [comment]
win732位

**Comment by SeaHOH** [comment]
耶，不对。
才发现你使用的不是最新版本……

**Comment by pgz123** [comment]
大海兄，最新在哪下？不会编译

**Comment by pgz123** [comment]
x\local\GlobalCo


x\local\GlobalCo






tion: 'gae'



















































































































































































































































































































































































































































































































































































































































































































































































































































































































x\local\GlobalCo


x\local\GlobalCo






tion: 'gae'
































































































































































































































































































































































































































































































































































































































































































































































































































































































































x\local\GlobalCo


x\local\GlobalCo






tion: 'gae'






























































































































































































































































































































































































































































































































































































































































































































































































































































































































Traceback (most recent call last):
  File "configparser.py", line 786, in get
  File "collections\__init__.py", line 881, in __getitem__
  File "collections\__init__.py", line 873, in __missing__
KeyError: 'debug'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from local import proxy
  File "C:\Users\Administrator\Desktop\新建文件夹\gox\local\proxy.py", line 61,
in <module>
    from .GlobalConfig import GC
  File "C:\Users\Administrator\Desktop\新建文件夹\gox\local\GlobalConfig.py", li
ne 36, in <module>
    class GC:
  File "C:\Users\Administrator\Desktop\新建文件夹\gox\local\GlobalConfig.py", li
ne 62, in GC
    GAE_DEBUG = CONFIG.getint('gae', 'debug')
  File "configparser.py", line 816, in getint
  File "configparser.py", line 806, in _get_conv
  File "configparser.py", line 800, in _get
  File "configparser.py", line 789, in get
configparser.NoOptionError: No option 'debug' in section: 'gae'

**Comment by pgz123** [comment]
新版3.40win32

**Comment by SeaHOH** [comment]
你是怎么升级的？配置文件 `Config.ini` 没有覆盖？

**Comment by pgz123** [comment]
啊，没覆盖，再试

**Comment by pgz123** [comment]
好了 ，谢谢
