### ISSUE TITLE
上推的日志

### ISSUE THREAD

**Issue by pgz123** [SeaHOH/GotoX#47]
22:39:42 W 219.76.4.4 _create_connection 'video.twimg.com' 返回 timeout('timed o
ut',)，重试
22:39:42 W 219.76.4.4 _create_connection 'abs.twimg.com' 返回 timeout('timed out
',)，重试
22:39:43 I L4:49476->173.194.24.76 "GAE GET https://twitter.com/i/timeline?compo
sed_count=0&include_available_features=1&include_entities=1&include_new_items_ba
r=true&interval=10000&latent_count=1&min_position=904715128808996865 HTTP/1.1" 2
00 225
22:39:48 W 219.76.4.4 _create_connection 'abs.twimg.com' 返回 timeout('timed out
',)，重试
22:39:50 W 219.76.4.4 _create_connection 'abs.twimg.com' 返回 timeout('timed out
',)，重试
22:39:50 W 219.76.4.4 _create_connection 'abs.twimg.com' 返回 timeout('timed out
',)，重试
22:39:53 I L4:49476->173.194.24.76 "GAE GET https://twitter.com/i/timeline?compo
sed_count=0&include_available_features=1&include_entities=1&include_new_items_ba
r=true&interval=10000&latent_count=1&min_position=904715128808996865 HTTP/1.1" 2
00 3601
22:39:56 W L4:49508->219.76.4.4 转发到 'pbs.twimg.com' 失败：timeout('timed out'
,)
22:39:58 W 219.76.4.4 _create_connection 'pbs.twimg.com' 返回 timeout('timed out
',)，重试
22:39:58 W 219.76.4.4 _create_connection 'pbs.twimg.com' 返回 timeout('timed out
',)，重试

**Comment by SeaHOH** [comment]
这个是需要自己维护规则的，自动尝试不一定会及时调用。
- 你可以编辑 GotoX 本身的配置 ActionFilter.ini；
- 或者使用代理插件加载其规则调用 8086 端口。

**Comment by pgz123** [comment]
嗯，上yt 就很快，谢谢

**Comment by SeaHOH** [comment]
不客气。
觉得还行，打算继续使用的话，可以大略看一遍首页介绍和配置文件。
