### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by jzp820927** [SeaHOH/GotoX#5]
您的连接不是私密连接

攻击者可能会试图从redirector.googlevideo.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_DATE_INVALID
Subject: googlevideo.com
Issuer: GotoX CA
Expires on: 2026年11月23日
Current date: 2016年11月23日

从报错看，好像是证书日期无效。删掉证书，重新生成也是这样。

**Comment by SeaHOH** [comment]
ActionFilter.ini 内容能不能看一下？

**Comment by jzp820927** [comment]
默认的，没改动过。

[0-fakecert]
#建议伪造证书排第一不要改动，配合需要匹配路径的加密链接
#clients1.google.com
#mail.google.com

[1-block]
#返回空数据包
#clients1.google.com/ocsp
#mail.google.com/mail/channel/bind
#.youtube-nocookie.com

[2-iredirect]
#内部重定向
#优酷示例规则、文件自备
#http://local.youku.com/loader.swf = file:///M:/Net/Palemoon/Lib/swf/loader.swf
#http://local.youku.com/player.swf = file:///M:/Net/Palemoon/Lib/swf/player.swf
#http:///@crossdomain\.xml$ = file:///M:/Net/Palemoon/Lib/swf/crossdomain.xml

[3-redirect]
#重定向
#优酷示例规则，与上面配合使用
#http://@^(static|player|v)\.youku\. = @.+?(?:id|ID|embed)(?:_|/|S=)([^\./\&]+).* >> http://local.youku.com/loader.swf?VideoIDS=\1
# google ipv4 sorry
ipv4.google.com/sorry = @.+continue=(.+)&q=.+ >> @\1

#[4-gae]
#changyan.sohu.com/debug/cookie
#changyan.sohu.com/stat

[5-forward]
#转发直连，即隧道代理
# github wss 协议
live.github.com
ipv6.
#cache.

[6-gae]
accounts.google.com
chrome.google.com
.googlevideo.com

[7-direct]
#代理直连（兼容性较好）
#[7-forward]
#代理转发／隧道（有可能遇到提供 gws 服务但没有部署相应证书的 IP）
.android.com = google_gws
.appspot.com = google_gws
.ggpht.com = google_gws
goo.gl = google_gws
.google.cn = google_com
.google.com = google_com
.google.com. = google_com
.googleapis.com = google_gws
.googlecode.com = google_gws
.googlegroups.com = google_gws
.googlesource.com = google_gws
.googletagservices.com. = google_gws
.googleusercontent.com = google_gws
.google-analytics.com = google_gws
.gstatic.com = google_com
.youtube.com = google_com
.ytimg.com = google_com
.golang.org = google_gws

[8-gae]
#通过 GAE 服务器代理
#.tw


[9-proxy]
#转发到代理服务器

**Comment by SeaHOH** [comment]
其它域名呢？有没有报日期错误？

**Comment by jzp820927** [comment]
您的连接不是私密连接

攻击者可能会试图从twitter.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_DATE_INVALID

您的连接不是私密连接

攻击者可能会试图从www.facebook.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_DATE_INVALID

一样的，这个是 chrome 浏览器的报错，GOTOX 的日志没有请求日志，估计是在证书验证出问题，还没开始请求数据，所以 GOTOX 还没日志。

**Comment by SeaHOH** [comment]
我没有 chrome 浏览器，麻烦你帮我测试下。
修改 CertUtil.py 签名过期日期，大概在 29 行，那两个 10 就是过期时间，单位：年。
> sub_time = 3600*24*(365*10+10//4)

改小，然后删除 certs 文件夹，不用删除主 CA 证书等和重新导入，也不用重启浏览器， Ctrl + F5刷新就好。看看多少年才不报错。

**Comment by jzp820927** [comment]
行，我也在怀疑，是不是默认的 30 年有点太长了，导致 chrome 认为时间过长不安全。我试试先。

**Comment by SeaHOH** [comment]
我的意思是先试被签名的子证书，不行再试 CA 证书。
麻烦你了 :white_flower:

**Comment by jzp820927** [comment]
知道了，根证书，和子证书的时间代码，我都看到了，我一个一个试，试完了，给你回复。

**Comment by jzp820927** [comment]
刚刚测试，子证书修改有效期为1 年，还是不行，一样的报错。
根证书修改有效期为1 年，也不行，一样的报错。
然后又用 FF 浏览器测试，一切正常。
看样子是 chrome 对证书有某些限制，导致错误提示。

**Comment by SeaHOH** [comment]
XX 呢？没看到有人报错啊。

**Comment by SeaHOH** [comment]
XX 呢？没看到有人报错啊。

**Comment by SeaHOH** [comment]
对了，想到个问题，大概在 92 行，子证书相关
> `cert.gmtime_adj_notBefore(0)`

把 0 改为负数 -3600

**Comment by jzp820927** [comment]
行，我试试，XX 上从没见到有这类报错。

**Comment by jzp820927** [comment]
OK，就是这个 -3600，你提个 commit 修复下吧

**Comment by SeaHOH** [comment]
OK，谢谢啦！ :pray:

**Comment by jzp820927** [comment]
不客气，开源项目，是要靠大家一起维护的。

**Comment by SeaHOH** [comment]
改好啦。

**Comment by jzp820927** [comment]
好，我 pull 下。谢谢。
