### ISSUE TITLE
gotox今天也不能用了

### ISSUE THREAD

**Issue by caofengzi** [SeaHOH/GotoX#51]
吉林聯通，今天gotox也不能使用了，應該可用ip都沒有了。

**Comment by SeaHOH** [comment]
是的。
可以找一些 sniproxy ip 来使用，一定要作为固定列表（`[gae/iplist]`），不然可能会影响其他人使用。
或者换用其它还能使用的代理。

**Comment by SeaHOH** [comment]
用 sniproxy ip 的话，servername 一定要是谷歌域名，但不能是 `www.google.com`。

**Comment by caofengzi** [comment]
這次是針對什麼封鎖的？ip還是證書。

**Comment by dou4cc** [comment]
ip+证书+servername

**Comment by Just2co** [comment]
QUIC目前依然坚挺，teredo IPv6隧道依然高速可用，sock5前置代理依旧如常高速可用，目前可以利用这3种方式高速过墙！

**Comment by tec1987** [comment]
@Just2co
teredo IPv6用的哪家的？以前用过，感觉速度一般

**Comment by Just2co** [comment]
@tec1987 韩国那家，虽然无法ping通，但是填进去重启PC之后可以用！速度还行，没以前快但是胜在稳定1080P看油管。

**Comment by masktao** [comment]
@Just2co 请问你说的填入重启pc是什么原理？为啥要重启？goproxy也可以这样用吗？

**Comment by Just2co** [comment]
@masktao 也可以的，不过要自己找IPv6 IP地址放进去，然后再配置文件里启用IPv6支持就可！

**Comment by blob2015** [comment]
额外提一句，上yt、g之类的，都没啥大问题，但上gitter.im，一片的黄红，用quic的话
gp还是比较低调，栏deng、ss是第一线

**Comment by Just2co** [comment]
@SeaHOH 海兄，啥时候升级支持http前置代理啊？我看配置文件前置代理设置项不可用啊，我这里有好几个高速稳定的sock5前置代理，转成http之后，可以作为gotoX的前置代理！

**Comment by SeaHOH** [comment]
好的，我这几天试着添加一下。

**Comment by Just2co** [comment]
@SeaHOH 之所以请求你的帮助，是因为谷歌证书还没被GFW block之前，你写的GOTOX速度最快，放几个IP进去都能跑满带宽，而xx-net速度就不行，goagent在chorome升级到最新版之后证书错误也不能用了。我现在用的xx-net就是开了http前置，它能支持sock4/sock5/http这三种前置。如果你的GotoX也支持了前置，那之前搜的一些高速IP就能继续用上了！

**Comment by SeaHOH** [comment]
那是因为用的 IP 本来就快，GotoX 挑着快的用。
如果有高质量前置，使用固定列表替换自动筛选会比较好，只需要放几个 IP 就行。

**Comment by SeaHOH** [comment]
@Just2co 
已添加，但是未测试，如果不能正常使用，请新开 issues 报错。
>如果有高质量前置，使用固定列表替换自动筛选会比较好，只需要放几个 IP 就行。

放域名应该也可以，只要解析出的 IP 是前置能访问的（多半是台湾 IP），但是这样不保证速度。

**Comment by tec1987** [comment]
@SeaHOH
老兄，现在sniproxy 好像没几个可用的了吧？
GoP只能开QUIC用了。。。
你这个gotoX是基于goa的吧？

**Comment by SeaHOH** [comment]
>现在sniproxy 好像没几个可用的了吧？

可以自己搭，sniproxy 还是比较可靠的只要不连谷歌、脸书等。
连 GAE 时可以用 GoProxy 或 GotoX 自定义 servername，以避开某些关键字。

>GoP只能开QUIC用了

大概是，用 sniproxy 的情况上面写了。

>你这个gotoX是基于goa的吧？

是，但调整了代理流程，细节也有改变。具体可以看 readme 或源码。

**Comment by Just2co** [comment]
@SeaHOH 赶紧再整整，用不了，config.ini前置代理那填的1，也就是启用了http前置，然而帽架MEOW软件监控到GOTOX并没有数据过来，用XX-NET开启http前置，MEOW前置那都有信息提示，然后gotox提示如下：
==================================================================================
20:14:03 W L4:13462-> do_GAE 超时，url='http://xn--gmqx3hmshvy4a.tv/archives/11412'，重试
20:14:04 W L4:13464-> do_GAE 超时，url='https://ben.crxmouse.com/ms/gs'，重试
20:14:05 W L4:13464-> do_GAE 由于有上传数据 "POST https://ben.crxmouse.com/ms/gs" 终止重试
20:14:10 W 没有检测到足够数量符合要求的 GAE IP，请重新设定参数！

也就是前置代理设置为1并没有起作用，如果起作用的话，MEOW监控窗口会有代理请求链接出现

**Comment by SeaHOH** [comment]
proxylist 填好没有？

**Comment by Just2co** [comment]
@SeaHOH 我稍微创新了一下，默认就是GAE代理，把自动代理的端口改成8086了，这样就不用手工设置proxylist了
#自动代理
auto_port = 8086
#GAE 代理
gae_port = 8087

**Comment by SeaHOH** [comment]
没懂，什么意思，你要填进去 GotoX 才能使用。

**Comment by SeaHOH** [comment]
这个只是 GAE 前置，不是 GotoX 前置，GotoX 前置可以使用其它软件实现。

**Comment by SeaHOH** [comment]
的确有 bug，等会儿改……

**Comment by Just2co** [comment]
因为谷歌证书被GFW认证，因此gotox单靠GWS/GVS IP跟GAE沟通已经行不通了，因此我找了MEOW前置SOCKS/http代理作为跳板，然而gotox设置好前置后，并没有起作用,没有数据到MEOW这里来。

**Comment by SeaHOH** [comment]
@Just2co 
已修复 bug，其中一个是 SOCKS4 的旧 bug。
但是你无法使用似乎不光是 bug 的原因，你需要在 proxylist 中填写代理。

**Comment by SeaHOH** [comment]
刚试了好几个，都无法链接 GAE，换了 servername 也不行，似乎针对 SOCKS 代理检查了证书。

**Comment by SeaHOH** [comment]
好像又不是证书，情况比较奇怪，没有条件懒得研究了。

**Comment by Just2co** [comment]
@SeaHOH 白天的时候干扰比较轻，可以再测试一下，找美国的sock5代理，谷歌一大把，只要能ping通就能用，不过最好是用MEOW转换成http，然后再填入前置代理，我前置代理xx-net/goproxy/轮子的两款/蓝灯/赛风都高速稳定可用！

**Comment by Just2co** [comment]
@SeaHOH 以下是Gogox错误提示：
11:54:22 W 正在通过前置代理使用 GAE：['HTTP://127.0.0.1:4411']。
Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\gevent-1.2.2-cp35-win32.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "D:\Program Files\Goproxy\GotoX\local\GAEUpdate.py", line 276, in checkgooglecom
    for ip in GC.IPLIST_MAP[GC.GAE_IPLIST]:
KeyError: ''
Sat Oct 21 11:54:22 2017 <Greenlet at 0x6102260: checkgooglecom> failed with KeyError

11:54:51 W L4:2353-> do_GAE "GET https://www.google.com/ncr" 返回：IndexError('string index out of range',)，重试
11:54:51 E L4:2353-> do_GAE "GET https://www.google.com/ncr" 失败：IndexError('string index out of range',)
Traceback (most recent call last):
  File "random.py", line 262, in choice
  File "random.py", line 239, in _randbelow
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 681, in request
    ssl_sock = self.create_gae_connection_withproxy(address, hostname, connection_cache_key, getfast=getfast)
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 578, in create_gae_connection_withproxy
    proxy = self.get_gae_front(getfast)
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 569, in get_gae_front
    return random.choice((proxy_list[0], random.choice(proxy_list[1:])))
  File "random.py", line 264, in choice
IndexError: Cannot choose from an empty sequence

**Comment by Just2co** [comment]
@SeaHOH 12:06:48 W 正在通过前置代理使用 GAE：['SOCKS5://161.144.221.183:28187']。
Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\gevent-1.2.2-cp35-win32.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "D:\Program Files\Goproxy\GotoX\local\GAEUpdate.py", line 276, in checkgooglecom
    for ip in GC.IPLIST_MAP[GC.GAE_IPLIST]:
KeyError: ''
Sat Oct 21 12:06:48 2017 <Greenlet at 0x5887670: checkgooglecom> failed with KeyError

Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\start.py", line 14, in <module>
    proxy.main()
  File "D:\Program Files\Goproxy\GotoX\local\proxy.py", line 281, in main
    network_test()
  File "D:\Program Files\Goproxy\GotoX\local\ProxyServer.py", line 191, in network_test
    _, peername = test_sock.recvfrom(512)
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\gevent-1.2.2-cp35-win32.egg\gevent\_socket3.py", line 362, in recvfrom
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

这是socks5前置时报错参数，请你看下哪里出问题了

**Comment by SeaHOH** [comment]
上面这个错误，是因为你没有填写链接 GAE 使用的列表。
默认是 google_gws，可以在 [gae/iplist] 修改，然后填域名或几个 IP。

另外，我这里前置完全无法连接 GAE，http 和 socks 都是如此。

**Comment by SeaHOH** [comment]
使用 GAE 前置时，增加了一个专用列表 `google_2p`，填写谷歌域名或 IP 就行，也可以自定义列表名称。

**Comment by Just2co** [comment]
@SeaHOH 我这里也是一样的，gotox前置模块根本就没起作用，前置代理软件MEOW那根本就收不到来自gotox的代理数据！

**Comment by SeaHOH** [comment]
不用给我，我这里标准代理无法突破。

你上面使用了 `g` 作为列表名称，需要在 [iplist] 小节配置
```ini
[iplist]
g = www.google.com | ip1 | ip2
```

**Comment by Just2co** [comment]
@SeaHOH 现在已经全部都是按照你写的设置的，当时用不了报错，MEOW这里检测不到数据过来
[ERROR] 2017/10/22 10:15:58 socks reply connect 103.250.189.164:443 error Connection refused
[ERROR] 2017/10/22 10:16:00 socks reply connect 124.216.0.76:443 error Connection refused



       /\
   )  ( ')     MEOW Proxy 1.5
  (  /  )      http://renzhn.github.io/MEOW/
   \(__)|

2017/10/22 10:18:10 listen http 127.0.0.1:4411, PAC url http://127.0.0.1:4411/pac
那个图案上边的参数是MEOW重启之前，接收到XX-NET过来的数据，重启之后，启动gotox，就只有一条默认的启动信息，再也不会滚动出现其他代理信息，gotox报错如下：

**Comment by SeaHOH** [comment]
你只填了一个代理，我没考虑到这个情况，现已修复。

**Comment by SeaHOH** [comment]
使用 GAE 前置时记得修改默认的谷歌直连规则，封锁严重时这是连不上的，配置成前置使用的代理或其它代理。

**Comment by Just2co** [comment]
@SeaHOH 我在iplist这里填了好几个IP，只不过只给你复制了这一个，问题是MEOW作为gotox的前置的时候，MEOW这里收不到gotox过来的数据包，不知道你修复的是不是这个问题

**Comment by SeaHOH** [comment]
>File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 569, in get_gae_front
return random.choice((proxy_list[0], random.choice(proxy_list[1:])))
File "random.py", line 264, in choice
IndexError: Cannot choose from an empty sequence

我是从这里看出来的，你只填了一个代理。
代码错误后就不会发出请求，所以 MEOW 没有受到数据包。

**Comment by SeaHOH** [comment]
其实你只需要配置 `gae` 小节的 `enableproxy` 和 `proxylist` 就行了。

如果无法正确解析 `www.google.com`，就把 `iplist` 小节的 google_2p 配置为几个 IP。

**Comment by Just2co** [comment]
@SeaHOH 还是用不了，请帮忙看下什么原因，MEOW那仍然不能滚动，无论是http或者socks前置都不行

15:32:53 W 正在通过前置代理使用 GAE：['socks5://162.144.221.185:28147']。
15:32:53 W 正在使用固定的 GAE IP 列表 [google_2p]，除了启动时，将不再进行 IP 检查。
15:33:04 W L4:22389-> do_GAE "GET https://www.google.com/ncr" 返回：IndexError('string index out of range',)，重试
15:33:04 E L4:22389-> do_GAE "GET https://www.google.com/ncr" 失败：IndexError('string index out of range',)
Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 606, in create_gae_connection_withproxy
    proxy_sock.settimeout(self.timeout)
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\PySocks-1.6.6.egg\socks.py", line 311, in settimeout
    peer = self.get_proxy_peername()
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\PySocks-1.6.6.egg\socks.py", line 452, in get_proxy_peername
    return super(socksocket, self).getpeername()
AttributeError: 'super' object has no attribute 'getpeername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 683, in request
    ssl_sock = self.create_gae_connection_withproxy(address, hostname, connection_cache_key, getfast=getfast)
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 610, in create_gae_connection_withproxy
    if '0x5b' in e.msg and not isip(host):
AttributeError: 'AttributeError' object has no attribute 'msg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\local\ProxyHandler.py", line 546, in do_GAE
    response = gae_urlfetch(self.command, self.url, request_headers, payload, appid)
  File "D:\Program Files\Goproxy\GotoX\local\GAEFetch.py", line 83, in gae_urlfetch
    response = http_gws.request(request_params, payload, request_headers, connection_cache_key='google_gws:443', getfast=getfast, realmethod=method, realurl=realurl)
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 704, in request
    logging.warning('%s _request "%s %s" 失败：%r', ip[0], realmethod, realurl or url, e)
IndexError: string index out of range

15:33:22 W 15:33:22 W Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\gevent-1.2.2-cp35-win32.egg\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "D:\Program Files\Goproxy\GotoX\local\GAEUpdate.py", line 286, in checkgooglecom
    _checkgooglecom(True)
  File "D:\Program Files\Goproxy\GotoX\local\GAEUpdate.py", line 271, in _checkgooglecom
    ip, ssldomain, costtime, isgaeserver)
  File "D:\Program Files\Goproxy\GotoX\local\clogging.py", line 143, in warning
    log(WARNING, fmt, *args)
  File "D:\Program Files\Goproxy\GotoX\local\clogging.py", line 125, in log
    _flush() # immediately output for python3
OSError: raw write() returned invalid length 22 (should have been between 0 and 11)
Sun Oct 22 15:33:32 2017 <Greenlet at 0x65143a0: checkgooglecom> failed with OSError

15:33:32 W L4:22399-> do_GAE "POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJIcDhwT2xpcHhyN3E5QzJsUnIxVzJBc2o2QUlxbGoyZEVHM1RPemFZRldvMGZTdmNUQ20wOE1paDNSM0k4dGNiTUVhLU51X05wOVJIX3d1TFVhUGJFeWhyZWRvQ3pDeVB3VFp4VTNBZTNTTGhzUnNmRjFkdXdHUTdnM09raERscWpVck9aX0ZWa3dvOWJEVXFqdExZemxkSmxTek9PWm80b3dhUUMySTVrbkFTZ3J6VmMaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM" 返回：IndexError('string index out of range',)，重试
15:33:32 W L4:22399-> do_GAE 由于有上传数据 "POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJIcDhwT2xpcHhyN3E5QzJsUnIxVzJBc2o2QUlxbGoyZEVHM1RPemFZRldvMGZTdmNUQ20wOE1paDNSM0k4dGNiTUVhLU51X05wOVJIX3d1TFVhUGJFeWhyZWRvQ3pDeVB3VFp4VTNBZTNTTGhzUnNmRjFkdXdHUTdnM09raERscWpVck9aX0ZWa3dvOWJEVXFqdExZemxkSmxTek9PWm80b3dhUUMySTVrbkFTZ3J6VmMaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM" 终止重试

**Comment by SeaHOH** [comment]
已修改。加油，快成功了~

**Comment by Just2co** [comment]
@SeaHOH 加油，的确是看到成功的曙光了！下面是前置MEOW软件反馈数据：

       /\
   )  ( ')     MEOW Proxy 1.5
  (  /  )      http://renzhn.github.io/MEOW/
   \(__)|

2017/10/22 21:00:36 listen http 127.0.0.1:4411, PAC url http://127.0.0.1:4411/pac
[>>>>>] 2017/10/22 21:01:07 PROXY 127.0.0.1:25598 CONNECT ***.appspot.com:443
[ERROR] 2017/10/22 21:01:07 PROXY 127.0.0.1:25600 CONNECT ***.appspot.com:443
[ERROR] 2017/10/22 21:02:05 socks reply connect ***.appspot.com:443 ATYP 4

下面是gotox软件的反馈信息：
21:06:24 W 固定 GAE IP 列表检测，IP：202.86.162.172，可用证书：None，耗时：3002 毫秒，支持 GAE：False
21:06:25 W L4:26170-> do_GAE "GET https://www.google.com/ncr" 返回：AttributeError("'_wrefsocket' object has no attribute 'sock'",)，重试
21:06:25 W L4:26168-> do_GAE "POST https://api.userstyles.org/tic/stats" 返回：AttributeError("'_wrefsocket' object has no attribute 'sock'",)，重试
21:06:25 W L4:26168-> do_GAE 由于有上传数据 "POST https://api.userstyles.org/tic/stats" 终止重试
21:06:27 W 固定 GAE IP 列表检测，IP：202.169.193.91，可用证书：None，耗时：3001 毫秒，支持 GAE：False
21:06:28 E create_gae_connection_withproxy 链接代理失败：'HTTP://127.0.0.1:4411'
21:06:28 E L4:26170-> do_GAE "GET https://www.google.com/ncr" 失败：AttributeError("'_wrefsocket' object has no attribute 'sock'",)
Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 691, in request
    result.settimeout(timeout)
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\PySocks-1.6.6.egg\socks.py", line 311, in settimeout
    peer = self.get_proxy_peername()
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\PySocks-1.6.6.egg\socks.py", line 452, in get_proxy_peername
    return super(socksocket, self).getpeername()
AttributeError: 'super' object has no attribute 'getpeername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Goproxy\GotoX\local\ProxyHandler.py", line 546, in do_GAE
    response = gae_urlfetch(self.command, self.url, request_headers, payload, appid)
  File "D:\Program Files\Goproxy\GotoX\local\GAEFetch.py", line 83, in gae_urlfetch
    response = http_gws.request(request_params, payload, request_headers, connection_cache_key='google_gws:443', getfast=getfast, realmethod=method, realurl=realurl)
  File "D:\Program Files\Goproxy\GotoX\local\HTTPUtil.py", line 697, in request
    ssl_sock.sock.close()
  File "D:\Program Files\Goproxy\GotoX\local\compat\openssl.py", line 27, in __getattr__
    return getattr(self._connection, attr)
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\OpenSSL-17.0.0-cp35-win32.egg\OpenSSL\SSL.py", line 1337, in __getattr__
    return getattr(self._socket, name)
  File "D:\Program Files\Goproxy\GotoX\python\site-packages\gevent-1.2.2-cp35-win32.egg\gevent\_socket3.py", line 93, in __getattr__
    return getattr(self._sock, name)
AttributeError: '_wrefsocket' object has no attribute 'sock'

21:06:30 W 固定 GAE IP 列表检测，IP：213.158.189.216，可用证书：None，耗时：3001 毫秒，支持 GAE：False
21:06:33 W 固定 GAE IP 列表检测，IP：203.211.0.29，可用证书：None，耗时：3002 毫秒，支持 GAE：False
21:06:33 E 检测出固定 GAE IP 列表 [google_2p] 中包含的可用 GWS IP 数量过少：0 个，请增加。
21:06:40 W L4:26198-> do_GAE "GET https://www.google.com/ncr" 返回：AttributeError("'_wrefsocket' object has no attribute 'sock'",)，重试
21:06:49 E create_gae_connection_withproxy 链接代理失败：'HTTP://127.0.0.1:4411'
21:06:49 W L4:26169-> do_GAE 超时，url='https://ben.crxmouse.com/ms/gs'，重试
21:06:49 W L4:26169-> do_GAE 由于有上传数据 "POST https://ben.crxmouse.com/ms/gs" 终止重试

下面是MEOW前置代理XX-net的滚动信息：
   )  ( ')     MEOW Proxy 1.5
  (  /  )      http://renzhn.github.io/MEOW/
   \(__)|

2017/10/22 21:07:35 listen http 127.0.0.1:4411, PAC url http://127.0.0.1:4411/pac
[>>>>>] 2017/10/22 21:07:35 DIRECT 127.0.0.1:26287 CONNECT 183.136.212.50:443
[>>>>>] 2017/10/22 21:07:35 PROXY 127.0.0.1:26290 CONNECT 173.194.63.84:443
[>>>>>] 2017/10/22 21:07:35 PROXY 127.0.0.1:26293 CONNECT 173.194.212.149:443
[>>>>>] 2017/10/22 21:07:36 PROXY 127.0.0.1:26295 CONNECT 221.144.116.79:443
[>>>>>] 2017/10/22 21:07:36 PROXY 127.0.0.1:26297 CONNECT 203.113.130.158:443
[>>>>>] 2017/10/22 21:07:36 PROXY 127.0.0.1:26299 CONNECT 213.153.32.181:443
[>>>>>] 2017/10/22 21:07:36 PROXY 127.0.0.1:26301 CONNECT 177.43.165.113:443
[>>>>>] 2017/10/22 21:07:37 PROXY 127.0.0.1:26304 CONNECT 176.221.96.27:443
[>>>>>] 2017/10/22 21:07:37 PROXY 127.0.0.1:26306 CONNECT 163.44.26.119:443
[ERROR] 2017/10/22 21:07:37 socks reply connect 213.153.32.181:443 error Connection refused

可以明显看出MEOW显示的区别，gotox显示连接appspot.com，而xx-net直接连接GAE IP，也就是GWS IP，这估计就是gotox失败而xx-net前置成功的原因。

**Comment by SeaHOH** [comment]
已修改，我觉得这回行了。

**Comment by SeaHOH** [comment]
>不用给我，我这里标准代理无法突破。

前言撤回~ 如果有自建的给我个作为后备，发我邮箱就行。 :smile_cat: 

刚试了一下，居然成功使用前置突破。看来我还是太想当然了，没有实际运行验证。
检查了之前的测试代码才发现，之前用的默认 ssl 模块，都是默认设置（可能是这个部分参数不安全导致被墙） 。

**Comment by Just2co** [comment]
@SeaHOH 帮我看看怎会如此奇葩，gotox把我填入的前置socks5服务器IP当成GAE IP了
12:03:01 W 正在使用固定的 GAE IP 列表 [google_2p]，除了启动时，将不再进行 IP 检查。
12:03:01 W 正在通过前置代理使用 GAE：['SOCKS5://162.144.221.185:28147']。
12:03:06 W IP：'162.144.221.185' 暂时不可用，已经删除
12:03:06 W 发现并移除非 GAE IP：162.144.221.185，Server：None
12:03:08 W IP：'162.144.221.185' 暂时不可用，已经删除
12:03:08 W 发现并移除非 GAE IP：162.144.221.185，Server：None
12:03:10 W IP：'162.144.221.185' 暂时不可用，已经删除
12:03:10 W 发现并移除非 GAE IP：162.144.221.185，Server：None

**Comment by SeaHOH** [comment]
@Just2co 
我已经能用了，怀疑配置错误。你的配置发我邮箱，明晚答复你。

今天累死了，明天也比较忙，我要 :bed: :zzz: 了。

**Comment by 2378** [comment]
mark一下 是时候多备几个梯子了

**Comment by Just2co** [comment]
@SeaHOH  seahoh@users.noreply.github.com  这是你的邮箱？

**Comment by tec1987** [comment]
@Just2co 肯定不是，自己看域名后缀。。。

**Comment by SeaHOH** [comment]
@Just2co 
下面这个是 socks5 吗？
```ini
proxylist = HTTP://127.0.0.1:4411
```
正确写法是
```ini
proxylist = socks5://127.0.0.1:4411
```

**Comment by SeaHOH** [comment]
好像不是这个原因，你上面实际上已经成功链接代理了，但是返回的结果不对，导致进行了有效性测试。

换个刚刚在 XX-Net 成功使用的代理试试？

**Comment by Just2co** [comment]
socks5已经被MEOW转换成HTTP代理了，默认端口是4411，跟8087端口类似的，你再看下其他地方有文昌没，我可以确定不是这里的问题

**Comment by SeaHOH** [comment]
这里面有几个脸书的 IP？
69.171.229.73|74.125.23.138|74.125.23.139|31.13.65.1|31.13.65.17|69.171.235.101|74.125.23.101|74.125.23.113|74.125.23.102

**Comment by SeaHOH** [comment]
我这儿今天又用不了前置了……

**Comment by SeaHOH** [comment]
刚修改成不用手动更改默认谷歌直连规则，可自动使用 GAE 的前置代理。

**Comment by SeaHOH** [comment]
@Just2co
今天测试 XX-Net 的时候，顺便也用 X-Tunnel 测试了一下 GotoX 的 GAE 前置。
X-Tunnel 是加密传输的，结果可用于 GotoX 前置，同时普通标准代理仍然无法连接，前置不了。

**Comment by Just2co** [comment]
@SeaHOH 估计还是哪里写的有问题，同样的前置，用XX-NET的正常，就是GOTOX就不行。

**Comment by SeaHOH** [comment]
我使用普通代理前置 XX-Net 还是无法使用。
你确定 XX-Net 走了前置代理吗？如果是，我就放弃了，没法测试。

**Comment by Just2co** [comment]
@SeaHOH 确定，XX-NET web配置界面有个选项，专门设置前置代理的，直接填进去前置服务器IP跟端口以及前置类型，就能用了，同样的放到gotox里面，就只能打开http网页而且速度非常慢，https打不开
