### ISSUE TITLE
远程主机强迫关闭一个现有的连接

### ISSUE THREAD

**Issue by wpyok500** [SeaHOH/GotoX#52]
![image](https://user-images.githubusercontent.com/14154547/32141445-9396a826-bcbb-11e7-9910-344bd43aa9fa.png)

**Comment by SeaHOH** [comment]
可能有证书检测，主动断开了。
这个不需要代理吧，https 默认是 FWD（转发）动作，你修改过？可以在自动规则中指定 FWD 动作。
```ini
[n-forward] # n 为序数
.microsoft.com
```

**Comment by SeaHOH** [comment]
-
