### ISSUE TITLE
gotox现在使用的是什么tls吗？如果要配置sni，如何配置。

### ISSUE THREAD

**Issue by wpyok500** [SeaHOH/GotoX#59]
gotox现在使用的是什么tls吗？如果要配置sni，如何配置。

**Comment by SeaHOH** [comment]
没有现成的 QUIC 库，所以还是 TLS。IPv6 应该可以用。

使用 sni 上个 issues 就有讲 https://github.com/SeaHOH/GotoX/issues/58#issuecomment-348825796 。

**Comment by wpyok500** [comment]
不能像默认那样，直接在data文件夹底下配置一个sni_all.txt的sni   ip列表吗？

**Comment by wpyok500** [comment]
我将ip.txt内的ip全部替换成sni  ip 也是可以使用的。

**Comment by SeaHOH** [comment]
可以直接放到 ip.txt 使用。

**Comment by wpyok500** [comment]
gotox在我这解析一个网站速度有点慢，请问如何提高。

**Comment by SeaHOH** [comment]
换 DNS 或更改 DNS 服务器设置？

**Comment by blob2015** [comment]
大海兄，搭车问一下，估摸着啥时候会有人搞出来个quic库？
quic好像地位要提高啊。

**Comment by blob2015** [comment]
大海兄强大

**Comment by Peytonlan** [comment]
如果是为了翻墙, 私以为quic上不宜投入太大精力, 我这quic封锁蛮长时间了

**Comment by SeaHOH** [comment]
只是有想法，根本没动力~

**Comment by blob2015** [comment]
>已交给 IETF，预计将于 2018 年标准化
>TLS 1.3 已经到达标准化的最后阶段
tls 1.3＋quic，会产生一些变化，虽然到时候墙也会有变化，目前可以观望一阵子
@Peytonlan 
gp开启quic不能用？俺这里用得好好的啊，重灾区

**Comment by Peytonlan** [comment]
@blob2015
我这udp一直是间歇性中断, 一开始udp没断时, goproxy使用quic能够连接
再后来, 即使udp没断, goproxy也无法使用quic连接, 算是彻底封了

**Comment by blob2015** [comment]
@Peytonlan 
这个俺这边是这样的，就是有段时间，ip会变得很少很少，连接还是能连接的，quic
使用quic，ip数量很重要
当然，也可能各地各isp状况不一样，真有可能有那家把quic给彻底封了也说不好

**Comment by Peytonlan** [comment]
goproxy有些天没用了, 怕我说的太主观, 相对认真重新试了下
暂时收回前面说的话, 不是因为情况有很大改善, 而是觉得goproxy的quic应该还有提升空间, 有不确定性

ip以万计, 谈何容易
gscan-quic 3.6, 默认数据库, 找出2个ip
gscan-quic 2.0, 默认数据库, 找出8个ip
2.0似乎搜索结果略好些
gscan-quic 2.0, 以前用goagent时积累的218万的ip库, 找出147个ip
算是凑出了157个ip用来测试
投入goproxy， 不超一分钟就连不上了
也容易理解, ip本身就少, 而且goproxy还使用了 clients3.google.com 这个在我这儿找死的域名来测连通性
以前懒就没折腾, 这次勤快点, 改两行代码, 换个域名
https://github.com/goproxy0/goproxy/blob/39611867adb372fa95ff8643d4e07cf357320d0e/httpproxy/filters/gae/gae.go#L372
https://github.com/goproxy0/goproxy/blob/39611867adb372fa95ff8643d4e07cf357320d0e/httpproxy/filters/gae/gae.go#L394
改了域名后, 的确有改善, 差不多放个两三首MV没问题, 然后继续断连, 还是报udp超时
虽然断了, 从输出看, 有个不正常的现象, good_addrs并没有下降多少, 有时甚至还有上升, 怀疑ip判定及调度有些问题
那就同时运行两个goproxy吧, 果然其中一个断了后, 另一个并没有同时中断, 这说明了不完全是ip不能连接导致的中断
暂时没时间也没精力折腾了, 到此为止

这次勤快点, 还是有个小收获的, 以前因为 clients3.google.com 的问题, goproxy配置sniproxy也运行不长时间的, 总算是稳定了

**Comment by blob2015** [comment]
有个讨论的issue，社长也参与，这会儿找不到了，好像还是在主任那边，记得他有说，蜗牛角上争天地，石火光中寄此身（白居易原诗修改而来？）。感觉你可能还是过于精细了，所谓的ip质量（带宽、响应速度）已经没有意义了。
粗茶淡饭保平安。
数量就是质量。

**Comment by Peytonlan** [comment]
问题是没数量啊, 又哪来的粗茶淡饭
火中取栗, 不精细点怎么办, 所以我对quic持保留态度

**Comment by blob2015** [comment]
你都精细了，那还是什么粗茶淡饭？这个暂时告一段落吧。
quic被N多人看淡，但都成了基础协议了，怎么看淡？我用quic，都没断过一天……

**Comment by gxggsrmyy** [comment]
@SeaHOH 经常被关闭连接退出。
![default](https://user-images.githubusercontent.com/12831337/35040620-c8f9753a-fbbc-11e7-9f54-2b82c1d22276.jpg)

**Comment by SeaHOH** [comment]
愕，看起来 DNS 被干扰了？不都是污染嘛，没见过这种。
@gxggsrmyy 你没有修改过源代码里面的 DNS 和域名吧？如果没有，这里加一个 try 就行了。

**Comment by gxggsrmyy** [comment]
@SeaHOH 没有修改过源代码, 在哪里加 try?

**Comment by SeaHOH** [comment]
等会儿我提交一个

**Comment by SeaHOH** [comment]
好了，试试这个 https://github.com/SeaHOH/GotoX/tree/f-DNS-reset

**Comment by gxggsrmyy** [comment]
@SeaHOH 什么时候支持域名绑定？

**Comment by SeaHOH** [comment]
现在有必要么？很急吗？
我想等开年后空闲点了，再考虑之后怎么做，准备增加对其它云服务的支持方案。

**Comment by blob2015** [comment]
@SeaHOH 
不急不急
慢慢来
过了年再说
多吃点抄手

**Comment by gxggsrmyy** [comment]
@SeaHOH 支持域名绑定如果难度不大，是有用的

**Comment by SeaHOH** [comment]
@gxggsrmyy 容易添加。但是一来现在还可以用 SNI 反代；二是决定以后不用 GAE 做主力了，到时还会重构代码，所以暂时不想改动。

**Comment by gxggsrmyy** [comment]
@SeaHOH 其它云平台的项目多了，不差你一个,gotox 的特点就是gae, 如果放弃gae 就没意思了，应该坚持立足gae, 充分挖掘gae

**Comment by blob2015** [comment]
@gxggsrmyy 这个项目首先是自用，然后想用的搭个便车。其他云平台好，那就其他的云平台呗。做GAE的，也不只这个。
不要动不动就说什么，哎呀，你这样做是不对的，我最聪明。或许你自己有自己的想法，甚至想法也不错，但你没有遇到过，某人指着鼻子说你，你怎么这么蠢，你怎么会这么做。
有缘则聚，无缘则散。不要把自己的意愿强加给别人，这是无聊而自私的。

**Comment by blob2015** [comment]
@SeaHOH 
大海兄，最近你狂下视频？ :grinning:

**Comment by SeaHOH** [comment]
没，日常杀时间，顺手修点小 bug（复杂的不会）。

**Comment by Just2co** [comment]
@SeaHOH 海兄，你自学Python多久了啊？写gotox这个项目让你code技能突飞猛进吧？

**Comment by SeaHOH** [comment]
当年改 `gvs` 的时候开始的吧，还好有段时间超闲。主要是为了自己用得顺手。

**Comment by Just2co** [comment]
@SeaHOH  改GVS是2015年4、 5月份的时候吧，我也是那个时候开始自学的，可惜琐事太多，断断续续的，最近才有了点头绪。

**Comment by blob2015** [comment]
@SeaHOH @Just2co 那天俺也试着学点，这年头，就不知道那年那月会完成这档子事了。好像不学点这个，都整不利索很多事……

**Comment by Just2co** [comment]
@blob2015   建议学，很简单的，搜索requests 或者beautifulsoup爬虫，你可以连Python语法都不懂的情况下，就能搞懂这两个开源爬虫库写出来的爬虫小脚本，照着修修改改，Python基本语法就会了，至少可以去爬妹子图、小说、视频、网易云音乐或者喜马拉雅音乐之类的，成就感会大增，然后在进一步学习scrapy框架，慢慢的你就入门Python了，至少是爬虫领域。 像 @SeaHOH 搞得gotox项目，偏向于网络编程，在做这个项目的过程中，你会学到很多的网络方面的一些知识。比如tcp/ip，sock，quic ,SNI，前置代理等等。

**Comment by blob2015** [comment]
@Just2co 老兄说的，甚好，有实操经验的人哪。之前学正则，就是靠着修改小说，慢慢练出来的。感谢。

**Comment by Just2co** [comment]
@blob2015 万事开头难，开头那一个月是最痛苦的，后来就好点了，几个月之后的某一瞬间，你会有一种打通任督二脉的感觉，再在那之后，很多问题就依照固定的路数就可以搞定了，而不是刚开始百思不得骑姐那种痛苦想放弃！

**Comment by SeaHOH** [comment]
时间很重要啊，之前我是太闲了。 :trollface:

**Comment by Just2co** [comment]
@SeaHOH 我现在就有大把的时间，在一家公司做实习生，但是现在还是感觉效率有点低，经常被一些问题卡半天，再给指点下？现在还处于看别人的单个脚本去理解，然后自己去改到能用的阶段，而且稍微复杂的项目，比如涉及到多个脚本之间互相调用，class类 project，就不明所以了，要么就是下载github别人的开源项目，改里面的部分参数，人家告诉我，去看入门教程，内功还要继续修炼，也就是基础还不牢，也有人让继续去做项目，只有在项目中碰到的不会的再去现学，才能加速理解掌握

**Comment by SeaHOH** [comment]
你这是要做成码农的节奏？
有没有项目说明，子项目有没有文档，源码有没有注释？都没有？那就可以考虑以后不要在这里干。

**Comment by Just2co** [comment]
@SeaHOH 是准备干这一行，大学毕业到现在已经错过了七八年的光阴了，趁35岁之前赶紧转行搞这个，人生才有希望。我问他的代码怎么不添加注释，带我入门的那个工程师说，要注重代码简介，项目刚开始启动的时候是有注释的，后来迭代改进的时候删掉了，为了简洁。我估计主要是为了防止他被开了之后，无人能替代他的项目吧！现在是他走了，留我在这里继续维护。文档就是在项目文件夹下面有个介绍.md，其他子文件夹下面就是脚本代码了。

**Comment by SeaHOH** [comment]
我这种外行都知道的基本，你领导不行啊，根本管不住属下。。。

**Comment by Just2co** [comment]
@SeaHOH 他就是技术部负责人，呵呵，对了，我想改改，让goproxy也能支持谷歌和其他被墙的网站。我刚才把gotox里面的ip.use文件里的IP取出来放进goproxy里面，发现可以开其他网页了，谷歌的404错误，我头天用SNI的时候，发现只能打开谷歌的不能开其他的，要改哪里呢？

**Comment by Just2co** [comment]
@SeaHOH 如果访问的是谷歌域名，servername就是fonts.googleapis.com，如果是其他域名，就是xxx.appspot.com，但即便知道这样，也还是不知道怎么把goproxy相关脚本改过来。在这里的判断以前是没有的吧？

**Comment by SeaHOH** [comment]
https://github.com/SeaHOH/goproxy/blob/master/httpproxy/filters/gae/gae.go#L123
这个是默认值

https://github.com/SeaHOH/goproxy/blob/master/httpproxy/helpers/dialer2.go#L115
从这儿开始分别处理

**Comment by wpyok500** [comment]
@Just2co 你修改的gop有在github发布吗？

**Comment by Just2co** [comment]
@wpyok500 我要是有这么大的本事倒好了，@Peytonlan 他好像会go语，让他改改

**Comment by SeaHOH** [comment]
@MeABc
问问进度如何，servername 的处理能一起修复了吗？

**Comment by SeaHOH** [comment]
我说的进度是你上次更新的，不是这个啊。 :sweat_smile:

**Comment by MeABc** [comment]
人工筛选”ip 是最好的。。

**Comment by SeaHOH** [comment]
突然发现那家伙把 comment 删掉了，看起来就像我在自言自语。。。

**Comment by wpyok500** [comment]
@MeABc 在这里先感谢接手开发，辛苦了。

**Comment by linux40** [comment]
quic是怎么用？放到ip.txt里面么？

**Comment by SeaHOH** [comment]
>quic是怎么用？

暂不支持

**Comment by linux40** [comment]
今天自己扫的sni都挂了，新的也扫不出来，这几天忙完了试试goproxy（换这个工具前一直用的goagent，还坚持到了19大。。。）

**Comment by SeaHOH** [comment]
172.217.0.0/16
216.58.0.0/16
108.177.0.0/16

试试

**Comment by wpyok500** [comment]
只扫到四个
216.58.227.71
216.58.227.70
216.58.227.68
216.58.227.69
