### ISSUE TITLE
无法找到 gevent 但安装了1.2.2的。

### ISSUE THREAD

**Issue by linux40** [SeaHOH/GotoX#60]
我把python文件夹改成了到/usr/lib/python3.6的软链接也没用。

**Comment by SeaHOH** [comment]
请问你是怎么运行的？
正确方式是不要下载 Windows 用的包，直接下载源码，
在终端运行 `python3 start.py` ，
或 `python start.py`（需配置默认版本为 3）。

**Comment by linux40** [comment]
之前下的zip包，但是clone一份就好了。
