### ISSUE TITLE
"FAKECERT None None" 失败

### ISSUE THREAD

**Issue by NAVrasZ** [SeaHOH/GotoX#68]
L4:2028-> "FAKECERT None None" 失败，code 400, message Bad request syntax (')\x02\x9b\x02')
L4:2028-> - - [28/Apr/2018 15:53:23] ")\x9b" 400 -

偶尔出这个红字但不影响使用

另外,,
在`控制面板--地区--非unicode程序`设置为英文时启动报错
~~`忘了截图貌似是unable to parse什么的`~~

**Comment by SeaHOH** [comment]
全是这样吗？这是访问什么地址？

>在控制面板--地区--非unicode程序设置为英文时启动报错
忘了截图貌似是unable to parse什么的

不改为英文特别影响你使用吗？如果不影响我就暂时忽略这个问题。

**Comment by NAVrasZ** [comment]
gotox报错之后貌似没有进入运行状态
不影响，只是有些indie游戏不用英文显示不正常，之后就忘记改回来了hhh

**Comment by SeaHOH** [comment]
我是说这个错误多不多，影不影响使用。

**Comment by NAVrasZ** [comment]
github抽风ing...
>全是这样吗？这是访问什么地址？
搜了下日志报错之前有各种网址
![capture](https://user-images.githubusercontent.com/20354364/39394546-bb38138c-4b05-11e8-97b8-cad374c6806d.PNG)
但访问正常
>不改为英文特别影响你使用吗？
![2](https://user-images.githubusercontent.com/20354364/39394641-ea3ca106-4b06-11e8-8563-7f99c189541c.PNG)
不影响，只是有些游戏不用英文显示不正常，之后就忘记改回来了hhh

**Comment by SeaHOH** [comment]
就这一条？可能是偶发网络错误引发。暂时忽略。

**Comment by NAVrasZ** [comment]
![capture](https://user-images.githubusercontent.com/20354364/39397737-e23bd406-4b36-11e8-82ce-5a8ce72254ec.PNG)
上面把chrome反复快速开关，每次都出一行
另外注意到chrome开着时，日志中很规律地每10分钟出现一次

gp的本机chrome启动截图
![3](https://user-images.githubusercontent.com/20354364/39397851-68656e4c-4b38-11e8-8e5a-4f435d47193b.PNG)

**Comment by SeaHOH** [comment]
超过 15 分钟，没有复现。主要我啥扩展都没有。

**Comment by NAVrasZ** [comment]
启动时是只开了switchyomega测的
![1](https://user-images.githubusercontent.com/20354364/39398266-f189c966-4b3d-11e8-811f-4f402fc3105b.PNG)
10分钟重复记得是开了除了idm外的三个，在看youtube

**Comment by SeaHOH** [comment]
感觉没影响使用。

**Comment by NAVrasZ** [comment]
确实没影响
只是有就提出来了xD

**Comment by NAVrasZ** [comment]
![1](https://user-images.githubusercontent.com/20354364/39398798-9c145dae-4b45-11e8-8a41-e8396472e731.PNG)
mtalk.google.com:5228的时间和gt报错符合
 00:32:54只有这一个url
只开了chrome://net-internals/#events 这一个tab

**Comment by SeaHOH** [comment]
还真是，我再看看。

**Comment by SeaHOH** [comment]
https://www.zhihu.com/question/23812421
实在想不到办法转发出去，包含 `google.com` 字样的 servername 是被封锁的，
而且 mtalk.google.com:5228，这个端口应该是有专门的服务器，一般 gws 不支持。

你能不能抓个 GoProxy 转发的包，我怀疑实际上并没有转发出去，只是没有报错而已。

**Comment by NAVrasZ** [comment]
原来这样``

用fiddler试了下作为gp前置，日志里没有mtalk的连接...
直接用gp全局连
http://portquiz.net:666/ `"error": "API error 1 (urlfetch: INVALID_URL)"`
https://mtalk.google.com:5228 `This site can’t provide a secure connection: mtalk.google.com sent an invalid response.`
而且确实gp里不显示有错

**Comment by SeaHOH** [comment]
103a8a6894ccfce51c50711d906f2b2c3e43511b
这个修改对握手进行了检查，对不支持的协议会直接丢弃，不再报错。
你看看有效果没有。

**Comment by NAVrasZ** [comment]
感谢海大挂念，这是更新后的
![image](https://user-images.githubusercontent.com/20354364/41810213-600dc61a-772d-11e8-8e5c-af9f563e894f.png)

**Comment by SeaHOH** [comment]
对了，这个修改只能修复`FAKECERT None None`，似乎对`FAKECERT None hostname`不起作用。
有点搞混了，我再改改。

**Comment by SeaHOH** [comment]
b68f285f8ff5bf1845405e28c2548e06c370d71a 这回应该修复了
