### ISSUE TITLE
证书已经手动导入了（受信任的根证书颁发者），访问https页面仍然错误

### ISSUE THREAD

**Issue by MyYellowBlanket** [SeaHOH/GotoX#7]
Chrome 浏览器 版本 54.0.2840.99 m (64-bit)
**NET::ERR_CERT_COMMON_NAME_INVALID**

![image](https://cloud.githubusercontent.com/assets/11293327/21176909/cd541640-c223-11e6-890e-c9e487c8d806.png)
![image](https://cloud.githubusercontent.com/assets/11293327/21176934/ea8a0dbe-c223-11e6-82e0-f8a9872d1e29.png)
![image](https://cloud.githubusercontent.com/assets/11293327/21176971/0d8b4152-c224-11e6-8dd1-a33c9de40e4d.png)

**Comment by SeaHOH** [comment]
其它浏览器呢？日志是否有提示 **无法伪造证书**？

**Comment by MyYellowBlanket** [comment]
刚刚试了IE浏览器（设置IE代理）没有问题

**Comment by MyYellowBlanket** [comment]
不过IE浏览器的证书截图看起来跟chrome稍有不同：
![image](https://cloud.githubusercontent.com/assets/11293327/21177580/c4c4d976-c226-11e6-8693-c02527352c10.png)
![image](https://cloud.githubusercontent.com/assets/11293327/21177585/ca4b6f68-c226-11e6-95a9-db75c5c8d647.png)
没有“:443”这个后缀

**Comment by SeaHOH** [comment]
看到了，你先从 win_py35 分支下载覆盖试一下。
我再想一下，等会儿答复你。

**Comment by SeaHOH** [comment]
不好意思，没找到原因。
你使用 py35 后是否正常？

**Comment by MyYellowBlanket** [comment]
是下载win_py35分支的.zip，解压后直接运行GotoX.exe吗？我这里显示python\python.exe: can't open file 'start.py': [Errno 2] No such file or directory

**Comment by SeaHOH** [comment]
这个是单独的便携 python。
不是直接运行，把它解压到先前的目录覆盖。

**Comment by MyYellowBlanket** [comment]
09:49:41 E 无法找到 pyopenssl，请安装 pyopenssl-16.0.0 以上版本，或将相应 .egg
放到 'E:\\PC\\Desktop\\新建文件夹\\python\\site-packages' 文件夹！

**Comment by jzp820927** [comment]
把之前的 egg 文件放进去就行了。

**Comment by MyYellowBlanket** [comment]
哦我知道了。得把原来的site-packages文件夹里的OpenSSL-16.1.0-cp27-win_amd64.egg删掉才行。。不知道为什么。。我现在试试win_py35。
======
我是先解压GotoX-3.3.0-cp27-win_amd64.7z， 再解压GotoX-win_py35.zip并把其中的内容复制过去的，重名的文件(夹)都替换(合并)了，然后才有的上面的“无法找到”。

**Comment by MyYellowBlanket** [comment]
使用py35也是一样的。IE没有问题，chrome无法访问。NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by SeaHOH** [comment]
忘记告诉你要删除旧版 egg 文件了。
##

好奇怪，看代码应该不会把 `:443` 包含进去。
最新版火狐刚试过，也没复现，不能帮助你，很遗憾。
谢谢反馈。

**Comment by SeaHOH** [comment]
@MyYellowBlanket 
对了，你是下载的发布版本吗？那个代码不是最新的。
你可以尝试一下最新代码，把两个分支都下载下来合并，然后运行就可以了。
以前的 cert 文件夹可以保留，不必重新导入证书。

**Comment by jzp820927** [comment]
这个证书是挺奇怪的，居然还带端口。

**Comment by SeaHOH** [comment]
@jzp820927 
这种情况在代码中已经考虑过。

**Comment by SeaHOH** [comment]
@jzp820927 
这种情况在代码中已经考虑过。

**Comment by jzp820927** [comment]
那就不知道是神马情况了。

**Comment by MyYellowBlanket** [comment]
我用的是这个版本：GotoX-3.3.0-cp27-win_amd64.7z。我不知道怎么合代码，不过我想重新上传服务端试试，之前用的xx-net上传的服务端。后者的证书不会有“:443”这个后缀。不太清楚怎么上传GotoX的服务端

**Comment by SeaHOH** [comment]
跟服务端完全没关系。
刚更新发布了 3.3.2 版本，你可以下载来试一下。
把你先前的 cert 文件夹复制进去就不用重新导入证书了。

**Comment by SeaHOH** [comment]
跟服务端完全没关系。
刚更新发布了 3.3.2 版本，你可以下载来试一下。
把你先前的 cert 文件夹复制进去就不用重新导入证书了。

**Comment by MyYellowBlanket** [comment]
目前是连不上：本地从 GAE 获‘...’失败。不确定证书可不可以，应该是好了，有一个绿色的锁标志。

**Comment by SeaHOH** [comment]
好的，我看到错误原因了。
已修复，你可以单独下载最新 GAEUpdata.py 文件更新。

**Comment by MyYellowBlanket** [comment]
好了，看起来是正常的。我看到改的那一行代码了:-D。谢谢，chrome的证书已经没有问题了。 Opera Browser gives a warning about public sites that use certificates from local issuers, 但是可以访问。但火狐会报告：“连接 www.google.com 时发生错误。 对等端的证书有一个无效的签名。 错误代码: SEC_ERROR_BAD_SIGNATURE”。不过以上已经解决了我的问题。

**Comment by SeaHOH** [comment]
火狐还有错误吗？
你试一下将 cert 文件夹下的 certs 文件夹删除，其它不要动，然后重启 GotoX。

**Comment by MyYellowBlanket** [comment]
火狐依然报错

**Comment by SeaHOH** [comment]
我这儿火狐 50.0 没问题，你的是什么版本？

**Comment by MyYellowBlanket** [comment]
确实是，在火狐浏览器中重新导入证书就好了。

**Comment by SeaHOH** [comment]
解决了就好，大家共同进步嘛。
