### ISSUE TITLE
一启动就一堆黄字，什么意思？

### ISSUE THREAD

**Issue by wpyok500** [SeaHOH/GotoX#74]
![image](https://user-images.githubusercontent.com/14154547/39576503-e632a9f8-4f10-11e8-8226-6386a2c8a237.png)

![image](https://user-images.githubusercontent.com/14154547/39576521-fc3abfce-4f10-11e8-9bd7-bf6cf2d853dd.png)

![image](https://user-images.githubusercontent.com/14154547/39576532-0924fa60-4f11-11e8-8272-6824f93ceccf.png)

**Comment by SeaHOH** [comment]
解析谷歌错误，无视即可。
