### ISSUE TITLE
无法解析主机，怎么解决

### ISSUE THREAD

**Issue by boseliy** [SeaHOH/GotoX#79]
所有的网站都是无法解析主机，然后上不了网，请问怎么解决啊
使用的是ipv6
![1](https://user-images.githubusercontent.com/39125354/40000735-1eef33ba-577c-11e8-978a-185d4a593a31.jpg)

**Comment by SeaHOH** [comment]
注释里面写清楚了的。
因为你的 DNS 不是 DNS64，所以 ip 可以只放 IPv6，但设置必须设置成 ipv46。

**Comment by boseliy** [comment]
设置成了ipv46，但是不能上youtub和脸书，显示：本地从 GAE 获取 'https://www.facebook.com/' 失败

**Comment by SeaHOH** [comment]
你放 IP 没有？？

**Comment by wpyok500** [comment]
一直使用ipv46，也是 同样问题
![image](https://user-images.githubusercontent.com/14154547/40095593-7c80a3ea-58ff-11e8-87e2-b3a584988ef9.png)

**Comment by wpyok500** [comment]
在哪设置？

**Comment by SeaHOH** [comment]
Config.ini 留空即可，或者自己配置好能解析的系统 DNS 设置。
```ini
[dns]
overhttpsecs = 
```

**Comment by SeaHOH** [comment]
还有一招就是在规则中设置固定 IP，这个服务器 IP 估计极少变动。

**Comment by wpyok500** [comment]
HOSTS?

**Comment by SeaHOH** [comment]
ActionFilter.ini，direct 或 forward 指定 IP。

**Comment by boseliy** [comment]
默认就是这样设置的，
[dns]
overhttpsecs = 

国外的网站上不了，国内的百度新浪都能上，国外的两个是这样的
![1](https://user-images.githubusercontent.com/39125354/40266780-a9b7bd2e-5b40-11e8-8b94-67bf67295c90.jpg)
![2](https://user-images.githubusercontent.com/39125354/40266781-a9f7f1be-5b40-11e8-87b2-4f006e620e89.jpg)
ip的话，这样设置的
![3](https://user-images.githubusercontent.com/39125354/40266860-29f53baa-5b42-11e8-9eda-c50804eb1065.jpg)
但是ip.txt文件里有很多ip地址。不知道是不是写到txt文件里就行

**Comment by SeaHOH** [comment]
@boseliy 
你这个情况和  overhttpsecs 无关。
先更新到 3.4.2，把 ip.txt 里面所有 IP 替换成 IPv6。

**Comment by SeaHOH** [comment]
请到 releases 页面下载。
IPv6 的谷歌 IP，自己找，比如 XX-Net 自带的。

话说，我这个和 XX-Net 不一样，建议不熟悉网络基本概念的就不要用 GotoX 了。

**Comment by SeaHOH** [comment]
#55
