### ISSUE TITLE
youtube直播不能看

### ISSUE THREAD

**Issue by cixi666** [SeaHOH/GotoX#8]

**Comment by jzp820927** [comment]
贴日志看看？

**Comment by SeaHOH** [comment]
给个地址，我好久没看过直播了，视频也很少看。

**Comment by cixi666** [comment]
https://www.youtube.com/watch?v=5M7czC0VR_Q

**Comment by SeaHOH** [comment]
没毛病，就是慢。你改过默认设置和规则吗？
![x2scrap](https://cloud.githubusercontent.com/assets/8470820/21541817/7c75ebea-cdf4-11e6-8109-f0268b04efc2.jpg)

**Comment by SeaHOH** [comment]
找到毛病了。
找到 ActionFilter.ini > [1-block] > #.youtube-nocookie.com 取消注释。
