### ISSUE TITLE
vimeo 403错误

### ISSUE THREAD

**Issue by wpyok500** [SeaHOH/GotoX#83]
![image](https://user-images.githubusercontent.com/14154547/41199030-335870cc-6cbd-11e8-9146-f450dc57af74.png)

![image](https://user-images.githubusercontent.com/14154547/41198976-e07b9532-6cbc-11e8-8328-53ddf14b5773.png)

**Comment by SeaHOH** [comment]
对于 GAE 来说很正常，看看能通过机器人验证不。

**Comment by wpyok500** [comment]
可以通过人机验证，但一直在转圈圈。
![image](https://user-images.githubusercontent.com/14154547/41881912-a28c38f4-7918-11e8-9220-d154506f9602.png)
![image](https://user-images.githubusercontent.com/14154547/41881933-bc52e972-7918-11e8-8c5a-ea2906dad3db.png)

**Comment by SeaHOH** [comment]
的确无法解锁，可以单独配置 SNI。
```ini
[forward/direct-序数]
vimeo.com = sni ips
```

**Comment by masktao** [comment]
vimeo以前是可以用goproxy访问的，后来就永远访问不了了

**Comment by SeaHOH** [comment]
可以直连
