### ISSUE TITLE
最新code 下载 现在动不到就404  没有上传数据

### ISSUE THREAD

**Issue by wpyok500** [SeaHOH/GotoX#93]
![image](https://user-images.githubusercontent.com/14154547/46251627-92123d80-c48a-11e8-8cf8-d790c91e17f1.png)

![image](https://user-images.githubusercontent.com/14154547/46253128-80d72a00-c4a6-11e8-8f38-3cc504bd6f5c.png)

**Comment by wpyok500** [comment]
ip.use有ip，重启后又可访问google

**Comment by SeaHOH** [comment]
前面提到过，服务器有变化。
我这段时间有点忙，来不及修改，你按照之前说的使用固定列表就行。
排除 google_com 类型的 IP，忽视启动时的提示。

**Comment by SeaHOH** [comment]
已发布新版
