### ISSUE TITLE
DNS 重复选项错误

### ISSUE THREAD

**Issue by qingjiangshui** [SeaHOH/GotoX#96]
下载的是刚发布的版本，只在config里填入了GAE名称和密码，启动时出现图示错误。请问，这是什么原因？
![snipaste_20190119_221644](https://user-images.githubusercontent.com/3205221/51428006-697ca200-1c39-11e9-82dc-88d0beb2b5eb.png)

**Comment by SeaHOH** [comment]
忘记改了。。。
最后几个修改时，辅助一直没重启过。

**Comment by SeaHOH** [comment]
不对，是配置混入了重复项。

**Comment by SeaHOH** [comment]
错误的版本已重新发布，谢谢。

**Comment by yeligou** [comment]
大海兄，winxp安装了python3.2，程序一闪而过，没法用，请问还需要安装别的吗？

**Comment by SeaHOH** [comment]
https://www.python.org/downloads/release/python-344/

最后一版支持 XP 的。

https://github.com/SeaHOH/GotoX/blob/master/requirements.txt

使用 pip 安装必需的模块。

**Comment by yeligou** [comment]
谢谢大海
