### ISSUE TITLE
gae-r6 uploader.bat闪退

### ISSUE THREAD

**Issue by 722tzz** [SeaHOH/GotoX#99]
[https://github.com/SeaHOH/GotoX/releases/tag/gae-r6](url)上边下的GotoX-gae-r6.7z包，uploader.bat双击后闪退。
在命令行下运行，报如下错误：
```
PS E:\GotoX-gae-r6> .\python27.exe uploader.py
Traceback (most recent call last):
  File "uploader.py", line 53, in <module>
    import ssl
  File "E:\GotoX-gae-r6\python27.zip\ssl.py", line 101, in <module>
    server_side=False, cert_reqs=CERT_NONE,
ImportError: cannot import name _SSLContext
```

**Comment by SeaHOH** [comment]
本机有安装 python？
设置一下环境变量：
```bat
SET PYTHONPATH=
SET PYTHONHOME=
```

**Comment by 722tzz** [comment]
还是报错啊。。

E:\GotoX-master\GotoX-gaeserver.goproxy
ascii


?褂?HTTP 代理：127.0.0.1:8087
Traceback (most recent call last):
  File "E:\GotoX-master\GotoX-gaeserver.goproxy\uploader.py", line 69, in <module>
    println(u'浣跨敤 HTTP 浠ｇ悊锛?27.0.0.1:8087')
  File "E:\GotoX-master\GotoX-gaeserver.goproxy\uploader.py", line 17, in println
    file.write(s.encode(sys.getfilesystemencoding(), 'replace') + os.linesep)
IOError: [Errno 0] Error

**Comment by SeaHOH** [comment]
试试上次传的修改版本
https://github.com/SeaHOH/GotoX/releases/download/gae-r6/GotoX-gae-r6-c1.7z

**Comment by SeaHOH** [comment]
https://github.com/SeaHOH/GotoX/issues/92#issuecomment-466670840

**Comment by 722tzz** [comment]
GotoX-gae-r6-c1.7z报相同的错，按楼上链接的方法把CMD属性里面设成旧版控制台就正常了
